// Code generated by ent, DO NOT EDIT.

package agenttrace

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/papercomputeco/tapes/pkg/storage/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldContainsFold(FieldID, id))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldEQ(FieldVersion, v))
}

// Timestamp applies equality check predicate on the "timestamp" field. It's identical to TimestampEQ.
func Timestamp(v string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldEQ(FieldTimestamp, v))
}

// VcsType applies equality check predicate on the "vcs_type" field. It's identical to VcsTypeEQ.
func VcsType(v string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldEQ(FieldVcsType, v))
}

// VcsRevision applies equality check predicate on the "vcs_revision" field. It's identical to VcsRevisionEQ.
func VcsRevision(v string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldEQ(FieldVcsRevision, v))
}

// ToolName applies equality check predicate on the "tool_name" field. It's identical to ToolNameEQ.
func ToolName(v string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldEQ(FieldToolName, v))
}

// ToolVersion applies equality check predicate on the "tool_version" field. It's identical to ToolVersionEQ.
func ToolVersion(v string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldEQ(FieldToolVersion, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldEQ(FieldCreatedAt, v))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldLTE(FieldVersion, v))
}

// VersionContains applies the Contains predicate on the "version" field.
func VersionContains(v string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldContains(FieldVersion, v))
}

// VersionHasPrefix applies the HasPrefix predicate on the "version" field.
func VersionHasPrefix(v string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldHasPrefix(FieldVersion, v))
}

// VersionHasSuffix applies the HasSuffix predicate on the "version" field.
func VersionHasSuffix(v string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldHasSuffix(FieldVersion, v))
}

// VersionEqualFold applies the EqualFold predicate on the "version" field.
func VersionEqualFold(v string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldEqualFold(FieldVersion, v))
}

// VersionContainsFold applies the ContainsFold predicate on the "version" field.
func VersionContainsFold(v string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldContainsFold(FieldVersion, v))
}

// TimestampEQ applies the EQ predicate on the "timestamp" field.
func TimestampEQ(v string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldEQ(FieldTimestamp, v))
}

// TimestampNEQ applies the NEQ predicate on the "timestamp" field.
func TimestampNEQ(v string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldNEQ(FieldTimestamp, v))
}

// TimestampIn applies the In predicate on the "timestamp" field.
func TimestampIn(vs ...string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldIn(FieldTimestamp, vs...))
}

// TimestampNotIn applies the NotIn predicate on the "timestamp" field.
func TimestampNotIn(vs ...string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldNotIn(FieldTimestamp, vs...))
}

// TimestampGT applies the GT predicate on the "timestamp" field.
func TimestampGT(v string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldGT(FieldTimestamp, v))
}

// TimestampGTE applies the GTE predicate on the "timestamp" field.
func TimestampGTE(v string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldGTE(FieldTimestamp, v))
}

// TimestampLT applies the LT predicate on the "timestamp" field.
func TimestampLT(v string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldLT(FieldTimestamp, v))
}

// TimestampLTE applies the LTE predicate on the "timestamp" field.
func TimestampLTE(v string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldLTE(FieldTimestamp, v))
}

// TimestampContains applies the Contains predicate on the "timestamp" field.
func TimestampContains(v string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldContains(FieldTimestamp, v))
}

// TimestampHasPrefix applies the HasPrefix predicate on the "timestamp" field.
func TimestampHasPrefix(v string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldHasPrefix(FieldTimestamp, v))
}

// TimestampHasSuffix applies the HasSuffix predicate on the "timestamp" field.
func TimestampHasSuffix(v string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldHasSuffix(FieldTimestamp, v))
}

// TimestampEqualFold applies the EqualFold predicate on the "timestamp" field.
func TimestampEqualFold(v string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldEqualFold(FieldTimestamp, v))
}

// TimestampContainsFold applies the ContainsFold predicate on the "timestamp" field.
func TimestampContainsFold(v string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldContainsFold(FieldTimestamp, v))
}

// VcsTypeEQ applies the EQ predicate on the "vcs_type" field.
func VcsTypeEQ(v string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldEQ(FieldVcsType, v))
}

// VcsTypeNEQ applies the NEQ predicate on the "vcs_type" field.
func VcsTypeNEQ(v string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldNEQ(FieldVcsType, v))
}

// VcsTypeIn applies the In predicate on the "vcs_type" field.
func VcsTypeIn(vs ...string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldIn(FieldVcsType, vs...))
}

// VcsTypeNotIn applies the NotIn predicate on the "vcs_type" field.
func VcsTypeNotIn(vs ...string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldNotIn(FieldVcsType, vs...))
}

// VcsTypeGT applies the GT predicate on the "vcs_type" field.
func VcsTypeGT(v string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldGT(FieldVcsType, v))
}

// VcsTypeGTE applies the GTE predicate on the "vcs_type" field.
func VcsTypeGTE(v string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldGTE(FieldVcsType, v))
}

// VcsTypeLT applies the LT predicate on the "vcs_type" field.
func VcsTypeLT(v string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldLT(FieldVcsType, v))
}

// VcsTypeLTE applies the LTE predicate on the "vcs_type" field.
func VcsTypeLTE(v string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldLTE(FieldVcsType, v))
}

// VcsTypeContains applies the Contains predicate on the "vcs_type" field.
func VcsTypeContains(v string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldContains(FieldVcsType, v))
}

// VcsTypeHasPrefix applies the HasPrefix predicate on the "vcs_type" field.
func VcsTypeHasPrefix(v string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldHasPrefix(FieldVcsType, v))
}

// VcsTypeHasSuffix applies the HasSuffix predicate on the "vcs_type" field.
func VcsTypeHasSuffix(v string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldHasSuffix(FieldVcsType, v))
}

// VcsTypeIsNil applies the IsNil predicate on the "vcs_type" field.
func VcsTypeIsNil() predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldIsNull(FieldVcsType))
}

// VcsTypeNotNil applies the NotNil predicate on the "vcs_type" field.
func VcsTypeNotNil() predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldNotNull(FieldVcsType))
}

// VcsTypeEqualFold applies the EqualFold predicate on the "vcs_type" field.
func VcsTypeEqualFold(v string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldEqualFold(FieldVcsType, v))
}

// VcsTypeContainsFold applies the ContainsFold predicate on the "vcs_type" field.
func VcsTypeContainsFold(v string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldContainsFold(FieldVcsType, v))
}

// VcsRevisionEQ applies the EQ predicate on the "vcs_revision" field.
func VcsRevisionEQ(v string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldEQ(FieldVcsRevision, v))
}

// VcsRevisionNEQ applies the NEQ predicate on the "vcs_revision" field.
func VcsRevisionNEQ(v string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldNEQ(FieldVcsRevision, v))
}

// VcsRevisionIn applies the In predicate on the "vcs_revision" field.
func VcsRevisionIn(vs ...string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldIn(FieldVcsRevision, vs...))
}

// VcsRevisionNotIn applies the NotIn predicate on the "vcs_revision" field.
func VcsRevisionNotIn(vs ...string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldNotIn(FieldVcsRevision, vs...))
}

// VcsRevisionGT applies the GT predicate on the "vcs_revision" field.
func VcsRevisionGT(v string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldGT(FieldVcsRevision, v))
}

// VcsRevisionGTE applies the GTE predicate on the "vcs_revision" field.
func VcsRevisionGTE(v string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldGTE(FieldVcsRevision, v))
}

// VcsRevisionLT applies the LT predicate on the "vcs_revision" field.
func VcsRevisionLT(v string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldLT(FieldVcsRevision, v))
}

// VcsRevisionLTE applies the LTE predicate on the "vcs_revision" field.
func VcsRevisionLTE(v string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldLTE(FieldVcsRevision, v))
}

// VcsRevisionContains applies the Contains predicate on the "vcs_revision" field.
func VcsRevisionContains(v string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldContains(FieldVcsRevision, v))
}

// VcsRevisionHasPrefix applies the HasPrefix predicate on the "vcs_revision" field.
func VcsRevisionHasPrefix(v string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldHasPrefix(FieldVcsRevision, v))
}

// VcsRevisionHasSuffix applies the HasSuffix predicate on the "vcs_revision" field.
func VcsRevisionHasSuffix(v string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldHasSuffix(FieldVcsRevision, v))
}

// VcsRevisionIsNil applies the IsNil predicate on the "vcs_revision" field.
func VcsRevisionIsNil() predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldIsNull(FieldVcsRevision))
}

// VcsRevisionNotNil applies the NotNil predicate on the "vcs_revision" field.
func VcsRevisionNotNil() predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldNotNull(FieldVcsRevision))
}

// VcsRevisionEqualFold applies the EqualFold predicate on the "vcs_revision" field.
func VcsRevisionEqualFold(v string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldEqualFold(FieldVcsRevision, v))
}

// VcsRevisionContainsFold applies the ContainsFold predicate on the "vcs_revision" field.
func VcsRevisionContainsFold(v string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldContainsFold(FieldVcsRevision, v))
}

// ToolNameEQ applies the EQ predicate on the "tool_name" field.
func ToolNameEQ(v string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldEQ(FieldToolName, v))
}

// ToolNameNEQ applies the NEQ predicate on the "tool_name" field.
func ToolNameNEQ(v string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldNEQ(FieldToolName, v))
}

// ToolNameIn applies the In predicate on the "tool_name" field.
func ToolNameIn(vs ...string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldIn(FieldToolName, vs...))
}

// ToolNameNotIn applies the NotIn predicate on the "tool_name" field.
func ToolNameNotIn(vs ...string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldNotIn(FieldToolName, vs...))
}

// ToolNameGT applies the GT predicate on the "tool_name" field.
func ToolNameGT(v string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldGT(FieldToolName, v))
}

// ToolNameGTE applies the GTE predicate on the "tool_name" field.
func ToolNameGTE(v string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldGTE(FieldToolName, v))
}

// ToolNameLT applies the LT predicate on the "tool_name" field.
func ToolNameLT(v string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldLT(FieldToolName, v))
}

// ToolNameLTE applies the LTE predicate on the "tool_name" field.
func ToolNameLTE(v string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldLTE(FieldToolName, v))
}

// ToolNameContains applies the Contains predicate on the "tool_name" field.
func ToolNameContains(v string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldContains(FieldToolName, v))
}

// ToolNameHasPrefix applies the HasPrefix predicate on the "tool_name" field.
func ToolNameHasPrefix(v string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldHasPrefix(FieldToolName, v))
}

// ToolNameHasSuffix applies the HasSuffix predicate on the "tool_name" field.
func ToolNameHasSuffix(v string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldHasSuffix(FieldToolName, v))
}

// ToolNameIsNil applies the IsNil predicate on the "tool_name" field.
func ToolNameIsNil() predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldIsNull(FieldToolName))
}

// ToolNameNotNil applies the NotNil predicate on the "tool_name" field.
func ToolNameNotNil() predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldNotNull(FieldToolName))
}

// ToolNameEqualFold applies the EqualFold predicate on the "tool_name" field.
func ToolNameEqualFold(v string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldEqualFold(FieldToolName, v))
}

// ToolNameContainsFold applies the ContainsFold predicate on the "tool_name" field.
func ToolNameContainsFold(v string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldContainsFold(FieldToolName, v))
}

// ToolVersionEQ applies the EQ predicate on the "tool_version" field.
func ToolVersionEQ(v string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldEQ(FieldToolVersion, v))
}

// ToolVersionNEQ applies the NEQ predicate on the "tool_version" field.
func ToolVersionNEQ(v string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldNEQ(FieldToolVersion, v))
}

// ToolVersionIn applies the In predicate on the "tool_version" field.
func ToolVersionIn(vs ...string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldIn(FieldToolVersion, vs...))
}

// ToolVersionNotIn applies the NotIn predicate on the "tool_version" field.
func ToolVersionNotIn(vs ...string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldNotIn(FieldToolVersion, vs...))
}

// ToolVersionGT applies the GT predicate on the "tool_version" field.
func ToolVersionGT(v string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldGT(FieldToolVersion, v))
}

// ToolVersionGTE applies the GTE predicate on the "tool_version" field.
func ToolVersionGTE(v string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldGTE(FieldToolVersion, v))
}

// ToolVersionLT applies the LT predicate on the "tool_version" field.
func ToolVersionLT(v string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldLT(FieldToolVersion, v))
}

// ToolVersionLTE applies the LTE predicate on the "tool_version" field.
func ToolVersionLTE(v string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldLTE(FieldToolVersion, v))
}

// ToolVersionContains applies the Contains predicate on the "tool_version" field.
func ToolVersionContains(v string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldContains(FieldToolVersion, v))
}

// ToolVersionHasPrefix applies the HasPrefix predicate on the "tool_version" field.
func ToolVersionHasPrefix(v string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldHasPrefix(FieldToolVersion, v))
}

// ToolVersionHasSuffix applies the HasSuffix predicate on the "tool_version" field.
func ToolVersionHasSuffix(v string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldHasSuffix(FieldToolVersion, v))
}

// ToolVersionIsNil applies the IsNil predicate on the "tool_version" field.
func ToolVersionIsNil() predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldIsNull(FieldToolVersion))
}

// ToolVersionNotNil applies the NotNil predicate on the "tool_version" field.
func ToolVersionNotNil() predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldNotNull(FieldToolVersion))
}

// ToolVersionEqualFold applies the EqualFold predicate on the "tool_version" field.
func ToolVersionEqualFold(v string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldEqualFold(FieldToolVersion, v))
}

// ToolVersionContainsFold applies the ContainsFold predicate on the "tool_version" field.
func ToolVersionContainsFold(v string) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldContainsFold(FieldToolVersion, v))
}

// MetadataIsNil applies the IsNil predicate on the "metadata" field.
func MetadataIsNil() predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldIsNull(FieldMetadata))
}

// MetadataNotNil applies the NotNil predicate on the "metadata" field.
func MetadataNotNil() predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldNotNull(FieldMetadata))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AgentTrace {
	return predicate.AgentTrace(sql.FieldLTE(FieldCreatedAt, v))
}

// HasFiles applies the HasEdge predicate on the "files" edge.
func HasFiles() predicate.AgentTrace {
	return predicate.AgentTrace(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, FilesTable, FilesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasFilesWith applies the HasEdge predicate on the "files" edge with a given conditions (other predicates).
func HasFilesWith(preds ...predicate.AgentTraceFile) predicate.AgentTrace {
	return predicate.AgentTrace(func(s *sql.Selector) {
		step := newFilesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AgentTrace) predicate.AgentTrace {
	return predicate.AgentTrace(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AgentTrace) predicate.AgentTrace {
	return predicate.AgentTrace(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AgentTrace) predicate.AgentTrace {
	return predicate.AgentTrace(sql.NotPredicates(p))
}
