// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ancestry_chains.sql

package gensqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const ancestryChains = `-- name: AncestryChains :many
SELECT
    COALESCE(walk.start_hash::text, '') AS start_hash,
    COALESCE(walk.hash::text, '') AS hash,
    COALESCE(walk.parent_hash::text, '') AS parent_hash,
    COALESCE(walk.bucket::jsonb, '{}'::jsonb) AS bucket,
    COALESCE(walk.type::text, '') AS type,
    COALESCE(walk.role::text, '') AS role,
    COALESCE(walk.content::jsonb, '[]'::jsonb) AS content,
    COALESCE(walk.model::text, '') AS model,
    COALESCE(walk.provider::text, '') AS provider,
    COALESCE(walk.agent_name::text, '') AS agent_name,
    COALESCE(walk.stop_reason::text, '') AS stop_reason,
    COALESCE(walk.prompt_tokens::integer, 0) AS prompt_tokens,
    COALESCE(walk.completion_tokens::integer, 0) AS completion_tokens,
    COALESCE(walk.total_tokens::integer, 0) AS total_tokens,
    COALESCE(walk.cache_creation_input_tokens::integer, 0) AS cache_creation_input_tokens,
    COALESCE(walk.cache_read_input_tokens::integer, 0) AS cache_read_input_tokens,
    COALESCE(walk.total_duration_ns::bigint, 0) AS total_duration_ns,
    COALESCE(walk.prompt_duration_ns::bigint, 0) AS prompt_duration_ns,
    COALESCE(walk.project::text, '') AS project,
    walk.created_at::timestamptz AS created_at,
    walk.depth::integer AS depth,
    walk.has_usage::boolean AS has_usage,
    COALESCE(walk.node_kind::text, '') AS node_kind,
    COALESCE(walk.parent_tool_use_id::text, '') AS parent_tool_use_id
FROM ancestry_chains_rows($1::text[], $2::integer) AS walk(
    start_hash,
    hash,
    parent_hash,
    bucket,
    type,
    role,
    content,
    model,
    provider,
    agent_name,
    stop_reason,
    prompt_tokens,
    completion_tokens,
    total_tokens,
    cache_creation_input_tokens,
    cache_read_input_tokens,
    total_duration_ns,
    prompt_duration_ns,
    project,
    created_at,
    depth,
    has_usage,
    node_kind,
    parent_tool_use_id
)
ORDER BY walk.start_hash, walk.depth
`

type AncestryChainsParams struct {
	Hashes   []string
	MaxDepth int32
}

type AncestryChainsRow struct {
	StartHash                interface{}
	Hash                     interface{}
	ParentHash               interface{}
	Bucket                   interface{}
	Type                     interface{}
	Role                     interface{}
	Content                  interface{}
	Model                    interface{}
	Provider                 interface{}
	AgentName                interface{}
	StopReason               interface{}
	PromptTokens             interface{}
	CompletionTokens         interface{}
	TotalTokens              interface{}
	CacheCreationInputTokens interface{}
	CacheReadInputTokens     interface{}
	TotalDurationNs          interface{}
	PromptDurationNs         interface{}
	Project                  interface{}
	CreatedAt                pgtype.Timestamptz
	Depth                    int32
	HasUsage                 bool
	NodeKind                 interface{}
	ParentToolUseID          interface{}
}

func (q *Queries) AncestryChains(ctx context.Context, arg AncestryChainsParams) ([]AncestryChainsRow, error) {
	rows, err := q.db.Query(ctx, ancestryChains, arg.Hashes, arg.MaxDepth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AncestryChainsRow
	for rows.Next() {
		var i AncestryChainsRow
		if err := rows.Scan(
			&i.StartHash,
			&i.Hash,
			&i.ParentHash,
			&i.Bucket,
			&i.Type,
			&i.Role,
			&i.Content,
			&i.Model,
			&i.Provider,
			&i.AgentName,
			&i.StopReason,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.TotalTokens,
			&i.CacheCreationInputTokens,
			&i.CacheReadInputTokens,
			&i.TotalDurationNs,
			&i.PromptDurationNs,
			&i.Project,
			&i.CreatedAt,
			&i.Depth,
			&i.HasUsage,
			&i.NodeKind,
			&i.ParentToolUseID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
