// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cout_turns.sql

package gensqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countTurns = `-- name: CountTurns :one
SELECT COUNT(*)
FROM nodes n
WHERE ($1::text IS NULL OR n.project = $1::text)
  AND ($2::text IS NULL OR n.agent_name = $2::text)
  AND ($3::text IS NULL OR n.model = $3::text)
  AND ($4::text IS NULL OR n.provider = $4::text)
  AND ($5::timestamptz IS NULL OR n.created_at >= $5::timestamptz)
  AND ($6::timestamptz IS NULL OR n.created_at < $6::timestamptz)
`

type CountTurnsParams struct {
	ProjectFilter  pgtype.Text
	AgentFilter    pgtype.Text
	ModelFilter    pgtype.Text
	ProviderFilter pgtype.Text
	SinceFilter    pgtype.Timestamptz
	UntilFilter    pgtype.Timestamptz
}

func (q *Queries) CountTurns(ctx context.Context, arg CountTurnsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTurns,
		arg.ProjectFilter,
		arg.AgentFilter,
		arg.ModelFilter,
		arg.ProviderFilter,
		arg.SinceFilter,
		arg.UntilFilter,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}
