// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: derive.sql

package gensqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRawTurn = `-- name: GetRawTurn :one
SELECT id, org_id, source, provider, agent_name,
       harness_id, harness_session_id, request_id,
       raw_request, response, meta, session_envelope, received_at
FROM raw_turns
WHERE id = $1
`

func (q *Queries) GetRawTurn(ctx context.Context, id int64) (RawTurn, error) {
	row := q.db.QueryRow(ctx, getRawTurn, id)
	var i RawTurn
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Source,
		&i.Provider,
		&i.AgentName,
		&i.HarnessID,
		&i.HarnessSessionID,
		&i.RequestID,
		&i.RawRequest,
		&i.Response,
		&i.Meta,
		&i.SessionEnvelope,
		&i.ReceivedAt,
	)
	return i, err
}

const listRawTurnIndex = `-- name: ListRawTurnIndex :many
SELECT id, org_id, source, harness_id, harness_session_id, received_at, meta
FROM raw_turns
WHERE id > $1
ORDER BY id
LIMIT $2
`

type ListRawTurnIndexParams struct {
	AfterID  int64
	PageSize int32
}

type ListRawTurnIndexRow struct {
	ID               int64
	OrgID            pgtype.UUID
	Source           string
	HarnessID        string
	HarnessSessionID string
	ReceivedAt       pgtype.Timestamptz
	Meta             []byte
}

// Lightweight scan for the deriver's ordering pass: identity and
// timing only, no payloads. meta rides along because it carries the
// original capture time for backfilled rows.
func (q *Queries) ListRawTurnIndex(ctx context.Context, arg ListRawTurnIndexParams) ([]ListRawTurnIndexRow, error) {
	rows, err := q.db.Query(ctx, listRawTurnIndex, arg.AfterID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRawTurnIndexRow
	for rows.Next() {
		var i ListRawTurnIndexRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Source,
			&i.HarnessID,
			&i.HarnessSessionID,
			&i.ReceivedAt,
			&i.Meta,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sessionIDByHarnessKey = `-- name: SessionIDByHarnessKey :one
SELECT id FROM sessions
WHERE org_id = $1
  AND harness_id = $2
  AND harness_session_id = $3
`

type SessionIDByHarnessKeyParams struct {
	OrgID            pgtype.UUID
	HarnessID        string
	HarnessSessionID string
}

// Resolve the sessions row for one raw turn's natural key. The deriver
// only attributes to existing sessions; it never creates them.
func (q *Queries) SessionIDByHarnessKey(ctx context.Context, arg SessionIDByHarnessKeyParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, sessionIDByHarnessKey, arg.OrgID, arg.HarnessID, arg.HarnessSessionID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
