// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: derive.sql

package gensqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRawTurn = `-- name: GetRawTurn :one
SELECT r.id, r.org_id, r.source, r.provider, r.agent_name,
       COALESCE(c.harness_id, r.harness_id) AS harness_id,
       COALESCE(c.harness_session_id, r.harness_session_id) AS harness_session_id,
       r.request_id, r.raw_request, r.response,
       (CASE WHEN c.id IS NULL THEN r.meta
             ELSE jsonb_set(r.meta, '{thread_id}', to_jsonb(c.thread_id), true)
        END)::jsonb AS meta,
       (CASE WHEN c.id IS NULL THEN r.session_envelope
             WHEN c.parent_harness_session_id IS NULL THEN
                  (COALESCE(r.session_envelope, '{}'::jsonb) - 'parent_harness_session_id') ||
                  jsonb_build_object(
                      'harness_id', c.harness_id,
                      'harness_session_id', c.harness_session_id
                  )
             ELSE COALESCE(r.session_envelope, '{}'::jsonb) || jsonb_build_object(
                      'harness_id', c.harness_id,
                      'harness_session_id', c.harness_session_id,
                      'parent_harness_session_id', c.parent_harness_session_id
                  )
        END)::jsonb AS session_envelope,
       r.received_at,
       CASE
           WHEN jsonb_typeof(r.response -> 'message' -> 'content') = 'array'
                AND jsonb_array_length(r.response -> 'message' -> 'content') > 0
           THEN NULL
           ELSE r.raw_response
       END::bytea AS raw_response,
       r.raw_response_encoding
FROM raw_turns r
LEFT JOIN LATERAL (
    SELECT id, harness_id, harness_session_id, thread_id, parent_harness_session_id
    FROM raw_turn_attribution_corrections
    WHERE org_id = r.org_id AND raw_turn_id = r.id
    ORDER BY id DESC LIMIT 1
) c ON TRUE
WHERE r.id = $1
`

type GetRawTurnRow struct {
	ID                  int64
	OrgID               pgtype.UUID
	Source              string
	Provider            string
	AgentName           string
	HarnessID           string
	HarnessSessionID    string
	RequestID           string
	RawRequest          []byte
	Response            []byte
	Meta                []byte
	SessionEnvelope     []byte
	ReceivedAt          pgtype.Timestamptz
	RawResponse         []byte
	RawResponseEncoding string
}

// The derive read, through the attribution-correction overlay: identity
// columns COALESCE to the latest correction, meta's thread_id is overridden
// when corrected, and the session envelope is rewritten to match.
//
// raw_response is selected ONLY for turns whose reduction is missing its
// content blocks — the shape the deriver skips.
//
// The column runs to the ingest cap, so selecting it unconditionally would pull
// megabytes through every derive read to be discarded. Selecting it never is
// what left a failed reduction unrecoverable: the bytes were stored and no read
// path could reach them. This CASE is the whole difference, and it costs nothing
// on the common path because a healthy reduction returns NULL here.
//
// The test is deliberately coarse — "no content blocks" rather than a faithful
// port of ingest's reducedResponseAbsent. It only decides whether to *fetch*;
// the caller re-checks authoritatively before reducing, so a false positive
// costs one wasted read and a false negative is impossible for the case that
// matters (an empty reduction always lacks content).
func (q *Queries) GetRawTurn(ctx context.Context, id int64) (GetRawTurnRow, error) {
	row := q.db.QueryRow(ctx, getRawTurn, id)
	var i GetRawTurnRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Source,
		&i.Provider,
		&i.AgentName,
		&i.HarnessID,
		&i.HarnessSessionID,
		&i.RequestID,
		&i.RawRequest,
		&i.Response,
		&i.Meta,
		&i.SessionEnvelope,
		&i.ReceivedAt,
		&i.RawResponse,
		&i.RawResponseEncoding,
	)
	return i, err
}

const listRawTurnIndex = `-- name: ListRawTurnIndex :many
SELECT r.id, r.org_id, r.source,
       COALESCE(c.harness_id, r.harness_id) AS harness_id,
       COALESCE(c.harness_session_id, r.harness_session_id) AS harness_session_id,
       r.received_at, r.meta
FROM raw_turns r
LEFT JOIN LATERAL (
    SELECT harness_id, harness_session_id
    FROM raw_turn_attribution_corrections
    WHERE org_id = r.org_id AND raw_turn_id = r.id
    ORDER BY id DESC LIMIT 1
) c ON TRUE
WHERE r.id > $1
ORDER BY r.id
LIMIT $2
`

type ListRawTurnIndexParams struct {
	AfterID  int64
	PageSize int32
}

type ListRawTurnIndexRow struct {
	ID               int64
	OrgID            pgtype.UUID
	Source           string
	HarnessID        string
	HarnessSessionID string
	ReceivedAt       pgtype.Timestamptz
	Meta             []byte
}

// Lightweight scan for the deriver's ordering pass: identity and
// timing only, no payloads. meta rides along because it carries the
// original capture time for backfilled rows.
func (q *Queries) ListRawTurnIndex(ctx context.Context, arg ListRawTurnIndexParams) ([]ListRawTurnIndexRow, error) {
	rows, err := q.db.Query(ctx, listRawTurnIndex, arg.AfterID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRawTurnIndexRow
	for rows.Next() {
		var i ListRawTurnIndexRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Source,
			&i.HarnessID,
			&i.HarnessSessionID,
			&i.ReceivedAt,
			&i.Meta,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsForRederive = `-- name: ListSessionsForRederive :many
SELECT org_id, harness_id, harness_session_id
FROM sessions
ORDER BY org_id, harness_id, harness_session_id
`

type ListSessionsForRederiveRow struct {
	OrgID            pgtype.UUID
	HarnessID        string
	HarnessSessionID string
}

// Whole-store rederive enumerates persisted identities, including sessions
// whose last effective raw turn was repaired away, so their stale projection
// is still covered and pruned.
func (q *Queries) ListSessionsForRederive(ctx context.Context) ([]ListSessionsForRederiveRow, error) {
	rows, err := q.db.Query(ctx, listSessionsForRederive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSessionsForRederiveRow
	for rows.Next() {
		var i ListSessionsForRederiveRow
		if err := rows.Scan(&i.OrgID, &i.HarnessID, &i.HarnessSessionID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sessionIDByHarnessKey = `-- name: SessionIDByHarnessKey :one
SELECT id FROM sessions
WHERE org_id = $1
  AND harness_id = $2
  AND harness_session_id = $3
`

type SessionIDByHarnessKeyParams struct {
	OrgID            pgtype.UUID
	HarnessID        string
	HarnessSessionID string
}

// Resolve the sessions row for one raw turn's natural key. The deriver
// only attributes to existing sessions; it never creates them.
func (q *Queries) SessionIDByHarnessKey(ctx context.Context, arg SessionIDByHarnessKeyParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, sessionIDByHarnessKey, arg.OrgID, arg.HarnessID, arg.HarnessSessionID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
