// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_node.sql

package gensqlc

import (
	"context"
)

const getNode = `-- name: GetNode :one
SELECT hash, bucket, type, role, content, model, provider, agent_name, stop_reason,
       prompt_tokens, completion_tokens, total_tokens,
       cache_creation_input_tokens, cache_read_input_tokens,
       total_duration_ns, prompt_duration_ns, project, created_at, parent_hash,
       session_id, org_id,
       request_system, request_max_tokens, request_temperature, request_stream, request_tool_count
FROM nodes
WHERE hash = $1
`

func (q *Queries) GetNode(ctx context.Context, hash string) (Node, error) {
	row := q.db.QueryRow(ctx, getNode, hash)
	var i Node
	err := row.Scan(
		&i.Hash,
		&i.Bucket,
		&i.Type,
		&i.Role,
		&i.Content,
		&i.Model,
		&i.Provider,
		&i.AgentName,
		&i.StopReason,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.TotalTokens,
		&i.CacheCreationInputTokens,
		&i.CacheReadInputTokens,
		&i.TotalDurationNs,
		&i.PromptDurationNs,
		&i.Project,
		&i.CreatedAt,
		&i.ParentHash,
		&i.SessionID,
		&i.OrgID,
		&i.RequestSystem,
		&i.RequestMaxTokens,
		&i.RequestTemperature,
		&i.RequestStream,
		&i.RequestToolCount,
	)
	return i, err
}
