// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: insert.node.sql

package gensqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertNode = `-- name: InsertNode :execrows
INSERT INTO nodes (
    org_id, hash, bucket, type, role, content, model, provider, agent_name, stop_reason,
    prompt_tokens, completion_tokens, total_tokens,
    cache_creation_input_tokens, cache_read_input_tokens,
    total_duration_ns, prompt_duration_ns, project, created_at, parent_hash,
    request_system, request_max_tokens, request_temperature, request_stream, request_tool_count
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
    $11, $12, $13,
    $14, $15,
    $16, $17, $18, $19, $20,
    $21, $22, $23, $24, $25
)
ON CONFLICT (org_id, hash) DO NOTHING
`

type InsertNodeParams struct {
	OrgID                    pgtype.UUID
	Hash                     string
	Bucket                   []byte
	Type                     pgtype.Text
	Role                     pgtype.Text
	Content                  []byte
	Model                    pgtype.Text
	Provider                 pgtype.Text
	AgentName                pgtype.Text
	StopReason               pgtype.Text
	PromptTokens             pgtype.Int4
	CompletionTokens         pgtype.Int4
	TotalTokens              pgtype.Int4
	CacheCreationInputTokens pgtype.Int4
	CacheReadInputTokens     pgtype.Int4
	TotalDurationNs          pgtype.Int8
	PromptDurationNs         pgtype.Int8
	Project                  pgtype.Text
	CreatedAt                pgtype.Timestamptz
	ParentHash               pgtype.Text
	RequestSystem            pgtype.Text
	RequestMaxTokens         pgtype.Int4
	RequestTemperature       pgtype.Float8
	RequestStream            pgtype.Bool
	RequestToolCount         pgtype.Int4
}

// nodes is keyed by composite PK (org_id, hash) so the same content
// (e.g. a verbatim system prompt) can land for multiple orgs without
// the first writer permanently owning the row. Legacy non-session
// writers pass the nil-UUID (00000000-0000-0000-0000-000000000000)
// per the migration default; session-aware writers (IngestTurn) pass
// the validated cloud-trusted org_id.
func (q *Queries) InsertNode(ctx context.Context, arg InsertNodeParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertNode,
		arg.OrgID,
		arg.Hash,
		arg.Bucket,
		arg.Type,
		arg.Role,
		arg.Content,
		arg.Model,
		arg.Provider,
		arg.AgentName,
		arg.StopReason,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.TotalTokens,
		arg.CacheCreationInputTokens,
		arg.CacheReadInputTokens,
		arg.TotalDurationNs,
		arg.PromptDurationNs,
		arg.Project,
		arg.CreatedAt,
		arg.ParentHash,
		arg.RequestSystem,
		arg.RequestMaxTokens,
		arg.RequestTemperature,
		arg.RequestStream,
		arg.RequestToolCount,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
