// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: list_sessions.sql

package gensqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listSessions = `-- name: ListSessions :many
SELECT n.hash, n.bucket, n.type, n.role, n.content, n.model, n.provider, n.agent_name, n.stop_reason,
       n.prompt_tokens, n.completion_tokens, n.total_tokens,
       n.cache_creation_input_tokens, n.cache_read_input_tokens,
       n.total_duration_ns, n.prompt_duration_ns, n.project, n.created_at, n.parent_hash,
       n.session_id, n.org_id,
       n.request_system, n.request_max_tokens, n.request_temperature, n.request_stream, n.request_tool_count,
       n.node_kind, n.parent_tool_use_id
FROM nodes n
WHERE NOT EXISTS (
    SELECT 1 FROM nodes c WHERE c.parent_hash = n.hash
)
  AND ($1::text IS NULL OR n.project = $1::text)
  AND ($2::text IS NULL OR n.agent_name = $2::text)
  AND ($3::text IS NULL OR n.model = $3::text)
  AND ($4::text IS NULL OR n.provider = $4::text)
  AND ($5::timestamptz IS NULL OR n.created_at >= $5::timestamptz)
  AND ($6::timestamptz IS NULL OR n.created_at < $6::timestamptz)
  AND (
    $7::timestamptz IS NULL
    OR n.created_at < $7::timestamptz
    OR (n.created_at = $7::timestamptz AND n.hash < $8::text)
  )
ORDER BY n.created_at DESC, n.hash DESC
LIMIT $9
`

type ListSessionsParams struct {
	ProjectFilter   pgtype.Text
	AgentFilter     pgtype.Text
	ModelFilter     pgtype.Text
	ProviderFilter  pgtype.Text
	SinceFilter     pgtype.Timestamptz
	UntilFilter     pgtype.Timestamptz
	CursorCreatedAt pgtype.Timestamptz
	CursorHash      pgtype.Text
	LimitCount      int32
}

func (q *Queries) ListSessions(ctx context.Context, arg ListSessionsParams) ([]Node, error) {
	rows, err := q.db.Query(ctx, listSessions,
		arg.ProjectFilter,
		arg.AgentFilter,
		arg.ModelFilter,
		arg.ProviderFilter,
		arg.SinceFilter,
		arg.UntilFilter,
		arg.CursorCreatedAt,
		arg.CursorHash,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Node
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.Hash,
			&i.Bucket,
			&i.Type,
			&i.Role,
			&i.Content,
			&i.Model,
			&i.Provider,
			&i.AgentName,
			&i.StopReason,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.TotalTokens,
			&i.CacheCreationInputTokens,
			&i.CacheReadInputTokens,
			&i.TotalDurationNs,
			&i.PromptDurationNs,
			&i.Project,
			&i.CreatedAt,
			&i.ParentHash,
			&i.SessionID,
			&i.OrgID,
			&i.RequestSystem,
			&i.RequestMaxTokens,
			&i.RequestTemperature,
			&i.RequestStream,
			&i.RequestToolCount,
			&i.NodeKind,
			&i.ParentToolUseID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
