// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package gensqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Node struct {
	Hash                     string
	Bucket                   []byte
	Type                     pgtype.Text
	Role                     pgtype.Text
	Content                  []byte
	Model                    pgtype.Text
	Provider                 pgtype.Text
	AgentName                pgtype.Text
	StopReason               pgtype.Text
	PromptTokens             pgtype.Int4
	CompletionTokens         pgtype.Int4
	TotalTokens              pgtype.Int4
	CacheCreationInputTokens pgtype.Int4
	CacheReadInputTokens     pgtype.Int4
	TotalDurationNs          pgtype.Int8
	PromptDurationNs         pgtype.Int8
	Project                  pgtype.Text
	CreatedAt                pgtype.Timestamptz
	ParentHash               pgtype.Text
	SessionID                pgtype.UUID
	OrgID                    pgtype.UUID
	RequestSystem            pgtype.Text
	RequestMaxTokens         pgtype.Int4
	RequestTemperature       pgtype.Float8
	RequestStream            pgtype.Bool
	RequestToolCount         pgtype.Int4
}

type RawTurn struct {
	ID               int64
	OrgID            pgtype.UUID
	Source           string
	Provider         string
	AgentName        string
	HarnessID        string
	HarnessSessionID string
	RequestID        string
	RawRequest       []byte
	Response         []byte
	Meta             []byte
	SessionEnvelope  []byte
	ReceivedAt       pgtype.Timestamptz
}

type Session struct {
	ID                pgtype.UUID
	OrgID             pgtype.UUID
	AuthSubject       string
	HarnessID         string
	HarnessSessionID  string
	Name              pgtype.Text
	Cwd               pgtype.Text
	HarnessVersion    pgtype.Text
	ParentSessionID   pgtype.UUID
	StartedAt         pgtype.Timestamptz
	LastSeenAt        pgtype.Timestamptz
	EndedAt           pgtype.Timestamptz
	HarnessMetadata   []byte
	TotalInputTokens  int64
	TotalOutputTokens int64
	TotalCostUsd      pgtype.Numeric
	TurnCount         int32
	DerivedStatus     string
	HasGitActivity    bool
	ToolResultCount   int32
	ToolErrorCount    int32
}
