// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package gensqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Node struct {
	Hash                     string
	Bucket                   []byte
	Type                     pgtype.Text
	Role                     pgtype.Text
	Content                  []byte
	Model                    pgtype.Text
	Provider                 pgtype.Text
	AgentName                pgtype.Text
	StopReason               pgtype.Text
	PromptTokens             pgtype.Int4
	CompletionTokens         pgtype.Int4
	TotalTokens              pgtype.Int4
	CacheCreationInputTokens pgtype.Int4
	CacheReadInputTokens     pgtype.Int4
	TotalDurationNs          pgtype.Int8
	PromptDurationNs         pgtype.Int8
	Project                  pgtype.Text
	CreatedAt                pgtype.Timestamptz
	ParentHash               pgtype.Text
}
