// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: raw_turns.sql

package gensqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRawTurns = `-- name: CountRawTurns :one
SELECT COUNT(*) FROM raw_turns
`

func (q *Queries) CountRawTurns(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countRawTurns)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const findRawTurnIDsByPaperProxyRequestID = `-- name: FindRawTurnIDsByPaperProxyRequestID :many
SELECT id
FROM raw_turns
WHERE org_id = $1
  AND session_envelope->'harness_metadata'->>'paperProxyRequestId' = $2::text
ORDER BY id
LIMIT 2
`

type FindRawTurnIDsByPaperProxyRequestIDParams struct {
	OrgID               pgtype.UUID
	PaperProxyRequestID string
}

func (q *Queries) FindRawTurnIDsByPaperProxyRequestID(ctx context.Context, arg FindRawTurnIDsByPaperProxyRequestIDParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, findRawTurnIDsByPaperProxyRequestID, arg.OrgID, arg.PaperProxyRequestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRawTurnAttributionForUpdate = `-- name: GetRawTurnAttributionForUpdate :one
SELECT r.id, r.org_id, r.session_envelope, r.received_at,
       COALESCE(c.harness_id, r.harness_id) AS harness_id,
       COALESCE(c.harness_session_id, r.harness_session_id) AS harness_session_id,
       COALESCE(c.thread_id, r.meta->>'thread_id', '') AS thread_id,
       (c.id IS NOT NULL)::boolean AS has_correction,
       COALESCE(c.parent_harness_session_id, '') AS corrected_parent_harness_session_id,
       COALESCE(r.session_envelope->>'parent_harness_session_id', '')::text AS raw_parent_harness_session_id
FROM raw_turns r
LEFT JOIN LATERAL (
    SELECT id, harness_id, harness_session_id, thread_id, parent_harness_session_id
    FROM raw_turn_attribution_corrections
    WHERE org_id = r.org_id AND raw_turn_id = r.id
    ORDER BY id DESC LIMIT 1
) c ON TRUE
WHERE r.org_id = $1 AND r.id = $2
FOR UPDATE OF r
`

type GetRawTurnAttributionForUpdateParams struct {
	OrgID     pgtype.UUID
	RawTurnID int64
}

type GetRawTurnAttributionForUpdateRow struct {
	ID                              int64
	OrgID                           pgtype.UUID
	SessionEnvelope                 []byte
	ReceivedAt                      pgtype.Timestamptz
	HarnessID                       string
	HarnessSessionID                string
	ThreadID                        string
	HasCorrection                   bool
	CorrectedParentHarnessSessionID string
	RawParentHarnessSessionID       string
}

// Locks the immutable row as a serialization point for competing repairs.
func (q *Queries) GetRawTurnAttributionForUpdate(ctx context.Context, arg GetRawTurnAttributionForUpdateParams) (GetRawTurnAttributionForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getRawTurnAttributionForUpdate, arg.OrgID, arg.RawTurnID)
	var i GetRawTurnAttributionForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.SessionEnvelope,
		&i.ReceivedAt,
		&i.HarnessID,
		&i.HarnessSessionID,
		&i.ThreadID,
		&i.HasCorrection,
		&i.CorrectedParentHarnessSessionID,
		&i.RawParentHarnessSessionID,
	)
	return i, err
}

const insertRawTurn = `-- name: InsertRawTurn :execrows
INSERT INTO raw_turns (
    org_id, source, provider, agent_name,
    harness_id, harness_session_id, request_id,
    raw_request, response, meta, session_envelope,
    raw_response, raw_response_encoding, raw_response_dropped
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9, $10, $11,
    $12, $13, $14
)
ON CONFLICT (org_id, request_id) WHERE request_id <> '' DO NOTHING
`

type InsertRawTurnParams struct {
	OrgID               pgtype.UUID
	Source              string
	Provider            string
	AgentName           string
	HarnessID           string
	HarnessSessionID    string
	RequestID           string
	RawRequest          []byte
	Response            []byte
	Meta                []byte
	SessionEnvelope     []byte
	RawResponse         []byte
	RawResponseEncoding string
	RawResponseDropped  bool
}

// raw_turns is append-only and immutable: INSERT is the only write this
// table ever sees. The ON CONFLICT arm matches the partial unique index
// raw_turns_org_request_uq so a retried POST of the same captured turn
// (same org, same extproc request_id) is a no-op rather than a
// duplicate raw row. Writers without a request_id (”) bypass the
// index and append unconditionally.
func (q *Queries) InsertRawTurn(ctx context.Context, arg InsertRawTurnParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertRawTurn,
		arg.OrgID,
		arg.Source,
		arg.Provider,
		arg.AgentName,
		arg.HarnessID,
		arg.HarnessSessionID,
		arg.RequestID,
		arg.RawRequest,
		arg.Response,
		arg.Meta,
		arg.SessionEnvelope,
		arg.RawResponse,
		arg.RawResponseEncoding,
		arg.RawResponseDropped,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertRawTurnAttributionCorrection = `-- name: InsertRawTurnAttributionCorrection :exec
INSERT INTO raw_turn_attribution_corrections (
    org_id, raw_turn_id, harness_id, harness_session_id, thread_id,
    parent_harness_session_id, reason
) VALUES (
    $1, $2, $3,
    $4, $5,
    $6, $7
)
`

type InsertRawTurnAttributionCorrectionParams struct {
	OrgID                  pgtype.UUID
	RawTurnID              int64
	HarnessID              string
	HarnessSessionID       string
	ThreadID               string
	ParentHarnessSessionID pgtype.Text
	Reason                 string
}

func (q *Queries) InsertRawTurnAttributionCorrection(ctx context.Context, arg InsertRawTurnAttributionCorrectionParams) error {
	_, err := q.db.Exec(ctx, insertRawTurnAttributionCorrection,
		arg.OrgID,
		arg.RawTurnID,
		arg.HarnessID,
		arg.HarnessSessionID,
		arg.ThreadID,
		arg.ParentHarnessSessionID,
		arg.Reason,
	)
	return err
}

const listRawTurnHeadersBySession = `-- name: ListRawTurnHeadersBySession :many
SELECT r.id, r.org_id, r.source, r.provider, r.agent_name, r.request_id,
       r.received_at,
       (CASE WHEN c.id IS NULL THEN r.meta
             ELSE jsonb_set(r.meta, '{thread_id}', to_jsonb(c.thread_id), true)
        END)::jsonb AS meta,
       COALESCE(length(r.raw_request::text), 0)::bigint AS request_bytes,
       COALESCE(length(r.response::text), 0)::bigint AS response_bytes,
       COALESCE(octet_length(r.raw_response), 0)::bigint AS raw_response_bytes,
       r.raw_response_dropped
FROM raw_turns r
LEFT JOIN LATERAL (
    SELECT id, harness_id, harness_session_id, thread_id
    FROM raw_turn_attribution_corrections
    WHERE org_id = r.org_id AND raw_turn_id = r.id
    ORDER BY id DESC LIMIT 1
) c ON TRUE
WHERE r.org_id = $1
  AND COALESCE((
      SELECT c2.harness_id FROM raw_turn_attribution_corrections c2
      WHERE c2.org_id = r.org_id AND c2.raw_turn_id = r.id
      ORDER BY c2.id DESC LIMIT 1
  ), r.harness_id) = $2
  AND COALESCE((
      SELECT c2.harness_session_id FROM raw_turn_attribution_corrections c2
      WHERE c2.org_id = r.org_id AND c2.raw_turn_id = r.id
      ORDER BY c2.id DESC LIMIT 1
  ), r.harness_session_id) = $3
ORDER BY r.id ASC
`

type ListRawTurnHeadersBySessionParams struct {
	OrgID            pgtype.UUID
	HarnessID        string
	HarnessSessionID string
}

type ListRawTurnHeadersBySessionRow struct {
	ID                 int64
	OrgID              pgtype.UUID
	Source             string
	Provider           string
	AgentName          string
	RequestID          string
	ReceivedAt         pgtype.Timestamptz
	Meta               []byte
	RequestBytes       int64
	ResponseBytes      int64
	RawResponseBytes   int64
	RawResponseDropped bool
}

// Operator wire log: identity + sizes, no payloads. The raw layer is
// the capture truth; this surfaces it without shipping the blobs.
func (q *Queries) ListRawTurnHeadersBySession(ctx context.Context, arg ListRawTurnHeadersBySessionParams) ([]ListRawTurnHeadersBySessionRow, error) {
	rows, err := q.db.Query(ctx, listRawTurnHeadersBySession, arg.OrgID, arg.HarnessID, arg.HarnessSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRawTurnHeadersBySessionRow
	for rows.Next() {
		var i ListRawTurnHeadersBySessionRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Source,
			&i.Provider,
			&i.AgentName,
			&i.RequestID,
			&i.ReceivedAt,
			&i.Meta,
			&i.RequestBytes,
			&i.ResponseBytes,
			&i.RawResponseBytes,
			&i.RawResponseDropped,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRawTurns = `-- name: ListRawTurns :many
SELECT r.id, r.org_id, r.source, r.provider, r.agent_name,
       COALESCE(c.harness_id, r.harness_id) AS harness_id,
       COALESCE(c.harness_session_id, r.harness_session_id) AS harness_session_id,
       r.request_id, r.raw_request, r.response,
       (CASE WHEN c.id IS NULL THEN r.meta
             ELSE jsonb_set(r.meta, '{thread_id}', to_jsonb(c.thread_id), true)
        END)::jsonb AS meta,
       (CASE WHEN c.id IS NULL THEN r.session_envelope
             WHEN c.parent_harness_session_id IS NULL THEN
                  (COALESCE(r.session_envelope, '{}'::jsonb) - 'parent_harness_session_id') ||
                  jsonb_build_object(
                      'harness_id', c.harness_id,
                      'harness_session_id', c.harness_session_id
                  )
             ELSE COALESCE(r.session_envelope, '{}'::jsonb) || jsonb_build_object(
                      'harness_id', c.harness_id,
                      'harness_session_id', c.harness_session_id,
                      'parent_harness_session_id', c.parent_harness_session_id
                  )
        END)::jsonb AS session_envelope,
       r.received_at,
       r.raw_response, r.raw_response_encoding, r.raw_response_dropped
FROM raw_turns r
LEFT JOIN LATERAL (
    SELECT id, harness_id, harness_session_id, thread_id, parent_harness_session_id
    FROM raw_turn_attribution_corrections
    WHERE org_id = r.org_id AND raw_turn_id = r.id
    ORDER BY id DESC LIMIT 1
) c ON TRUE
WHERE r.id > $1
ORDER BY r.id
LIMIT $2
`

type ListRawTurnsParams struct {
	AfterID  int64
	PageSize int32
}

type ListRawTurnsRow struct {
	ID                  int64
	OrgID               pgtype.UUID
	Source              string
	Provider            string
	AgentName           string
	HarnessID           string
	HarnessSessionID    string
	RequestID           string
	RawRequest          []byte
	Response            []byte
	Meta                []byte
	SessionEnvelope     []byte
	ReceivedAt          pgtype.Timestamptz
	RawResponse         []byte
	RawResponseEncoding string
	RawResponseDropped  bool
}

// Keyset-paginated scan in insertion order, for the re-runnable deriver.
// Pass after_id = 0 to start from the beginning.
func (q *Queries) ListRawTurns(ctx context.Context, arg ListRawTurnsParams) ([]ListRawTurnsRow, error) {
	rows, err := q.db.Query(ctx, listRawTurns, arg.AfterID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRawTurnsRow
	for rows.Next() {
		var i ListRawTurnsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Source,
			&i.Provider,
			&i.AgentName,
			&i.HarnessID,
			&i.HarnessSessionID,
			&i.RequestID,
			&i.RawRequest,
			&i.Response,
			&i.Meta,
			&i.SessionEnvelope,
			&i.ReceivedAt,
			&i.RawResponse,
			&i.RawResponseEncoding,
			&i.RawResponseDropped,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRawTurnsBySession = `-- name: ListRawTurnsBySession :many
SELECT r.id, r.org_id, r.source, r.provider, r.agent_name,
       COALESCE(c.harness_id, r.harness_id) AS harness_id,
       COALESCE(c.harness_session_id, r.harness_session_id) AS harness_session_id,
       r.request_id, r.raw_request, r.response,
       (CASE WHEN c.id IS NULL THEN r.meta
             ELSE jsonb_set(r.meta, '{thread_id}', to_jsonb(c.thread_id), true)
        END)::jsonb AS meta,
       (CASE WHEN c.id IS NULL THEN r.session_envelope
             WHEN c.parent_harness_session_id IS NULL THEN
                  (COALESCE(r.session_envelope, '{}'::jsonb) - 'parent_harness_session_id') ||
                  jsonb_build_object(
                      'harness_id', c.harness_id,
                      'harness_session_id', c.harness_session_id
                  )
             ELSE COALESCE(r.session_envelope, '{}'::jsonb) || jsonb_build_object(
                      'harness_id', c.harness_id,
                      'harness_session_id', c.harness_session_id,
                      'parent_harness_session_id', c.parent_harness_session_id
                  )
        END)::jsonb AS session_envelope,
       r.received_at,
       r.raw_response, r.raw_response_encoding, r.raw_response_dropped
FROM raw_turns r
LEFT JOIN LATERAL (
    SELECT id, harness_id, harness_session_id, thread_id, parent_harness_session_id
    FROM raw_turn_attribution_corrections
    WHERE org_id = r.org_id AND raw_turn_id = r.id
    ORDER BY id DESC LIMIT 1
) c ON TRUE
WHERE r.org_id = $1
  AND COALESCE((
      SELECT c2.harness_session_id FROM raw_turn_attribution_corrections c2
      WHERE c2.org_id = r.org_id AND c2.raw_turn_id = r.id
      ORDER BY c2.id DESC LIMIT 1
  ), r.harness_session_id) = $2
ORDER BY r.id
`

type ListRawTurnsBySessionParams struct {
	OrgID            pgtype.UUID
	HarnessSessionID string
}

type ListRawTurnsBySessionRow struct {
	ID                  int64
	OrgID               pgtype.UUID
	Source              string
	Provider            string
	AgentName           string
	HarnessID           string
	HarnessSessionID    string
	RequestID           string
	RawRequest          []byte
	Response            []byte
	Meta                []byte
	SessionEnvelope     []byte
	ReceivedAt          pgtype.Timestamptz
	RawResponse         []byte
	RawResponseEncoding string
	RawResponseDropped  bool
}

// Every raw turn captured for one harness session, in insertion order.
func (q *Queries) ListRawTurnsBySession(ctx context.Context, arg ListRawTurnsBySessionParams) ([]ListRawTurnsBySessionRow, error) {
	rows, err := q.db.Query(ctx, listRawTurnsBySession, arg.OrgID, arg.HarnessSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRawTurnsBySessionRow
	for rows.Next() {
		var i ListRawTurnsBySessionRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Source,
			&i.Provider,
			&i.AgentName,
			&i.HarnessID,
			&i.HarnessSessionID,
			&i.RequestID,
			&i.RawRequest,
			&i.Response,
			&i.Meta,
			&i.SessionEnvelope,
			&i.ReceivedAt,
			&i.RawResponse,
			&i.RawResponseEncoding,
			&i.RawResponseDropped,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rawTurnFidelityByIDs = `-- name: RawTurnFidelityByIDs :many
SELECT id,
       COALESCE(octet_length(raw_response) > 0, false)::boolean AS has_raw_response,
       raw_response_dropped
FROM raw_turns
WHERE id = ANY($1::bigint[])
`

type RawTurnFidelityByIDsRow struct {
	ID                 int64
	HasRawResponse     bool
	RawResponseDropped bool
}

// Provenance tier for a set of raw turns, for stamping the span projection.
//
// The projection needs to know whether each row can be re-derived from stored
// bytes, which is a fact about how the turn was captured — not something the
// deriver can know, since it is a pure function of the rows it is handed and
// must not read storage state. Resolving it here keeps that separation while
// still letting the write stamp it.
// COALESCE so the column types as a plain bool rather than a nullable one:
// the predicate cannot actually be NULL, and a three-valued result would push
// an "unknown" case into the caller that has no meaning here.
func (q *Queries) RawTurnFidelityByIDs(ctx context.Context, ids []int64) ([]RawTurnFidelityByIDsRow, error) {
	rows, err := q.db.Query(ctx, rawTurnFidelityByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RawTurnFidelityByIDsRow
	for rows.Next() {
		var i RawTurnFidelityByIDsRow
		if err := rows.Scan(&i.ID, &i.HasRawResponse, &i.RawResponseDropped); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
