// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reflections.sql

package gensqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSessionReflection = `-- name: GetSessionReflection :one
SELECT org_id, session_id, narrative, observation, turn_count, model, generated_at FROM session_reflections
WHERE org_id = $1 AND session_id = $2
`

type GetSessionReflectionParams struct {
	OrgID     pgtype.UUID
	SessionID pgtype.UUID
}

// Org-scoped point read used by GET /v1/sessions/:id/reflection and the generate
// handler's cache check (a reflection whose turn_count matches the session is
// returned without an LLM call).
func (q *Queries) GetSessionReflection(ctx context.Context, arg GetSessionReflectionParams) (SessionReflection, error) {
	row := q.db.QueryRow(ctx, getSessionReflection, arg.OrgID, arg.SessionID)
	var i SessionReflection
	err := row.Scan(
		&i.OrgID,
		&i.SessionID,
		&i.Narrative,
		&i.Observation,
		&i.TurnCount,
		&i.Model,
		&i.GeneratedAt,
	)
	return i, err
}

const upsertSessionReflection = `-- name: UpsertSessionReflection :one
INSERT INTO session_reflections (
    org_id,
    session_id,
    narrative,
    observation,
    turn_count,
    model,
    generated_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
ON CONFLICT (org_id, session_id) DO UPDATE
SET narrative    = EXCLUDED.narrative,
    observation  = EXCLUDED.observation,
    turn_count   = EXCLUDED.turn_count,
    model        = EXCLUDED.model,
    generated_at = EXCLUDED.generated_at
RETURNING org_id, session_id, narrative, observation, turn_count, model, generated_at
`

type UpsertSessionReflectionParams struct {
	OrgID       pgtype.UUID
	SessionID   pgtype.UUID
	Narrative   string
	Observation string
	TurnCount   int32
	Model       string
	GeneratedAt pgtype.Timestamptz
}

// Insert-or-replace a session's reflection keyed by (org_id, session_id) — one
// reflection per session, regeneration overwrites (latest wins). Every field but
// the key is replaced on conflict: a regenerated reflection supersedes the prior
// narrative/observation wholesale, and turn_count/generated_at move with it.
func (q *Queries) UpsertSessionReflection(ctx context.Context, arg UpsertSessionReflectionParams) (SessionReflection, error) {
	row := q.db.QueryRow(ctx, upsertSessionReflection,
		arg.OrgID,
		arg.SessionID,
		arg.Narrative,
		arg.Observation,
		arg.TurnCount,
		arg.Model,
		arg.GeneratedAt,
	)
	var i SessionReflection
	err := row.Scan(
		&i.OrgID,
		&i.SessionID,
		&i.Narrative,
		&i.Observation,
		&i.TurnCount,
		&i.Model,
		&i.GeneratedAt,
	)
	return i, err
}
