// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: skills.sql

package gensqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSkills = `-- name: CountSkills :one
SELECT
    COUNT(*)::bigint AS total,
    COUNT(*) FILTER (WHERE author_subject = $1)::bigint AS mine
FROM skills
WHERE org_id = $2
  AND (
    $3::text IS NULL
    OR name ILIKE '%' || $3::text || '%'
    OR description ILIKE '%' || $3::text || '%'
    OR EXISTS (SELECT 1 FROM unnest(tags) tag WHERE tag ILIKE '%' || $3::text || '%')
  )
`

type CountSkillsParams struct {
	Author string
	OrgID  pgtype.UUID
	Query  pgtype.Text
}

type CountSkillsRow struct {
	Total int64
	Mine  int64
}

// Tab counts for the current search: total matching, and how many are authored
// by the caller. "team" is derived client-side as total - mine. Counts ignore
// scope and cursor so every tab shows its full size for the active query.
func (q *Queries) CountSkills(ctx context.Context, arg CountSkillsParams) (CountSkillsRow, error) {
	row := q.db.QueryRow(ctx, countSkills, arg.Author, arg.OrgID, arg.Query)
	var i CountSkillsRow
	err := row.Scan(&i.Total, &i.Mine)
	return i, err
}

const createSkillVersion = `-- name: CreateSkillVersion :one
INSERT INTO skill_versions (
    org_id,
    skill_id,
    version_number,
    semver,
    changelog,
    content,
    author_subject,
    published_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING org_id, version_number, semver, changelog, content, author_subject, published_at, skill_id
`

type CreateSkillVersionParams struct {
	OrgID         pgtype.UUID
	SkillID       pgtype.UUID
	VersionNumber int32
	Semver        string
	Changelog     string
	Content       string
	AuthorSubject string
	PublishedAt   pgtype.Timestamptz
}

// Append an immutable published snapshot of a skill's content.
func (q *Queries) CreateSkillVersion(ctx context.Context, arg CreateSkillVersionParams) (SkillVersion, error) {
	row := q.db.QueryRow(ctx, createSkillVersion,
		arg.OrgID,
		arg.SkillID,
		arg.VersionNumber,
		arg.Semver,
		arg.Changelog,
		arg.Content,
		arg.AuthorSubject,
		arg.PublishedAt,
	)
	var i SkillVersion
	err := row.Scan(
		&i.OrgID,
		&i.VersionNumber,
		&i.Semver,
		&i.Changelog,
		&i.Content,
		&i.AuthorSubject,
		&i.PublishedAt,
		&i.SkillID,
	)
	return i, err
}

const deleteSkill = `-- name: DeleteSkill :execrows
DELETE FROM skills
WHERE org_id = $1 AND id = $2
`

type DeleteSkillParams struct {
	OrgID pgtype.UUID
	ID    pgtype.UUID
}

// Remove a skill by its org-scoped id. Returns the affected row count so the
// handler can distinguish a real delete from a missing id.
func (q *Queries) DeleteSkill(ctx context.Context, arg DeleteSkillParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSkill, arg.OrgID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSkillVersions = `-- name: DeleteSkillVersions :exec
DELETE FROM skill_versions
WHERE org_id = $1 AND skill_id = $2
`

type DeleteSkillVersionsParams struct {
	OrgID   pgtype.UUID
	SkillID pgtype.UUID
}

// Remove a skill's published history. skill_versions has no FK cascade to
// skills, so deleting a skill must drop its versions explicitly.
func (q *Queries) DeleteSkillVersions(ctx context.Context, arg DeleteSkillVersionsParams) error {
	_, err := q.db.Exec(ctx, deleteSkillVersions, arg.OrgID, arg.SkillID)
	return err
}

const getSkillByID = `-- name: GetSkillByID :one
SELECT org_id, slug, name, description, type, version, visibility, tags, content, is_ai_generated, generated_from_session_ids, created_at, updated_at, author_subject, download_count, id, parent_id FROM skills
WHERE org_id = $1 AND id = $2
`

type GetSkillByIDParams struct {
	OrgID pgtype.UUID
	ID    pgtype.UUID
}

// Org-scoped point read used by GET /v1/skills/:id and the write handlers.
func (q *Queries) GetSkillByID(ctx context.Context, arg GetSkillByIDParams) (Skill, error) {
	row := q.db.QueryRow(ctx, getSkillByID, arg.OrgID, arg.ID)
	var i Skill
	err := row.Scan(
		&i.OrgID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.Version,
		&i.Visibility,
		&i.Tags,
		&i.Content,
		&i.IsAiGenerated,
		&i.GeneratedFromSessionIds,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthorSubject,
		&i.DownloadCount,
		&i.ID,
		&i.ParentID,
	)
	return i, err
}

const incrementSkillDownloads = `-- name: IncrementSkillDownloads :exec
UPDATE skills SET download_count = download_count + 1
WHERE org_id = $1 AND id = $2
`

type IncrementSkillDownloadsParams struct {
	OrgID pgtype.UUID
	ID    pgtype.UUID
}

// Bump the real download counter when a skill's SKILL.md is downloaded.
func (q *Queries) IncrementSkillDownloads(ctx context.Context, arg IncrementSkillDownloadsParams) error {
	_, err := q.db.Exec(ctx, incrementSkillDownloads, arg.OrgID, arg.ID)
	return err
}

const listSessionSkills = `-- name: ListSessionSkills :many
SELECT org_id, slug, name, description, type, version, visibility, tags, content, is_ai_generated, generated_from_session_ids, created_at, updated_at, author_subject, download_count, id, parent_id FROM skills
WHERE org_id = $1
  AND $2::text = ANY(generated_from_session_ids)
ORDER BY updated_at DESC, id DESC
`

type ListSessionSkillsParams struct {
	OrgID     pgtype.UUID
	SessionID string
}

// Skills generated from a given session (reverse lookup over the provenance
// array), newest-edited first. Small result set, so no pagination.
func (q *Queries) ListSessionSkills(ctx context.Context, arg ListSessionSkillsParams) ([]Skill, error) {
	rows, err := q.db.Query(ctx, listSessionSkills, arg.OrgID, arg.SessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Skill
	for rows.Next() {
		var i Skill
		if err := rows.Scan(
			&i.OrgID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.Type,
			&i.Version,
			&i.Visibility,
			&i.Tags,
			&i.Content,
			&i.IsAiGenerated,
			&i.GeneratedFromSessionIds,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorSubject,
			&i.DownloadCount,
			&i.ID,
			&i.ParentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSkillVersions = `-- name: ListSkillVersions :many
SELECT org_id, version_number, semver, changelog, content, author_subject, published_at, skill_id FROM skill_versions
WHERE org_id = $1 AND skill_id = $2
ORDER BY version_number DESC
`

type ListSkillVersionsParams struct {
	OrgID   pgtype.UUID
	SkillID pgtype.UUID
}

func (q *Queries) ListSkillVersions(ctx context.Context, arg ListSkillVersionsParams) ([]SkillVersion, error) {
	rows, err := q.db.Query(ctx, listSkillVersions, arg.OrgID, arg.SkillID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SkillVersion
	for rows.Next() {
		var i SkillVersion
		if err := rows.Scan(
			&i.OrgID,
			&i.VersionNumber,
			&i.Semver,
			&i.Changelog,
			&i.Content,
			&i.AuthorSubject,
			&i.PublishedAt,
			&i.SkillID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSkillsPage = `-- name: ListSkillsPage :many
SELECT org_id, slug, name, description, type, version, visibility, tags, content, is_ai_generated, generated_from_session_ids, created_at, updated_at, author_subject, download_count, id, parent_id FROM skills
WHERE org_id = $1
  AND (
    $2::text IS NULL
    OR name ILIKE '%' || $2::text || '%'
    OR description ILIKE '%' || $2::text || '%'
    OR EXISTS (SELECT 1 FROM unnest(tags) tag WHERE tag ILIKE '%' || $2::text || '%')
  )
  AND ($3::text IS NULL OR author_subject = $3::text)
  AND ($4::text IS NULL OR author_subject <> $4::text)
  AND (
    $5::timestamptz IS NULL
    OR updated_at < $5::timestamptz
    OR (updated_at = $5::timestamptz AND id < $6::uuid)
  )
ORDER BY updated_at DESC, id DESC
LIMIT $7
`

type ListSkillsPageParams struct {
	OrgID     pgtype.UUID
	Query     pgtype.Text
	Author    pgtype.Text
	NotAuthor pgtype.Text
	CursorTs  pgtype.Timestamptz
	CursorID  pgtype.UUID
	Lim       int32
}

// One keyset page of skills for an org, newest-edited first, with optional
// full-text search (name/description/tags) and author scope. The cursor is the
// (updated_at, id) of the last row on the previous page; the tiebreak on id
// keeps pagination stable when updated_at ties. Fetch lim+1 to detect has_more.
func (q *Queries) ListSkillsPage(ctx context.Context, arg ListSkillsPageParams) ([]Skill, error) {
	rows, err := q.db.Query(ctx, listSkillsPage,
		arg.OrgID,
		arg.Query,
		arg.Author,
		arg.NotAuthor,
		arg.CursorTs,
		arg.CursorID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Skill
	for rows.Next() {
		var i Skill
		if err := rows.Scan(
			&i.OrgID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.Type,
			&i.Version,
			&i.Visibility,
			&i.Tags,
			&i.Content,
			&i.IsAiGenerated,
			&i.GeneratedFromSessionIds,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorSubject,
			&i.DownloadCount,
			&i.ID,
			&i.ParentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSkillsPageByDownloads = `-- name: ListSkillsPageByDownloads :many
SELECT org_id, slug, name, description, type, version, visibility, tags, content, is_ai_generated, generated_from_session_ids, created_at, updated_at, author_subject, download_count, id, parent_id FROM skills
WHERE org_id = $1
  AND (
    $2::text IS NULL
    OR name ILIKE '%' || $2::text || '%'
    OR description ILIKE '%' || $2::text || '%'
    OR EXISTS (SELECT 1 FROM unnest(tags) tag WHERE tag ILIKE '%' || $2::text || '%')
  )
  AND ($3::text IS NULL OR author_subject = $3::text)
  AND ($4::text IS NULL OR author_subject <> $4::text)
  AND (
    $5::bigint IS NULL
    OR download_count < $5::bigint
    OR (download_count = $5::bigint AND id < $6::uuid)
  )
ORDER BY download_count DESC, id DESC
LIMIT $7
`

type ListSkillsPageByDownloadsParams struct {
	OrgID           pgtype.UUID
	Query           pgtype.Text
	Author          pgtype.Text
	NotAuthor       pgtype.Text
	CursorDownloads pgtype.Int8
	CursorID        pgtype.UUID
	Lim             int32
}

// Same as ListSkillsPage but ordered by most-downloaded. The keyset is
// (download_count, id); the cursor carries the last row's download_count and id.
func (q *Queries) ListSkillsPageByDownloads(ctx context.Context, arg ListSkillsPageByDownloadsParams) ([]Skill, error) {
	rows, err := q.db.Query(ctx, listSkillsPageByDownloads,
		arg.OrgID,
		arg.Query,
		arg.Author,
		arg.NotAuthor,
		arg.CursorDownloads,
		arg.CursorID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Skill
	for rows.Next() {
		var i Skill
		if err := rows.Scan(
			&i.OrgID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.Type,
			&i.Version,
			&i.Visibility,
			&i.Tags,
			&i.Content,
			&i.IsAiGenerated,
			&i.GeneratedFromSessionIds,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorSubject,
			&i.DownloadCount,
			&i.ID,
			&i.ParentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxSkillVersionNumber = `-- name: MaxSkillVersionNumber :one
SELECT COALESCE(MAX(version_number), 0)::int AS max_version
FROM skill_versions
WHERE org_id = $1 AND skill_id = $2
`

type MaxSkillVersionNumberParams struct {
	OrgID   pgtype.UUID
	SkillID pgtype.UUID
}

// Highest version_number for a skill (0 when none published yet).
func (q *Queries) MaxSkillVersionNumber(ctx context.Context, arg MaxSkillVersionNumberParams) (int32, error) {
	row := q.db.QueryRow(ctx, maxSkillVersionNumber, arg.OrgID, arg.SkillID)
	var max_version int32
	err := row.Scan(&max_version)
	return max_version, err
}

const setSkillVersion = `-- name: SetSkillVersion :exec
UPDATE skills
   SET version = $1, updated_at = $2
 WHERE org_id = $3 AND id = $4
`

type SetSkillVersionParams struct {
	Version   string
	UpdatedAt pgtype.Timestamptz
	OrgID     pgtype.UUID
	ID        pgtype.UUID
}

// Bump the skill's current published semver (and updated_at) at publish time.
func (q *Queries) SetSkillVersion(ctx context.Context, arg SetSkillVersionParams) error {
	_, err := q.db.Exec(ctx, setSkillVersion,
		arg.Version,
		arg.UpdatedAt,
		arg.OrgID,
		arg.ID,
	)
	return err
}

const upsertSkill = `-- name: UpsertSkill :one
INSERT INTO skills (
    org_id,
    id,
    slug,
    name,
    description,
    type,
    version,
    visibility,
    tags,
    content,
    is_ai_generated,
    generated_from_session_ids,
    parent_id,
    author_subject,
    created_at,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16
)
ON CONFLICT (org_id, id) DO UPDATE
SET slug                       = EXCLUDED.slug,
    name                       = EXCLUDED.name,
    description                = EXCLUDED.description,
    type                       = EXCLUDED.type,
    version                    = EXCLUDED.version,
    visibility                 = EXCLUDED.visibility,
    tags                       = EXCLUDED.tags,
    content                    = EXCLUDED.content,
    is_ai_generated            = EXCLUDED.is_ai_generated,
    generated_from_session_ids = EXCLUDED.generated_from_session_ids,
    parent_id                  = EXCLUDED.parent_id,
    updated_at                 = EXCLUDED.updated_at
RETURNING org_id, slug, name, description, type, version, visibility, tags, content, is_ai_generated, generated_from_session_ids, created_at, updated_at, author_subject, download_count, id, parent_id
`

type UpsertSkillParams struct {
	OrgID                   pgtype.UUID
	ID                      pgtype.UUID
	Slug                    string
	Name                    string
	Description             string
	Type                    string
	Version                 string
	Visibility              string
	Tags                    []string
	Content                 string
	IsAiGenerated           bool
	GeneratedFromSessionIds []string
	ParentID                pgtype.UUID
	AuthorSubject           string
	CreatedAt               pgtype.Timestamptz
	UpdatedAt               pgtype.Timestamptz
}

// Insert-or-replace a skill keyed by (org_id, id). Create/generate/duplicate
// mint a fresh id (a plain insert); PUT and publish pass the existing id (an
// update). slug is a cosmetic, non-unique display label, so it is overwritten
// on update like any other mutable field. created_at and author_subject are
// preserved on conflict (original creation time and creator stay authoritative).
func (q *Queries) UpsertSkill(ctx context.Context, arg UpsertSkillParams) (Skill, error) {
	row := q.db.QueryRow(ctx, upsertSkill,
		arg.OrgID,
		arg.ID,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.Type,
		arg.Version,
		arg.Visibility,
		arg.Tags,
		arg.Content,
		arg.IsAiGenerated,
		arg.GeneratedFromSessionIds,
		arg.ParentID,
		arg.AuthorSubject,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Skill
	err := row.Scan(
		&i.OrgID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.Version,
		&i.Visibility,
		&i.Tags,
		&i.Content,
		&i.IsAiGenerated,
		&i.GeneratedFromSessionIds,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthorSubject,
		&i.DownloadCount,
		&i.ID,
		&i.ParentID,
	)
	return i, err
}
