// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: spans.sql

package gensqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSpan = `-- name: GetSpan :one
SELECT org_id, trace_id, span_id, parent_span_id, session_id, kind, name, status, call_kind, thread_id, model, stop_reason, started_at, duration_ns, input, output, usage, raw_turn_id, node_hash FROM spans
WHERE org_id = $1 AND trace_id = $2 AND span_id = $3
`

type GetSpanParams struct {
	OrgID   pgtype.UUID
	TraceID string
	SpanID  string
}

func (q *Queries) GetSpan(ctx context.Context, arg GetSpanParams) (Span, error) {
	row := q.db.QueryRow(ctx, getSpan, arg.OrgID, arg.TraceID, arg.SpanID)
	var i Span
	err := row.Scan(
		&i.OrgID,
		&i.TraceID,
		&i.SpanID,
		&i.ParentSpanID,
		&i.SessionID,
		&i.Kind,
		&i.Name,
		&i.Status,
		&i.CallKind,
		&i.ThreadID,
		&i.Model,
		&i.StopReason,
		&i.StartedAt,
		&i.DurationNs,
		&i.Input,
		&i.Output,
		&i.Usage,
		&i.RawTurnID,
		&i.NodeHash,
	)
	return i, err
}

const getSpanTurn = `-- name: GetSpanTurn :one
SELECT org_id, trace_id, session_id, user_prompt, synthetic, status, started_at, ended_at, duration_ns, total_input_tokens, total_output_tokens, total_cost_usd, main_input_tokens, main_output_tokens, cache_read_tokens, cache_creation_tokens FROM span_turns
WHERE org_id = $1 AND trace_id = $2
`

type GetSpanTurnParams struct {
	OrgID   pgtype.UUID
	TraceID string
}

func (q *Queries) GetSpanTurn(ctx context.Context, arg GetSpanTurnParams) (SpanTurn, error) {
	row := q.db.QueryRow(ctx, getSpanTurn, arg.OrgID, arg.TraceID)
	var i SpanTurn
	err := row.Scan(
		&i.OrgID,
		&i.TraceID,
		&i.SessionID,
		&i.UserPrompt,
		&i.Synthetic,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
		&i.DurationNs,
		&i.TotalInputTokens,
		&i.TotalOutputTokens,
		&i.TotalCostUsd,
		&i.MainInputTokens,
		&i.MainOutputTokens,
		&i.CacheReadTokens,
		&i.CacheCreationTokens,
	)
	return i, err
}

const listSpanLinksBySession = `-- name: ListSpanLinksBySession :many
SELECT org_id, from_trace_id, from_span_id, from_io, to_trace_id, to_span_id, to_io, kind, session_id FROM span_links
WHERE session_id = $1
`

func (q *Queries) ListSpanLinksBySession(ctx context.Context, sessionID pgtype.UUID) ([]SpanLink, error) {
	rows, err := q.db.Query(ctx, listSpanLinksBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SpanLink
	for rows.Next() {
		var i SpanLink
		if err := rows.Scan(
			&i.OrgID,
			&i.FromTraceID,
			&i.FromSpanID,
			&i.FromIo,
			&i.ToTraceID,
			&i.ToSpanID,
			&i.ToIo,
			&i.Kind,
			&i.SessionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpanLinksByTrace = `-- name: ListSpanLinksByTrace :many
SELECT org_id, from_trace_id, from_span_id, from_io, to_trace_id, to_span_id, to_io, kind, session_id FROM span_links
WHERE org_id = $1 AND (from_trace_id = $2 OR to_trace_id = $2)
`

type ListSpanLinksByTraceParams struct {
	OrgID       pgtype.UUID
	FromTraceID string
}

func (q *Queries) ListSpanLinksByTrace(ctx context.Context, arg ListSpanLinksByTraceParams) ([]SpanLink, error) {
	rows, err := q.db.Query(ctx, listSpanLinksByTrace, arg.OrgID, arg.FromTraceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SpanLink
	for rows.Next() {
		var i SpanLink
		if err := rows.Scan(
			&i.OrgID,
			&i.FromTraceID,
			&i.FromSpanID,
			&i.FromIo,
			&i.ToTraceID,
			&i.ToSpanID,
			&i.ToIo,
			&i.Kind,
			&i.SessionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpanTurns = `-- name: ListSpanTurns :many
SELECT org_id, trace_id, session_id, user_prompt, synthetic, status, started_at, ended_at, duration_ns, total_input_tokens, total_output_tokens, total_cost_usd, main_input_tokens, main_output_tokens, cache_read_tokens, cache_creation_tokens FROM span_turns
WHERE org_id = $1
  AND ($3::timestamptz IS NULL
       OR (started_at, trace_id) < ($3::timestamptz, $4::text))
ORDER BY started_at DESC, trace_id DESC
LIMIT $2
`

type ListSpanTurnsParams struct {
	OrgID           pgtype.UUID
	Limit           int32
	CursorStartedAt pgtype.Timestamptz
	CursorTraceID   pgtype.Text
}

func (q *Queries) ListSpanTurns(ctx context.Context, arg ListSpanTurnsParams) ([]SpanTurn, error) {
	rows, err := q.db.Query(ctx, listSpanTurns,
		arg.OrgID,
		arg.Limit,
		arg.CursorStartedAt,
		arg.CursorTraceID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SpanTurn
	for rows.Next() {
		var i SpanTurn
		if err := rows.Scan(
			&i.OrgID,
			&i.TraceID,
			&i.SessionID,
			&i.UserPrompt,
			&i.Synthetic,
			&i.Status,
			&i.StartedAt,
			&i.EndedAt,
			&i.DurationNs,
			&i.TotalInputTokens,
			&i.TotalOutputTokens,
			&i.TotalCostUsd,
			&i.MainInputTokens,
			&i.MainOutputTokens,
			&i.CacheReadTokens,
			&i.CacheCreationTokens,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpanTurnsBySession = `-- name: ListSpanTurnsBySession :many

SELECT org_id, trace_id, session_id, user_prompt, synthetic, status, started_at, ended_at, duration_ns, total_input_tokens, total_output_tokens, total_cost_usd, main_input_tokens, main_output_tokens, cache_read_tokens, cache_creation_tokens FROM span_turns
WHERE session_id = $1
ORDER BY started_at ASC, trace_id ASC
`

// Span model reads.
func (q *Queries) ListSpanTurnsBySession(ctx context.Context, sessionID pgtype.UUID) ([]SpanTurn, error) {
	rows, err := q.db.Query(ctx, listSpanTurnsBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SpanTurn
	for rows.Next() {
		var i SpanTurn
		if err := rows.Scan(
			&i.OrgID,
			&i.TraceID,
			&i.SessionID,
			&i.UserPrompt,
			&i.Synthetic,
			&i.Status,
			&i.StartedAt,
			&i.EndedAt,
			&i.DurationNs,
			&i.TotalInputTokens,
			&i.TotalOutputTokens,
			&i.TotalCostUsd,
			&i.MainInputTokens,
			&i.MainOutputTokens,
			&i.CacheReadTokens,
			&i.CacheCreationTokens,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpansBySession = `-- name: ListSpansBySession :many
SELECT org_id, trace_id, span_id, parent_span_id, session_id, kind, name, status, call_kind, thread_id, model, stop_reason, started_at, duration_ns, input, output, usage, raw_turn_id, node_hash FROM spans
WHERE session_id = $1
ORDER BY trace_id ASC, started_at ASC, span_id ASC
`

func (q *Queries) ListSpansBySession(ctx context.Context, sessionID pgtype.UUID) ([]Span, error) {
	rows, err := q.db.Query(ctx, listSpansBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Span
	for rows.Next() {
		var i Span
		if err := rows.Scan(
			&i.OrgID,
			&i.TraceID,
			&i.SpanID,
			&i.ParentSpanID,
			&i.SessionID,
			&i.Kind,
			&i.Name,
			&i.Status,
			&i.CallKind,
			&i.ThreadID,
			&i.Model,
			&i.StopReason,
			&i.StartedAt,
			&i.DurationNs,
			&i.Input,
			&i.Output,
			&i.Usage,
			&i.RawTurnID,
			&i.NodeHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpansByTrace = `-- name: ListSpansByTrace :many
SELECT org_id, trace_id, span_id, parent_span_id, session_id, kind, name, status, call_kind, thread_id, model, stop_reason, started_at, duration_ns, input, output, usage, raw_turn_id, node_hash FROM spans
WHERE org_id = $1 AND trace_id = $2
ORDER BY started_at ASC, span_id ASC
`

type ListSpansByTraceParams struct {
	OrgID   pgtype.UUID
	TraceID string
}

func (q *Queries) ListSpansByTrace(ctx context.Context, arg ListSpansByTraceParams) ([]Span, error) {
	rows, err := q.db.Query(ctx, listSpansByTrace, arg.OrgID, arg.TraceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Span
	for rows.Next() {
		var i Span
		if err := rows.Scan(
			&i.OrgID,
			&i.TraceID,
			&i.SpanID,
			&i.ParentSpanID,
			&i.SessionID,
			&i.Kind,
			&i.Name,
			&i.Status,
			&i.CallKind,
			&i.ThreadID,
			&i.Model,
			&i.StopReason,
			&i.StartedAt,
			&i.DurationNs,
			&i.Input,
			&i.Output,
			&i.Usage,
			&i.RawTurnID,
			&i.NodeHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTraceSummariesBySession = `-- name: ListTraceSummariesBySession :many
SELECT t.org_id, t.trace_id, t.session_id, t.user_prompt, t.synthetic,
       t.status, t.started_at, t.ended_at, t.duration_ns,
       t.total_input_tokens, t.total_output_tokens,
       t.main_input_tokens, t.main_output_tokens,
       t.cache_read_tokens, t.cache_creation_tokens, t.total_cost_usd,
       count(s.span_id) AS span_count
FROM span_turns t
LEFT JOIN spans s ON s.org_id = t.org_id AND s.trace_id = t.trace_id
WHERE t.session_id = $1
GROUP BY t.org_id, t.trace_id
ORDER BY t.started_at ASC, t.trace_id ASC
`

type ListTraceSummariesBySessionRow struct {
	OrgID               pgtype.UUID
	TraceID             string
	SessionID           pgtype.UUID
	UserPrompt          string
	Synthetic           string
	Status              string
	StartedAt           pgtype.Timestamptz
	EndedAt             pgtype.Timestamptz
	DurationNs          int64
	TotalInputTokens    int64
	TotalOutputTokens   int64
	MainInputTokens     int64
	MainOutputTokens    int64
	CacheReadTokens     int64
	CacheCreationTokens int64
	TotalCostUsd        pgtype.Numeric
	SpanCount           int64
}

// Session detail's lazy view: turn headers only, no span payloads.
func (q *Queries) ListTraceSummariesBySession(ctx context.Context, sessionID pgtype.UUID) ([]ListTraceSummariesBySessionRow, error) {
	rows, err := q.db.Query(ctx, listTraceSummariesBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTraceSummariesBySessionRow
	for rows.Next() {
		var i ListTraceSummariesBySessionRow
		if err := rows.Scan(
			&i.OrgID,
			&i.TraceID,
			&i.SessionID,
			&i.UserPrompt,
			&i.Synthetic,
			&i.Status,
			&i.StartedAt,
			&i.EndedAt,
			&i.DurationNs,
			&i.TotalInputTokens,
			&i.TotalOutputTokens,
			&i.MainInputTokens,
			&i.MainOutputTokens,
			&i.CacheReadTokens,
			&i.CacheCreationTokens,
			&i.TotalCostUsd,
			&i.SpanCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneSpanLinks = `-- name: PruneSpanLinks :execrows
DELETE FROM span_links
WHERE org_id = $1
  AND session_id = ANY($2::uuid[])
  AND NOT (from_trace_id || '|' || from_span_id || '|' || to_trace_id || '|' || to_span_id || '|' || from_io || '|' || to_io
           = ANY($3::text[]))
`

type PruneSpanLinksParams struct {
	OrgID      pgtype.UUID
	SessionIds []pgtype.UUID
	KeepKeys   []string
}

func (q *Queries) PruneSpanLinks(ctx context.Context, arg PruneSpanLinksParams) (int64, error) {
	result, err := q.db.Exec(ctx, pruneSpanLinks, arg.OrgID, arg.SessionIds, arg.KeepKeys)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const pruneSpanTurns = `-- name: PruneSpanTurns :execrows
DELETE FROM span_turns
WHERE org_id = $1
  AND session_id = ANY($2::uuid[])
  AND NOT (trace_id = ANY($3::text[]))
`

type PruneSpanTurnsParams struct {
	OrgID        pgtype.UUID
	SessionIds   []pgtype.UUID
	KeepTraceIds []string
}

// Deterministic ids make prune a no-op on unchanged raw; rows fall out
// only when the projection stops producing their key.
func (q *Queries) PruneSpanTurns(ctx context.Context, arg PruneSpanTurnsParams) (int64, error) {
	result, err := q.db.Exec(ctx, pruneSpanTurns, arg.OrgID, arg.SessionIds, arg.KeepTraceIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const pruneSpans = `-- name: PruneSpans :execrows
DELETE FROM spans
WHERE org_id = $1
  AND session_id = ANY($2::uuid[])
  AND NOT (trace_id || '|' || span_id = ANY($3::text[]))
`

type PruneSpansParams struct {
	OrgID      pgtype.UUID
	SessionIds []pgtype.UUID
	KeepKeys   []string
}

func (q *Queries) PruneSpans(ctx context.Context, arg PruneSpansParams) (int64, error) {
	result, err := q.db.Exec(ctx, pruneSpans, arg.OrgID, arg.SessionIds, arg.KeepKeys)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertSpan = `-- name: UpsertSpan :exec
INSERT INTO spans (
    org_id, trace_id, span_id, parent_span_id, session_id,
    kind, name, status, call_kind, thread_id, model, stop_reason,
    started_at, duration_ns, input, output, usage, raw_turn_id, node_hash
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10, $11, $12,
    $13, $14, $15, $16, $17, $18, $19
)
ON CONFLICT (org_id, trace_id, span_id) DO UPDATE SET
    parent_span_id = EXCLUDED.parent_span_id,
    session_id     = COALESCE(spans.session_id, EXCLUDED.session_id),
    kind           = EXCLUDED.kind,
    name           = EXCLUDED.name,
    status         = EXCLUDED.status,
    call_kind      = EXCLUDED.call_kind,
    thread_id      = EXCLUDED.thread_id,
    model          = EXCLUDED.model,
    stop_reason    = EXCLUDED.stop_reason,
    started_at     = EXCLUDED.started_at,
    duration_ns    = EXCLUDED.duration_ns,
    input          = EXCLUDED.input,
    output         = EXCLUDED.output,
    usage          = EXCLUDED.usage,
    raw_turn_id    = EXCLUDED.raw_turn_id,
    node_hash      = EXCLUDED.node_hash
`

type UpsertSpanParams struct {
	OrgID        pgtype.UUID
	TraceID      string
	SpanID       string
	ParentSpanID string
	SessionID    pgtype.UUID
	Kind         string
	Name         string
	Status       string
	CallKind     string
	ThreadID     string
	Model        string
	StopReason   string
	StartedAt    pgtype.Timestamptz
	DurationNs   int64
	Input        []byte
	Output       []byte
	Usage        []byte
	RawTurnID    pgtype.Int8
	NodeHash     string
}

func (q *Queries) UpsertSpan(ctx context.Context, arg UpsertSpanParams) error {
	_, err := q.db.Exec(ctx, upsertSpan,
		arg.OrgID,
		arg.TraceID,
		arg.SpanID,
		arg.ParentSpanID,
		arg.SessionID,
		arg.Kind,
		arg.Name,
		arg.Status,
		arg.CallKind,
		arg.ThreadID,
		arg.Model,
		arg.StopReason,
		arg.StartedAt,
		arg.DurationNs,
		arg.Input,
		arg.Output,
		arg.Usage,
		arg.RawTurnID,
		arg.NodeHash,
	)
	return err
}

const upsertSpanLink = `-- name: UpsertSpanLink :exec
INSERT INTO span_links (
    org_id, from_trace_id, from_span_id, from_io,
    to_trace_id, to_span_id, to_io, kind, session_id
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8, $9
)
ON CONFLICT (org_id, from_trace_id, from_span_id, to_trace_id, to_span_id, from_io, to_io)
DO UPDATE SET
    kind       = EXCLUDED.kind,
    session_id = COALESCE(span_links.session_id, EXCLUDED.session_id)
`

type UpsertSpanLinkParams struct {
	OrgID       pgtype.UUID
	FromTraceID string
	FromSpanID  string
	FromIo      string
	ToTraceID   string
	ToSpanID    string
	ToIo        string
	Kind        string
	SessionID   pgtype.UUID
}

func (q *Queries) UpsertSpanLink(ctx context.Context, arg UpsertSpanLinkParams) error {
	_, err := q.db.Exec(ctx, upsertSpanLink,
		arg.OrgID,
		arg.FromTraceID,
		arg.FromSpanID,
		arg.FromIo,
		arg.ToTraceID,
		arg.ToSpanID,
		arg.ToIo,
		arg.Kind,
		arg.SessionID,
	)
	return err
}

const upsertSpanTurn = `-- name: UpsertSpanTurn :exec

INSERT INTO span_turns (
    org_id, trace_id, session_id, user_prompt, synthetic, status,
    started_at, ended_at, duration_ns,
    total_input_tokens, total_output_tokens,
    main_input_tokens, main_output_tokens,
    cache_read_tokens, cache_creation_tokens
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9,
    $10, $11,
    $12, $13,
    $14, $15
)
ON CONFLICT (org_id, trace_id) DO UPDATE SET
    session_id            = COALESCE(span_turns.session_id, EXCLUDED.session_id),
    user_prompt           = EXCLUDED.user_prompt,
    synthetic             = EXCLUDED.synthetic,
    status                = EXCLUDED.status,
    started_at            = EXCLUDED.started_at,
    ended_at              = EXCLUDED.ended_at,
    duration_ns           = EXCLUDED.duration_ns,
    total_input_tokens    = EXCLUDED.total_input_tokens,
    total_output_tokens   = EXCLUDED.total_output_tokens,
    main_input_tokens     = EXCLUDED.main_input_tokens,
    main_output_tokens    = EXCLUDED.main_output_tokens,
    cache_read_tokens     = EXCLUDED.cache_read_tokens,
    cache_creation_tokens = EXCLUDED.cache_creation_tokens
`

type UpsertSpanTurnParams struct {
	OrgID               pgtype.UUID
	TraceID             string
	SessionID           pgtype.UUID
	UserPrompt          string
	Synthetic           string
	Status              string
	StartedAt           pgtype.Timestamptz
	EndedAt             pgtype.Timestamptz
	DurationNs          int64
	TotalInputTokens    int64
	TotalOutputTokens   int64
	MainInputTokens     int64
	MainOutputTokens    int64
	CacheReadTokens     int64
	CacheCreationTokens int64
}

// Span model writes. Span identity is deterministic (minted from wire
// identity by the deriver), so re-derivation upserts the same keys in
// place and prune removes only rows a superseded projection wrote.
func (q *Queries) UpsertSpanTurn(ctx context.Context, arg UpsertSpanTurnParams) error {
	_, err := q.db.Exec(ctx, upsertSpanTurn,
		arg.OrgID,
		arg.TraceID,
		arg.SessionID,
		arg.UserPrompt,
		arg.Synthetic,
		arg.Status,
		arg.StartedAt,
		arg.EndedAt,
		arg.DurationNs,
		arg.TotalInputTokens,
		arg.TotalOutputTokens,
		arg.MainInputTokens,
		arg.MainOutputTokens,
		arg.CacheReadTokens,
		arg.CacheCreationTokens,
	)
	return err
}
