// Code generated by ent, DO NOT EDIT.

package node

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the node type in the database.
	Label = "node"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "hash"
	// FieldParentHash holds the string denoting the parent_hash field in the database.
	FieldParentHash = "parent_hash"
	// FieldBucket holds the string denoting the bucket field in the database.
	FieldBucket = "bucket"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldRole holds the string denoting the role field in the database.
	FieldRole = "role"
	// FieldContent holds the string denoting the content field in the database.
	FieldContent = "content"
	// FieldModel holds the string denoting the model field in the database.
	FieldModel = "model"
	// FieldProvider holds the string denoting the provider field in the database.
	FieldProvider = "provider"
	// FieldAgentName holds the string denoting the agent_name field in the database.
	FieldAgentName = "agent_name"
	// FieldStopReason holds the string denoting the stop_reason field in the database.
	FieldStopReason = "stop_reason"
	// FieldPromptTokens holds the string denoting the prompt_tokens field in the database.
	FieldPromptTokens = "prompt_tokens"
	// FieldCompletionTokens holds the string denoting the completion_tokens field in the database.
	FieldCompletionTokens = "completion_tokens"
	// FieldTotalTokens holds the string denoting the total_tokens field in the database.
	FieldTotalTokens = "total_tokens"
	// FieldTotalDurationNs holds the string denoting the total_duration_ns field in the database.
	FieldTotalDurationNs = "total_duration_ns"
	// FieldPromptDurationNs holds the string denoting the prompt_duration_ns field in the database.
	FieldPromptDurationNs = "prompt_duration_ns"
	// FieldProject holds the string denoting the project field in the database.
	FieldProject = "project"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeParent holds the string denoting the parent edge name in mutations.
	EdgeParent = "parent"
	// EdgeChildren holds the string denoting the children edge name in mutations.
	EdgeChildren = "children"
	// Table holds the table name of the node in the database.
	Table = "nodes"
	// ParentTable is the table that holds the parent relation/edge.
	ParentTable = "nodes"
	// ParentColumn is the table column denoting the parent relation/edge.
	ParentColumn = "parent_hash"
	// ChildrenTable is the table that holds the children relation/edge.
	ChildrenTable = "nodes"
	// ChildrenColumn is the table column denoting the children relation/edge.
	ChildrenColumn = "parent_hash"
)

// Columns holds all SQL columns for node fields.
var Columns = []string{
	FieldID,
	FieldParentHash,
	FieldBucket,
	FieldType,
	FieldRole,
	FieldContent,
	FieldModel,
	FieldProvider,
	FieldAgentName,
	FieldStopReason,
	FieldPromptTokens,
	FieldCompletionTokens,
	FieldTotalTokens,
	FieldTotalDurationNs,
	FieldPromptDurationNs,
	FieldProject,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// OrderOption defines the ordering options for the Node queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByParentHash orders the results by the parent_hash field.
func ByParentHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldParentHash, opts...).ToFunc()
}

// ByType orders the results by the type field.
func ByType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldType, opts...).ToFunc()
}

// ByRole orders the results by the role field.
func ByRole(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRole, opts...).ToFunc()
}

// ByModel orders the results by the model field.
func ByModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModel, opts...).ToFunc()
}

// ByProvider orders the results by the provider field.
func ByProvider(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProvider, opts...).ToFunc()
}

// ByAgentName orders the results by the agent_name field.
func ByAgentName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAgentName, opts...).ToFunc()
}

// ByStopReason orders the results by the stop_reason field.
func ByStopReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStopReason, opts...).ToFunc()
}

// ByPromptTokens orders the results by the prompt_tokens field.
func ByPromptTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPromptTokens, opts...).ToFunc()
}

// ByCompletionTokens orders the results by the completion_tokens field.
func ByCompletionTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompletionTokens, opts...).ToFunc()
}

// ByTotalTokens orders the results by the total_tokens field.
func ByTotalTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalTokens, opts...).ToFunc()
}

// ByTotalDurationNs orders the results by the total_duration_ns field.
func ByTotalDurationNs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalDurationNs, opts...).ToFunc()
}

// ByPromptDurationNs orders the results by the prompt_duration_ns field.
func ByPromptDurationNs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPromptDurationNs, opts...).ToFunc()
}

// ByProject orders the results by the project field.
func ByProject(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProject, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByParentField orders the results by parent field.
func ByParentField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newParentStep(), sql.OrderByField(field, opts...))
	}
}

// ByChildrenCount orders the results by children count.
func ByChildrenCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newChildrenStep(), opts...)
	}
}

// ByChildren orders the results by children terms.
func ByChildren(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newChildrenStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newParentStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(Table, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, ParentTable, ParentColumn),
	)
}
func newChildrenStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(Table, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, ChildrenTable, ChildrenColumn),
	)
}
