// Code generated by ent, DO NOT EDIT.

package node

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/papercomputeco/tapes/pkg/storage/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Node {
	return predicate.Node(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Node {
	return predicate.Node(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Node {
	return predicate.Node(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Node {
	return predicate.Node(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Node {
	return predicate.Node(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Node {
	return predicate.Node(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Node {
	return predicate.Node(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Node {
	return predicate.Node(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Node {
	return predicate.Node(sql.FieldContainsFold(FieldID, id))
}

// ParentHash applies equality check predicate on the "parent_hash" field. It's identical to ParentHashEQ.
func ParentHash(v string) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldParentHash, v))
}

// Type applies equality check predicate on the "type" field. It's identical to TypeEQ.
func Type(v string) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldType, v))
}

// Role applies equality check predicate on the "role" field. It's identical to RoleEQ.
func Role(v string) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldRole, v))
}

// Model applies equality check predicate on the "model" field. It's identical to ModelEQ.
func Model(v string) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldModel, v))
}

// Provider applies equality check predicate on the "provider" field. It's identical to ProviderEQ.
func Provider(v string) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldProvider, v))
}

// StopReason applies equality check predicate on the "stop_reason" field. It's identical to StopReasonEQ.
func StopReason(v string) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldStopReason, v))
}

// PromptTokens applies equality check predicate on the "prompt_tokens" field. It's identical to PromptTokensEQ.
func PromptTokens(v int) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldPromptTokens, v))
}

// CompletionTokens applies equality check predicate on the "completion_tokens" field. It's identical to CompletionTokensEQ.
func CompletionTokens(v int) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldCompletionTokens, v))
}

// TotalTokens applies equality check predicate on the "total_tokens" field. It's identical to TotalTokensEQ.
func TotalTokens(v int) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldTotalTokens, v))
}

// TotalDurationNs applies equality check predicate on the "total_duration_ns" field. It's identical to TotalDurationNsEQ.
func TotalDurationNs(v int64) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldTotalDurationNs, v))
}

// PromptDurationNs applies equality check predicate on the "prompt_duration_ns" field. It's identical to PromptDurationNsEQ.
func PromptDurationNs(v int64) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldPromptDurationNs, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldCreatedAt, v))
}

// ParentHashEQ applies the EQ predicate on the "parent_hash" field.
func ParentHashEQ(v string) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldParentHash, v))
}

// ParentHashNEQ applies the NEQ predicate on the "parent_hash" field.
func ParentHashNEQ(v string) predicate.Node {
	return predicate.Node(sql.FieldNEQ(FieldParentHash, v))
}

// ParentHashIn applies the In predicate on the "parent_hash" field.
func ParentHashIn(vs ...string) predicate.Node {
	return predicate.Node(sql.FieldIn(FieldParentHash, vs...))
}

// ParentHashNotIn applies the NotIn predicate on the "parent_hash" field.
func ParentHashNotIn(vs ...string) predicate.Node {
	return predicate.Node(sql.FieldNotIn(FieldParentHash, vs...))
}

// ParentHashGT applies the GT predicate on the "parent_hash" field.
func ParentHashGT(v string) predicate.Node {
	return predicate.Node(sql.FieldGT(FieldParentHash, v))
}

// ParentHashGTE applies the GTE predicate on the "parent_hash" field.
func ParentHashGTE(v string) predicate.Node {
	return predicate.Node(sql.FieldGTE(FieldParentHash, v))
}

// ParentHashLT applies the LT predicate on the "parent_hash" field.
func ParentHashLT(v string) predicate.Node {
	return predicate.Node(sql.FieldLT(FieldParentHash, v))
}

// ParentHashLTE applies the LTE predicate on the "parent_hash" field.
func ParentHashLTE(v string) predicate.Node {
	return predicate.Node(sql.FieldLTE(FieldParentHash, v))
}

// ParentHashContains applies the Contains predicate on the "parent_hash" field.
func ParentHashContains(v string) predicate.Node {
	return predicate.Node(sql.FieldContains(FieldParentHash, v))
}

// ParentHashHasPrefix applies the HasPrefix predicate on the "parent_hash" field.
func ParentHashHasPrefix(v string) predicate.Node {
	return predicate.Node(sql.FieldHasPrefix(FieldParentHash, v))
}

// ParentHashHasSuffix applies the HasSuffix predicate on the "parent_hash" field.
func ParentHashHasSuffix(v string) predicate.Node {
	return predicate.Node(sql.FieldHasSuffix(FieldParentHash, v))
}

// ParentHashIsNil applies the IsNil predicate on the "parent_hash" field.
func ParentHashIsNil() predicate.Node {
	return predicate.Node(sql.FieldIsNull(FieldParentHash))
}

// ParentHashNotNil applies the NotNil predicate on the "parent_hash" field.
func ParentHashNotNil() predicate.Node {
	return predicate.Node(sql.FieldNotNull(FieldParentHash))
}

// ParentHashEqualFold applies the EqualFold predicate on the "parent_hash" field.
func ParentHashEqualFold(v string) predicate.Node {
	return predicate.Node(sql.FieldEqualFold(FieldParentHash, v))
}

// ParentHashContainsFold applies the ContainsFold predicate on the "parent_hash" field.
func ParentHashContainsFold(v string) predicate.Node {
	return predicate.Node(sql.FieldContainsFold(FieldParentHash, v))
}

// BucketIsNil applies the IsNil predicate on the "bucket" field.
func BucketIsNil() predicate.Node {
	return predicate.Node(sql.FieldIsNull(FieldBucket))
}

// BucketNotNil applies the NotNil predicate on the "bucket" field.
func BucketNotNil() predicate.Node {
	return predicate.Node(sql.FieldNotNull(FieldBucket))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v string) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v string) predicate.Node {
	return predicate.Node(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...string) predicate.Node {
	return predicate.Node(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...string) predicate.Node {
	return predicate.Node(sql.FieldNotIn(FieldType, vs...))
}

// TypeGT applies the GT predicate on the "type" field.
func TypeGT(v string) predicate.Node {
	return predicate.Node(sql.FieldGT(FieldType, v))
}

// TypeGTE applies the GTE predicate on the "type" field.
func TypeGTE(v string) predicate.Node {
	return predicate.Node(sql.FieldGTE(FieldType, v))
}

// TypeLT applies the LT predicate on the "type" field.
func TypeLT(v string) predicate.Node {
	return predicate.Node(sql.FieldLT(FieldType, v))
}

// TypeLTE applies the LTE predicate on the "type" field.
func TypeLTE(v string) predicate.Node {
	return predicate.Node(sql.FieldLTE(FieldType, v))
}

// TypeContains applies the Contains predicate on the "type" field.
func TypeContains(v string) predicate.Node {
	return predicate.Node(sql.FieldContains(FieldType, v))
}

// TypeHasPrefix applies the HasPrefix predicate on the "type" field.
func TypeHasPrefix(v string) predicate.Node {
	return predicate.Node(sql.FieldHasPrefix(FieldType, v))
}

// TypeHasSuffix applies the HasSuffix predicate on the "type" field.
func TypeHasSuffix(v string) predicate.Node {
	return predicate.Node(sql.FieldHasSuffix(FieldType, v))
}

// TypeIsNil applies the IsNil predicate on the "type" field.
func TypeIsNil() predicate.Node {
	return predicate.Node(sql.FieldIsNull(FieldType))
}

// TypeNotNil applies the NotNil predicate on the "type" field.
func TypeNotNil() predicate.Node {
	return predicate.Node(sql.FieldNotNull(FieldType))
}

// TypeEqualFold applies the EqualFold predicate on the "type" field.
func TypeEqualFold(v string) predicate.Node {
	return predicate.Node(sql.FieldEqualFold(FieldType, v))
}

// TypeContainsFold applies the ContainsFold predicate on the "type" field.
func TypeContainsFold(v string) predicate.Node {
	return predicate.Node(sql.FieldContainsFold(FieldType, v))
}

// RoleEQ applies the EQ predicate on the "role" field.
func RoleEQ(v string) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldRole, v))
}

// RoleNEQ applies the NEQ predicate on the "role" field.
func RoleNEQ(v string) predicate.Node {
	return predicate.Node(sql.FieldNEQ(FieldRole, v))
}

// RoleIn applies the In predicate on the "role" field.
func RoleIn(vs ...string) predicate.Node {
	return predicate.Node(sql.FieldIn(FieldRole, vs...))
}

// RoleNotIn applies the NotIn predicate on the "role" field.
func RoleNotIn(vs ...string) predicate.Node {
	return predicate.Node(sql.FieldNotIn(FieldRole, vs...))
}

// RoleGT applies the GT predicate on the "role" field.
func RoleGT(v string) predicate.Node {
	return predicate.Node(sql.FieldGT(FieldRole, v))
}

// RoleGTE applies the GTE predicate on the "role" field.
func RoleGTE(v string) predicate.Node {
	return predicate.Node(sql.FieldGTE(FieldRole, v))
}

// RoleLT applies the LT predicate on the "role" field.
func RoleLT(v string) predicate.Node {
	return predicate.Node(sql.FieldLT(FieldRole, v))
}

// RoleLTE applies the LTE predicate on the "role" field.
func RoleLTE(v string) predicate.Node {
	return predicate.Node(sql.FieldLTE(FieldRole, v))
}

// RoleContains applies the Contains predicate on the "role" field.
func RoleContains(v string) predicate.Node {
	return predicate.Node(sql.FieldContains(FieldRole, v))
}

// RoleHasPrefix applies the HasPrefix predicate on the "role" field.
func RoleHasPrefix(v string) predicate.Node {
	return predicate.Node(sql.FieldHasPrefix(FieldRole, v))
}

// RoleHasSuffix applies the HasSuffix predicate on the "role" field.
func RoleHasSuffix(v string) predicate.Node {
	return predicate.Node(sql.FieldHasSuffix(FieldRole, v))
}

// RoleIsNil applies the IsNil predicate on the "role" field.
func RoleIsNil() predicate.Node {
	return predicate.Node(sql.FieldIsNull(FieldRole))
}

// RoleNotNil applies the NotNil predicate on the "role" field.
func RoleNotNil() predicate.Node {
	return predicate.Node(sql.FieldNotNull(FieldRole))
}

// RoleEqualFold applies the EqualFold predicate on the "role" field.
func RoleEqualFold(v string) predicate.Node {
	return predicate.Node(sql.FieldEqualFold(FieldRole, v))
}

// RoleContainsFold applies the ContainsFold predicate on the "role" field.
func RoleContainsFold(v string) predicate.Node {
	return predicate.Node(sql.FieldContainsFold(FieldRole, v))
}

// ContentIsNil applies the IsNil predicate on the "content" field.
func ContentIsNil() predicate.Node {
	return predicate.Node(sql.FieldIsNull(FieldContent))
}

// ContentNotNil applies the NotNil predicate on the "content" field.
func ContentNotNil() predicate.Node {
	return predicate.Node(sql.FieldNotNull(FieldContent))
}

// ModelEQ applies the EQ predicate on the "model" field.
func ModelEQ(v string) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldModel, v))
}

// ModelNEQ applies the NEQ predicate on the "model" field.
func ModelNEQ(v string) predicate.Node {
	return predicate.Node(sql.FieldNEQ(FieldModel, v))
}

// ModelIn applies the In predicate on the "model" field.
func ModelIn(vs ...string) predicate.Node {
	return predicate.Node(sql.FieldIn(FieldModel, vs...))
}

// ModelNotIn applies the NotIn predicate on the "model" field.
func ModelNotIn(vs ...string) predicate.Node {
	return predicate.Node(sql.FieldNotIn(FieldModel, vs...))
}

// ModelGT applies the GT predicate on the "model" field.
func ModelGT(v string) predicate.Node {
	return predicate.Node(sql.FieldGT(FieldModel, v))
}

// ModelGTE applies the GTE predicate on the "model" field.
func ModelGTE(v string) predicate.Node {
	return predicate.Node(sql.FieldGTE(FieldModel, v))
}

// ModelLT applies the LT predicate on the "model" field.
func ModelLT(v string) predicate.Node {
	return predicate.Node(sql.FieldLT(FieldModel, v))
}

// ModelLTE applies the LTE predicate on the "model" field.
func ModelLTE(v string) predicate.Node {
	return predicate.Node(sql.FieldLTE(FieldModel, v))
}

// ModelContains applies the Contains predicate on the "model" field.
func ModelContains(v string) predicate.Node {
	return predicate.Node(sql.FieldContains(FieldModel, v))
}

// ModelHasPrefix applies the HasPrefix predicate on the "model" field.
func ModelHasPrefix(v string) predicate.Node {
	return predicate.Node(sql.FieldHasPrefix(FieldModel, v))
}

// ModelHasSuffix applies the HasSuffix predicate on the "model" field.
func ModelHasSuffix(v string) predicate.Node {
	return predicate.Node(sql.FieldHasSuffix(FieldModel, v))
}

// ModelIsNil applies the IsNil predicate on the "model" field.
func ModelIsNil() predicate.Node {
	return predicate.Node(sql.FieldIsNull(FieldModel))
}

// ModelNotNil applies the NotNil predicate on the "model" field.
func ModelNotNil() predicate.Node {
	return predicate.Node(sql.FieldNotNull(FieldModel))
}

// ModelEqualFold applies the EqualFold predicate on the "model" field.
func ModelEqualFold(v string) predicate.Node {
	return predicate.Node(sql.FieldEqualFold(FieldModel, v))
}

// ModelContainsFold applies the ContainsFold predicate on the "model" field.
func ModelContainsFold(v string) predicate.Node {
	return predicate.Node(sql.FieldContainsFold(FieldModel, v))
}

// ProviderEQ applies the EQ predicate on the "provider" field.
func ProviderEQ(v string) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldProvider, v))
}

// ProviderNEQ applies the NEQ predicate on the "provider" field.
func ProviderNEQ(v string) predicate.Node {
	return predicate.Node(sql.FieldNEQ(FieldProvider, v))
}

// ProviderIn applies the In predicate on the "provider" field.
func ProviderIn(vs ...string) predicate.Node {
	return predicate.Node(sql.FieldIn(FieldProvider, vs...))
}

// ProviderNotIn applies the NotIn predicate on the "provider" field.
func ProviderNotIn(vs ...string) predicate.Node {
	return predicate.Node(sql.FieldNotIn(FieldProvider, vs...))
}

// ProviderGT applies the GT predicate on the "provider" field.
func ProviderGT(v string) predicate.Node {
	return predicate.Node(sql.FieldGT(FieldProvider, v))
}

// ProviderGTE applies the GTE predicate on the "provider" field.
func ProviderGTE(v string) predicate.Node {
	return predicate.Node(sql.FieldGTE(FieldProvider, v))
}

// ProviderLT applies the LT predicate on the "provider" field.
func ProviderLT(v string) predicate.Node {
	return predicate.Node(sql.FieldLT(FieldProvider, v))
}

// ProviderLTE applies the LTE predicate on the "provider" field.
func ProviderLTE(v string) predicate.Node {
	return predicate.Node(sql.FieldLTE(FieldProvider, v))
}

// ProviderContains applies the Contains predicate on the "provider" field.
func ProviderContains(v string) predicate.Node {
	return predicate.Node(sql.FieldContains(FieldProvider, v))
}

// ProviderHasPrefix applies the HasPrefix predicate on the "provider" field.
func ProviderHasPrefix(v string) predicate.Node {
	return predicate.Node(sql.FieldHasPrefix(FieldProvider, v))
}

// ProviderHasSuffix applies the HasSuffix predicate on the "provider" field.
func ProviderHasSuffix(v string) predicate.Node {
	return predicate.Node(sql.FieldHasSuffix(FieldProvider, v))
}

// ProviderIsNil applies the IsNil predicate on the "provider" field.
func ProviderIsNil() predicate.Node {
	return predicate.Node(sql.FieldIsNull(FieldProvider))
}

// ProviderNotNil applies the NotNil predicate on the "provider" field.
func ProviderNotNil() predicate.Node {
	return predicate.Node(sql.FieldNotNull(FieldProvider))
}

// ProviderEqualFold applies the EqualFold predicate on the "provider" field.
func ProviderEqualFold(v string) predicate.Node {
	return predicate.Node(sql.FieldEqualFold(FieldProvider, v))
}

// ProviderContainsFold applies the ContainsFold predicate on the "provider" field.
func ProviderContainsFold(v string) predicate.Node {
	return predicate.Node(sql.FieldContainsFold(FieldProvider, v))
}

// StopReasonEQ applies the EQ predicate on the "stop_reason" field.
func StopReasonEQ(v string) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldStopReason, v))
}

// StopReasonNEQ applies the NEQ predicate on the "stop_reason" field.
func StopReasonNEQ(v string) predicate.Node {
	return predicate.Node(sql.FieldNEQ(FieldStopReason, v))
}

// StopReasonIn applies the In predicate on the "stop_reason" field.
func StopReasonIn(vs ...string) predicate.Node {
	return predicate.Node(sql.FieldIn(FieldStopReason, vs...))
}

// StopReasonNotIn applies the NotIn predicate on the "stop_reason" field.
func StopReasonNotIn(vs ...string) predicate.Node {
	return predicate.Node(sql.FieldNotIn(FieldStopReason, vs...))
}

// StopReasonGT applies the GT predicate on the "stop_reason" field.
func StopReasonGT(v string) predicate.Node {
	return predicate.Node(sql.FieldGT(FieldStopReason, v))
}

// StopReasonGTE applies the GTE predicate on the "stop_reason" field.
func StopReasonGTE(v string) predicate.Node {
	return predicate.Node(sql.FieldGTE(FieldStopReason, v))
}

// StopReasonLT applies the LT predicate on the "stop_reason" field.
func StopReasonLT(v string) predicate.Node {
	return predicate.Node(sql.FieldLT(FieldStopReason, v))
}

// StopReasonLTE applies the LTE predicate on the "stop_reason" field.
func StopReasonLTE(v string) predicate.Node {
	return predicate.Node(sql.FieldLTE(FieldStopReason, v))
}

// StopReasonContains applies the Contains predicate on the "stop_reason" field.
func StopReasonContains(v string) predicate.Node {
	return predicate.Node(sql.FieldContains(FieldStopReason, v))
}

// StopReasonHasPrefix applies the HasPrefix predicate on the "stop_reason" field.
func StopReasonHasPrefix(v string) predicate.Node {
	return predicate.Node(sql.FieldHasPrefix(FieldStopReason, v))
}

// StopReasonHasSuffix applies the HasSuffix predicate on the "stop_reason" field.
func StopReasonHasSuffix(v string) predicate.Node {
	return predicate.Node(sql.FieldHasSuffix(FieldStopReason, v))
}

// StopReasonIsNil applies the IsNil predicate on the "stop_reason" field.
func StopReasonIsNil() predicate.Node {
	return predicate.Node(sql.FieldIsNull(FieldStopReason))
}

// StopReasonNotNil applies the NotNil predicate on the "stop_reason" field.
func StopReasonNotNil() predicate.Node {
	return predicate.Node(sql.FieldNotNull(FieldStopReason))
}

// StopReasonEqualFold applies the EqualFold predicate on the "stop_reason" field.
func StopReasonEqualFold(v string) predicate.Node {
	return predicate.Node(sql.FieldEqualFold(FieldStopReason, v))
}

// StopReasonContainsFold applies the ContainsFold predicate on the "stop_reason" field.
func StopReasonContainsFold(v string) predicate.Node {
	return predicate.Node(sql.FieldContainsFold(FieldStopReason, v))
}

// PromptTokensEQ applies the EQ predicate on the "prompt_tokens" field.
func PromptTokensEQ(v int) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldPromptTokens, v))
}

// PromptTokensNEQ applies the NEQ predicate on the "prompt_tokens" field.
func PromptTokensNEQ(v int) predicate.Node {
	return predicate.Node(sql.FieldNEQ(FieldPromptTokens, v))
}

// PromptTokensIn applies the In predicate on the "prompt_tokens" field.
func PromptTokensIn(vs ...int) predicate.Node {
	return predicate.Node(sql.FieldIn(FieldPromptTokens, vs...))
}

// PromptTokensNotIn applies the NotIn predicate on the "prompt_tokens" field.
func PromptTokensNotIn(vs ...int) predicate.Node {
	return predicate.Node(sql.FieldNotIn(FieldPromptTokens, vs...))
}

// PromptTokensGT applies the GT predicate on the "prompt_tokens" field.
func PromptTokensGT(v int) predicate.Node {
	return predicate.Node(sql.FieldGT(FieldPromptTokens, v))
}

// PromptTokensGTE applies the GTE predicate on the "prompt_tokens" field.
func PromptTokensGTE(v int) predicate.Node {
	return predicate.Node(sql.FieldGTE(FieldPromptTokens, v))
}

// PromptTokensLT applies the LT predicate on the "prompt_tokens" field.
func PromptTokensLT(v int) predicate.Node {
	return predicate.Node(sql.FieldLT(FieldPromptTokens, v))
}

// PromptTokensLTE applies the LTE predicate on the "prompt_tokens" field.
func PromptTokensLTE(v int) predicate.Node {
	return predicate.Node(sql.FieldLTE(FieldPromptTokens, v))
}

// PromptTokensIsNil applies the IsNil predicate on the "prompt_tokens" field.
func PromptTokensIsNil() predicate.Node {
	return predicate.Node(sql.FieldIsNull(FieldPromptTokens))
}

// PromptTokensNotNil applies the NotNil predicate on the "prompt_tokens" field.
func PromptTokensNotNil() predicate.Node {
	return predicate.Node(sql.FieldNotNull(FieldPromptTokens))
}

// CompletionTokensEQ applies the EQ predicate on the "completion_tokens" field.
func CompletionTokensEQ(v int) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldCompletionTokens, v))
}

// CompletionTokensNEQ applies the NEQ predicate on the "completion_tokens" field.
func CompletionTokensNEQ(v int) predicate.Node {
	return predicate.Node(sql.FieldNEQ(FieldCompletionTokens, v))
}

// CompletionTokensIn applies the In predicate on the "completion_tokens" field.
func CompletionTokensIn(vs ...int) predicate.Node {
	return predicate.Node(sql.FieldIn(FieldCompletionTokens, vs...))
}

// CompletionTokensNotIn applies the NotIn predicate on the "completion_tokens" field.
func CompletionTokensNotIn(vs ...int) predicate.Node {
	return predicate.Node(sql.FieldNotIn(FieldCompletionTokens, vs...))
}

// CompletionTokensGT applies the GT predicate on the "completion_tokens" field.
func CompletionTokensGT(v int) predicate.Node {
	return predicate.Node(sql.FieldGT(FieldCompletionTokens, v))
}

// CompletionTokensGTE applies the GTE predicate on the "completion_tokens" field.
func CompletionTokensGTE(v int) predicate.Node {
	return predicate.Node(sql.FieldGTE(FieldCompletionTokens, v))
}

// CompletionTokensLT applies the LT predicate on the "completion_tokens" field.
func CompletionTokensLT(v int) predicate.Node {
	return predicate.Node(sql.FieldLT(FieldCompletionTokens, v))
}

// CompletionTokensLTE applies the LTE predicate on the "completion_tokens" field.
func CompletionTokensLTE(v int) predicate.Node {
	return predicate.Node(sql.FieldLTE(FieldCompletionTokens, v))
}

// CompletionTokensIsNil applies the IsNil predicate on the "completion_tokens" field.
func CompletionTokensIsNil() predicate.Node {
	return predicate.Node(sql.FieldIsNull(FieldCompletionTokens))
}

// CompletionTokensNotNil applies the NotNil predicate on the "completion_tokens" field.
func CompletionTokensNotNil() predicate.Node {
	return predicate.Node(sql.FieldNotNull(FieldCompletionTokens))
}

// TotalTokensEQ applies the EQ predicate on the "total_tokens" field.
func TotalTokensEQ(v int) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldTotalTokens, v))
}

// TotalTokensNEQ applies the NEQ predicate on the "total_tokens" field.
func TotalTokensNEQ(v int) predicate.Node {
	return predicate.Node(sql.FieldNEQ(FieldTotalTokens, v))
}

// TotalTokensIn applies the In predicate on the "total_tokens" field.
func TotalTokensIn(vs ...int) predicate.Node {
	return predicate.Node(sql.FieldIn(FieldTotalTokens, vs...))
}

// TotalTokensNotIn applies the NotIn predicate on the "total_tokens" field.
func TotalTokensNotIn(vs ...int) predicate.Node {
	return predicate.Node(sql.FieldNotIn(FieldTotalTokens, vs...))
}

// TotalTokensGT applies the GT predicate on the "total_tokens" field.
func TotalTokensGT(v int) predicate.Node {
	return predicate.Node(sql.FieldGT(FieldTotalTokens, v))
}

// TotalTokensGTE applies the GTE predicate on the "total_tokens" field.
func TotalTokensGTE(v int) predicate.Node {
	return predicate.Node(sql.FieldGTE(FieldTotalTokens, v))
}

// TotalTokensLT applies the LT predicate on the "total_tokens" field.
func TotalTokensLT(v int) predicate.Node {
	return predicate.Node(sql.FieldLT(FieldTotalTokens, v))
}

// TotalTokensLTE applies the LTE predicate on the "total_tokens" field.
func TotalTokensLTE(v int) predicate.Node {
	return predicate.Node(sql.FieldLTE(FieldTotalTokens, v))
}

// TotalTokensIsNil applies the IsNil predicate on the "total_tokens" field.
func TotalTokensIsNil() predicate.Node {
	return predicate.Node(sql.FieldIsNull(FieldTotalTokens))
}

// TotalTokensNotNil applies the NotNil predicate on the "total_tokens" field.
func TotalTokensNotNil() predicate.Node {
	return predicate.Node(sql.FieldNotNull(FieldTotalTokens))
}

// TotalDurationNsEQ applies the EQ predicate on the "total_duration_ns" field.
func TotalDurationNsEQ(v int64) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldTotalDurationNs, v))
}

// TotalDurationNsNEQ applies the NEQ predicate on the "total_duration_ns" field.
func TotalDurationNsNEQ(v int64) predicate.Node {
	return predicate.Node(sql.FieldNEQ(FieldTotalDurationNs, v))
}

// TotalDurationNsIn applies the In predicate on the "total_duration_ns" field.
func TotalDurationNsIn(vs ...int64) predicate.Node {
	return predicate.Node(sql.FieldIn(FieldTotalDurationNs, vs...))
}

// TotalDurationNsNotIn applies the NotIn predicate on the "total_duration_ns" field.
func TotalDurationNsNotIn(vs ...int64) predicate.Node {
	return predicate.Node(sql.FieldNotIn(FieldTotalDurationNs, vs...))
}

// TotalDurationNsGT applies the GT predicate on the "total_duration_ns" field.
func TotalDurationNsGT(v int64) predicate.Node {
	return predicate.Node(sql.FieldGT(FieldTotalDurationNs, v))
}

// TotalDurationNsGTE applies the GTE predicate on the "total_duration_ns" field.
func TotalDurationNsGTE(v int64) predicate.Node {
	return predicate.Node(sql.FieldGTE(FieldTotalDurationNs, v))
}

// TotalDurationNsLT applies the LT predicate on the "total_duration_ns" field.
func TotalDurationNsLT(v int64) predicate.Node {
	return predicate.Node(sql.FieldLT(FieldTotalDurationNs, v))
}

// TotalDurationNsLTE applies the LTE predicate on the "total_duration_ns" field.
func TotalDurationNsLTE(v int64) predicate.Node {
	return predicate.Node(sql.FieldLTE(FieldTotalDurationNs, v))
}

// TotalDurationNsIsNil applies the IsNil predicate on the "total_duration_ns" field.
func TotalDurationNsIsNil() predicate.Node {
	return predicate.Node(sql.FieldIsNull(FieldTotalDurationNs))
}

// TotalDurationNsNotNil applies the NotNil predicate on the "total_duration_ns" field.
func TotalDurationNsNotNil() predicate.Node {
	return predicate.Node(sql.FieldNotNull(FieldTotalDurationNs))
}

// PromptDurationNsEQ applies the EQ predicate on the "prompt_duration_ns" field.
func PromptDurationNsEQ(v int64) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldPromptDurationNs, v))
}

// PromptDurationNsNEQ applies the NEQ predicate on the "prompt_duration_ns" field.
func PromptDurationNsNEQ(v int64) predicate.Node {
	return predicate.Node(sql.FieldNEQ(FieldPromptDurationNs, v))
}

// PromptDurationNsIn applies the In predicate on the "prompt_duration_ns" field.
func PromptDurationNsIn(vs ...int64) predicate.Node {
	return predicate.Node(sql.FieldIn(FieldPromptDurationNs, vs...))
}

// PromptDurationNsNotIn applies the NotIn predicate on the "prompt_duration_ns" field.
func PromptDurationNsNotIn(vs ...int64) predicate.Node {
	return predicate.Node(sql.FieldNotIn(FieldPromptDurationNs, vs...))
}

// PromptDurationNsGT applies the GT predicate on the "prompt_duration_ns" field.
func PromptDurationNsGT(v int64) predicate.Node {
	return predicate.Node(sql.FieldGT(FieldPromptDurationNs, v))
}

// PromptDurationNsGTE applies the GTE predicate on the "prompt_duration_ns" field.
func PromptDurationNsGTE(v int64) predicate.Node {
	return predicate.Node(sql.FieldGTE(FieldPromptDurationNs, v))
}

// PromptDurationNsLT applies the LT predicate on the "prompt_duration_ns" field.
func PromptDurationNsLT(v int64) predicate.Node {
	return predicate.Node(sql.FieldLT(FieldPromptDurationNs, v))
}

// PromptDurationNsLTE applies the LTE predicate on the "prompt_duration_ns" field.
func PromptDurationNsLTE(v int64) predicate.Node {
	return predicate.Node(sql.FieldLTE(FieldPromptDurationNs, v))
}

// PromptDurationNsIsNil applies the IsNil predicate on the "prompt_duration_ns" field.
func PromptDurationNsIsNil() predicate.Node {
	return predicate.Node(sql.FieldIsNull(FieldPromptDurationNs))
}

// PromptDurationNsNotNil applies the NotNil predicate on the "prompt_duration_ns" field.
func PromptDurationNsNotNil() predicate.Node {
	return predicate.Node(sql.FieldNotNull(FieldPromptDurationNs))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Node {
	return predicate.Node(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Node {
	return predicate.Node(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Node {
	return predicate.Node(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Node {
	return predicate.Node(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Node {
	return predicate.Node(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Node {
	return predicate.Node(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Node {
	return predicate.Node(sql.FieldLTE(FieldCreatedAt, v))
}

// HasParent applies the HasEdge predicate on the "parent" edge.
func HasParent() predicate.Node {
	return predicate.Node(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, ParentTable, ParentColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasParentWith applies the HasEdge predicate on the "parent" edge with a given conditions (other predicates).
func HasParentWith(preds ...predicate.Node) predicate.Node {
	return predicate.Node(func(s *sql.Selector) {
		step := newParentStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasChildren applies the HasEdge predicate on the "children" edge.
func HasChildren() predicate.Node {
	return predicate.Node(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, ChildrenTable, ChildrenColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasChildrenWith applies the HasEdge predicate on the "children" edge with a given conditions (other predicates).
func HasChildrenWith(preds ...predicate.Node) predicate.Node {
	return predicate.Node(func(s *sql.Selector) {
		step := newChildrenStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Node) predicate.Node {
	return predicate.Node(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Node) predicate.Node {
	return predicate.Node(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Node) predicate.Node {
	return predicate.Node(sql.NotPredicates(p))
}
