// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/papercomputeco/tapes/pkg/storage/ent/agenttrace"
	"github.com/papercomputeco/tapes/pkg/storage/ent/agenttracefile"
)

// AgentTraceFile is the model entity for the AgentTraceFile schema.
type AgentTraceFile struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Path holds the value of the "path" field.
	Path string `json:"path,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AgentTraceFileQuery when eager-loading is set.
	Edges             AgentTraceFileEdges `json:"edges"`
	agent_trace_files *string
	selectValues      sql.SelectValues
}

// AgentTraceFileEdges holds the relations/edges for other nodes in the graph.
type AgentTraceFileEdges struct {
	// Trace holds the value of the trace edge.
	Trace *AgentTrace `json:"trace,omitempty"`
	// Conversations holds the value of the conversations edge.
	Conversations []*AgentTraceConversation `json:"conversations,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// TraceOrErr returns the Trace value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AgentTraceFileEdges) TraceOrErr() (*AgentTrace, error) {
	if e.Trace != nil {
		return e.Trace, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: agenttrace.Label}
	}
	return nil, &NotLoadedError{edge: "trace"}
}

// ConversationsOrErr returns the Conversations value or an error if the edge
// was not loaded in eager-loading.
func (e AgentTraceFileEdges) ConversationsOrErr() ([]*AgentTraceConversation, error) {
	if e.loadedTypes[1] {
		return e.Conversations, nil
	}
	return nil, &NotLoadedError{edge: "conversations"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AgentTraceFile) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case agenttracefile.FieldID:
			values[i] = new(sql.NullInt64)
		case agenttracefile.FieldPath:
			values[i] = new(sql.NullString)
		case agenttracefile.ForeignKeys[0]: // agent_trace_files
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AgentTraceFile fields.
func (_m *AgentTraceFile) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case agenttracefile.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case agenttracefile.FieldPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field path", values[i])
			} else if value.Valid {
				_m.Path = value.String
			}
		case agenttracefile.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field agent_trace_files", values[i])
			} else if value.Valid {
				_m.agent_trace_files = new(string)
				*_m.agent_trace_files = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AgentTraceFile.
// This includes values selected through modifiers, order, etc.
func (_m *AgentTraceFile) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTrace queries the "trace" edge of the AgentTraceFile entity.
func (_m *AgentTraceFile) QueryTrace() *AgentTraceQuery {
	return NewAgentTraceFileClient(_m.config).QueryTrace(_m)
}

// QueryConversations queries the "conversations" edge of the AgentTraceFile entity.
func (_m *AgentTraceFile) QueryConversations() *AgentTraceConversationQuery {
	return NewAgentTraceFileClient(_m.config).QueryConversations(_m)
}

// Update returns a builder for updating this AgentTraceFile.
// Note that you need to call AgentTraceFile.Unwrap() before calling this method if this AgentTraceFile
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AgentTraceFile) Update() *AgentTraceFileUpdateOne {
	return NewAgentTraceFileClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AgentTraceFile entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AgentTraceFile) Unwrap() *AgentTraceFile {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AgentTraceFile is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AgentTraceFile) String() string {
	var builder strings.Builder
	builder.WriteString("AgentTraceFile(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("path=")
	builder.WriteString(_m.Path)
	builder.WriteByte(')')
	return builder.String()
}

// AgentTraceFiles is a parsable slice of AgentTraceFile.
type AgentTraceFiles []*AgentTraceFile
