// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/papercomputeco/tapes/pkg/storage/ent/agenttrace"
	"github.com/papercomputeco/tapes/pkg/storage/ent/agenttracefile"
)

// AgentTraceCreate is the builder for creating a AgentTrace entity.
type AgentTraceCreate struct {
	config
	mutation *AgentTraceMutation
	hooks    []Hook
}

// SetVersion sets the "version" field.
func (_c *AgentTraceCreate) SetVersion(v string) *AgentTraceCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetTimestamp sets the "timestamp" field.
func (_c *AgentTraceCreate) SetTimestamp(v string) *AgentTraceCreate {
	_c.mutation.SetTimestamp(v)
	return _c
}

// SetVcsType sets the "vcs_type" field.
func (_c *AgentTraceCreate) SetVcsType(v string) *AgentTraceCreate {
	_c.mutation.SetVcsType(v)
	return _c
}

// SetNillableVcsType sets the "vcs_type" field if the given value is not nil.
func (_c *AgentTraceCreate) SetNillableVcsType(v *string) *AgentTraceCreate {
	if v != nil {
		_c.SetVcsType(*v)
	}
	return _c
}

// SetVcsRevision sets the "vcs_revision" field.
func (_c *AgentTraceCreate) SetVcsRevision(v string) *AgentTraceCreate {
	_c.mutation.SetVcsRevision(v)
	return _c
}

// SetNillableVcsRevision sets the "vcs_revision" field if the given value is not nil.
func (_c *AgentTraceCreate) SetNillableVcsRevision(v *string) *AgentTraceCreate {
	if v != nil {
		_c.SetVcsRevision(*v)
	}
	return _c
}

// SetToolName sets the "tool_name" field.
func (_c *AgentTraceCreate) SetToolName(v string) *AgentTraceCreate {
	_c.mutation.SetToolName(v)
	return _c
}

// SetNillableToolName sets the "tool_name" field if the given value is not nil.
func (_c *AgentTraceCreate) SetNillableToolName(v *string) *AgentTraceCreate {
	if v != nil {
		_c.SetToolName(*v)
	}
	return _c
}

// SetToolVersion sets the "tool_version" field.
func (_c *AgentTraceCreate) SetToolVersion(v string) *AgentTraceCreate {
	_c.mutation.SetToolVersion(v)
	return _c
}

// SetNillableToolVersion sets the "tool_version" field if the given value is not nil.
func (_c *AgentTraceCreate) SetNillableToolVersion(v *string) *AgentTraceCreate {
	if v != nil {
		_c.SetToolVersion(*v)
	}
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *AgentTraceCreate) SetMetadata(v map[string]interface{}) *AgentTraceCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AgentTraceCreate) SetCreatedAt(v time.Time) *AgentTraceCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AgentTraceCreate) SetNillableCreatedAt(v *time.Time) *AgentTraceCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AgentTraceCreate) SetID(v string) *AgentTraceCreate {
	_c.mutation.SetID(v)
	return _c
}

// AddFileIDs adds the "files" edge to the AgentTraceFile entity by IDs.
func (_c *AgentTraceCreate) AddFileIDs(ids ...int) *AgentTraceCreate {
	_c.mutation.AddFileIDs(ids...)
	return _c
}

// AddFiles adds the "files" edges to the AgentTraceFile entity.
func (_c *AgentTraceCreate) AddFiles(v ...*AgentTraceFile) *AgentTraceCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddFileIDs(ids...)
}

// Mutation returns the AgentTraceMutation object of the builder.
func (_c *AgentTraceCreate) Mutation() *AgentTraceMutation {
	return _c.mutation
}

// Save creates the AgentTrace in the database.
func (_c *AgentTraceCreate) Save(ctx context.Context) (*AgentTrace, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AgentTraceCreate) SaveX(ctx context.Context) *AgentTrace {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AgentTraceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AgentTraceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AgentTraceCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := agenttrace.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AgentTraceCreate) check() error {
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "AgentTrace.version"`)}
	}
	if v, ok := _c.mutation.Version(); ok {
		if err := agenttrace.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "AgentTrace.version": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Timestamp(); !ok {
		return &ValidationError{Name: "timestamp", err: errors.New(`ent: missing required field "AgentTrace.timestamp"`)}
	}
	if v, ok := _c.mutation.Timestamp(); ok {
		if err := agenttrace.TimestampValidator(v); err != nil {
			return &ValidationError{Name: "timestamp", err: fmt.Errorf(`ent: validator failed for field "AgentTrace.timestamp": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AgentTrace.created_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := agenttrace.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "AgentTrace.id": %w`, err)}
		}
	}
	return nil
}

func (_c *AgentTraceCreate) sqlSave(ctx context.Context) (*AgentTrace, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected AgentTrace.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AgentTraceCreate) createSpec() (*AgentTrace, *sqlgraph.CreateSpec) {
	var (
		_node = &AgentTrace{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(agenttrace.Table, sqlgraph.NewFieldSpec(agenttrace.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(agenttrace.FieldVersion, field.TypeString, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.Timestamp(); ok {
		_spec.SetField(agenttrace.FieldTimestamp, field.TypeString, value)
		_node.Timestamp = value
	}
	if value, ok := _c.mutation.VcsType(); ok {
		_spec.SetField(agenttrace.FieldVcsType, field.TypeString, value)
		_node.VcsType = value
	}
	if value, ok := _c.mutation.VcsRevision(); ok {
		_spec.SetField(agenttrace.FieldVcsRevision, field.TypeString, value)
		_node.VcsRevision = value
	}
	if value, ok := _c.mutation.ToolName(); ok {
		_spec.SetField(agenttrace.FieldToolName, field.TypeString, value)
		_node.ToolName = value
	}
	if value, ok := _c.mutation.ToolVersion(); ok {
		_spec.SetField(agenttrace.FieldToolVersion, field.TypeString, value)
		_node.ToolVersion = value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(agenttrace.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(agenttrace.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.FilesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agenttrace.FilesTable,
			Columns: []string{agenttrace.FilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agenttracefile.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AgentTraceCreateBulk is the builder for creating many AgentTrace entities in bulk.
type AgentTraceCreateBulk struct {
	config
	err      error
	builders []*AgentTraceCreate
}

// Save creates the AgentTrace entities in the database.
func (_c *AgentTraceCreateBulk) Save(ctx context.Context) ([]*AgentTrace, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AgentTrace, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AgentTraceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AgentTraceCreateBulk) SaveX(ctx context.Context) []*AgentTrace {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AgentTraceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AgentTraceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
