// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/papercomputeco/tapes/pkg/storage/ent/agenttraceconversation"
	"github.com/papercomputeco/tapes/pkg/storage/ent/agenttracefile"
	"github.com/papercomputeco/tapes/pkg/storage/ent/agenttracerange"
)

// AgentTraceConversationCreate is the builder for creating a AgentTraceConversation entity.
type AgentTraceConversationCreate struct {
	config
	mutation *AgentTraceConversationMutation
	hooks    []Hook
}

// SetURL sets the "url" field.
func (_c *AgentTraceConversationCreate) SetURL(v string) *AgentTraceConversationCreate {
	_c.mutation.SetURL(v)
	return _c
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_c *AgentTraceConversationCreate) SetNillableURL(v *string) *AgentTraceConversationCreate {
	if v != nil {
		_c.SetURL(*v)
	}
	return _c
}

// SetContributorType sets the "contributor_type" field.
func (_c *AgentTraceConversationCreate) SetContributorType(v string) *AgentTraceConversationCreate {
	_c.mutation.SetContributorType(v)
	return _c
}

// SetNillableContributorType sets the "contributor_type" field if the given value is not nil.
func (_c *AgentTraceConversationCreate) SetNillableContributorType(v *string) *AgentTraceConversationCreate {
	if v != nil {
		_c.SetContributorType(*v)
	}
	return _c
}

// SetContributorModelID sets the "contributor_model_id" field.
func (_c *AgentTraceConversationCreate) SetContributorModelID(v string) *AgentTraceConversationCreate {
	_c.mutation.SetContributorModelID(v)
	return _c
}

// SetNillableContributorModelID sets the "contributor_model_id" field if the given value is not nil.
func (_c *AgentTraceConversationCreate) SetNillableContributorModelID(v *string) *AgentTraceConversationCreate {
	if v != nil {
		_c.SetContributorModelID(*v)
	}
	return _c
}

// SetRelated sets the "related" field.
func (_c *AgentTraceConversationCreate) SetRelated(v []map[string]interface{}) *AgentTraceConversationCreate {
	_c.mutation.SetRelated(v)
	return _c
}

// SetFileID sets the "file" edge to the AgentTraceFile entity by ID.
func (_c *AgentTraceConversationCreate) SetFileID(id int) *AgentTraceConversationCreate {
	_c.mutation.SetFileID(id)
	return _c
}

// SetFile sets the "file" edge to the AgentTraceFile entity.
func (_c *AgentTraceConversationCreate) SetFile(v *AgentTraceFile) *AgentTraceConversationCreate {
	return _c.SetFileID(v.ID)
}

// AddRangeIDs adds the "ranges" edge to the AgentTraceRange entity by IDs.
func (_c *AgentTraceConversationCreate) AddRangeIDs(ids ...int) *AgentTraceConversationCreate {
	_c.mutation.AddRangeIDs(ids...)
	return _c
}

// AddRanges adds the "ranges" edges to the AgentTraceRange entity.
func (_c *AgentTraceConversationCreate) AddRanges(v ...*AgentTraceRange) *AgentTraceConversationCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddRangeIDs(ids...)
}

// Mutation returns the AgentTraceConversationMutation object of the builder.
func (_c *AgentTraceConversationCreate) Mutation() *AgentTraceConversationMutation {
	return _c.mutation
}

// Save creates the AgentTraceConversation in the database.
func (_c *AgentTraceConversationCreate) Save(ctx context.Context) (*AgentTraceConversation, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AgentTraceConversationCreate) SaveX(ctx context.Context) *AgentTraceConversation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AgentTraceConversationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AgentTraceConversationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AgentTraceConversationCreate) check() error {
	if len(_c.mutation.FileIDs()) == 0 {
		return &ValidationError{Name: "file", err: errors.New(`ent: missing required edge "AgentTraceConversation.file"`)}
	}
	return nil
}

func (_c *AgentTraceConversationCreate) sqlSave(ctx context.Context) (*AgentTraceConversation, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AgentTraceConversationCreate) createSpec() (*AgentTraceConversation, *sqlgraph.CreateSpec) {
	var (
		_node = &AgentTraceConversation{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(agenttraceconversation.Table, sqlgraph.NewFieldSpec(agenttraceconversation.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.URL(); ok {
		_spec.SetField(agenttraceconversation.FieldURL, field.TypeString, value)
		_node.URL = value
	}
	if value, ok := _c.mutation.ContributorType(); ok {
		_spec.SetField(agenttraceconversation.FieldContributorType, field.TypeString, value)
		_node.ContributorType = value
	}
	if value, ok := _c.mutation.ContributorModelID(); ok {
		_spec.SetField(agenttraceconversation.FieldContributorModelID, field.TypeString, value)
		_node.ContributorModelID = value
	}
	if value, ok := _c.mutation.Related(); ok {
		_spec.SetField(agenttraceconversation.FieldRelated, field.TypeJSON, value)
		_node.Related = value
	}
	if nodes := _c.mutation.FileIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agenttraceconversation.FileTable,
			Columns: []string{agenttraceconversation.FileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agenttracefile.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.agent_trace_file_conversations = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.RangesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agenttraceconversation.RangesTable,
			Columns: []string{agenttraceconversation.RangesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agenttracerange.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AgentTraceConversationCreateBulk is the builder for creating many AgentTraceConversation entities in bulk.
type AgentTraceConversationCreateBulk struct {
	config
	err      error
	builders []*AgentTraceConversationCreate
}

// Save creates the AgentTraceConversation entities in the database.
func (_c *AgentTraceConversationCreateBulk) Save(ctx context.Context) ([]*AgentTraceConversation, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AgentTraceConversation, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AgentTraceConversationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AgentTraceConversationCreateBulk) SaveX(ctx context.Context) []*AgentTraceConversation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AgentTraceConversationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AgentTraceConversationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
