// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/papercomputeco/tapes/pkg/storage/ent/agenttrace"
	"github.com/papercomputeco/tapes/pkg/storage/ent/agenttraceconversation"
	"github.com/papercomputeco/tapes/pkg/storage/ent/agenttracefile"
	"github.com/papercomputeco/tapes/pkg/storage/ent/predicate"
)

// AgentTraceFileUpdate is the builder for updating AgentTraceFile entities.
type AgentTraceFileUpdate struct {
	config
	hooks    []Hook
	mutation *AgentTraceFileMutation
}

// Where appends a list predicates to the AgentTraceFileUpdate builder.
func (_u *AgentTraceFileUpdate) Where(ps ...predicate.AgentTraceFile) *AgentTraceFileUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPath sets the "path" field.
func (_u *AgentTraceFileUpdate) SetPath(v string) *AgentTraceFileUpdate {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *AgentTraceFileUpdate) SetNillablePath(v *string) *AgentTraceFileUpdate {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// SetTraceID sets the "trace" edge to the AgentTrace entity by ID.
func (_u *AgentTraceFileUpdate) SetTraceID(id string) *AgentTraceFileUpdate {
	_u.mutation.SetTraceID(id)
	return _u
}

// SetTrace sets the "trace" edge to the AgentTrace entity.
func (_u *AgentTraceFileUpdate) SetTrace(v *AgentTrace) *AgentTraceFileUpdate {
	return _u.SetTraceID(v.ID)
}

// AddConversationIDs adds the "conversations" edge to the AgentTraceConversation entity by IDs.
func (_u *AgentTraceFileUpdate) AddConversationIDs(ids ...int) *AgentTraceFileUpdate {
	_u.mutation.AddConversationIDs(ids...)
	return _u
}

// AddConversations adds the "conversations" edges to the AgentTraceConversation entity.
func (_u *AgentTraceFileUpdate) AddConversations(v ...*AgentTraceConversation) *AgentTraceFileUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddConversationIDs(ids...)
}

// Mutation returns the AgentTraceFileMutation object of the builder.
func (_u *AgentTraceFileUpdate) Mutation() *AgentTraceFileMutation {
	return _u.mutation
}

// ClearTrace clears the "trace" edge to the AgentTrace entity.
func (_u *AgentTraceFileUpdate) ClearTrace() *AgentTraceFileUpdate {
	_u.mutation.ClearTrace()
	return _u
}

// ClearConversations clears all "conversations" edges to the AgentTraceConversation entity.
func (_u *AgentTraceFileUpdate) ClearConversations() *AgentTraceFileUpdate {
	_u.mutation.ClearConversations()
	return _u
}

// RemoveConversationIDs removes the "conversations" edge to AgentTraceConversation entities by IDs.
func (_u *AgentTraceFileUpdate) RemoveConversationIDs(ids ...int) *AgentTraceFileUpdate {
	_u.mutation.RemoveConversationIDs(ids...)
	return _u
}

// RemoveConversations removes "conversations" edges to AgentTraceConversation entities.
func (_u *AgentTraceFileUpdate) RemoveConversations(v ...*AgentTraceConversation) *AgentTraceFileUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveConversationIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AgentTraceFileUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AgentTraceFileUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AgentTraceFileUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AgentTraceFileUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AgentTraceFileUpdate) check() error {
	if v, ok := _u.mutation.Path(); ok {
		if err := agenttracefile.PathValidator(v); err != nil {
			return &ValidationError{Name: "path", err: fmt.Errorf(`ent: validator failed for field "AgentTraceFile.path": %w`, err)}
		}
	}
	if _u.mutation.TraceCleared() && len(_u.mutation.TraceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AgentTraceFile.trace"`)
	}
	return nil
}

func (_u *AgentTraceFileUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(agenttracefile.Table, agenttracefile.Columns, sqlgraph.NewFieldSpec(agenttracefile.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(agenttracefile.FieldPath, field.TypeString, value)
	}
	if _u.mutation.TraceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agenttracefile.TraceTable,
			Columns: []string{agenttracefile.TraceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agenttrace.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TraceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agenttracefile.TraceTable,
			Columns: []string{agenttracefile.TraceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agenttrace.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ConversationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agenttracefile.ConversationsTable,
			Columns: []string{agenttracefile.ConversationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agenttraceconversation.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedConversationsIDs(); len(nodes) > 0 && !_u.mutation.ConversationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agenttracefile.ConversationsTable,
			Columns: []string{agenttracefile.ConversationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agenttraceconversation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ConversationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agenttracefile.ConversationsTable,
			Columns: []string{agenttracefile.ConversationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agenttraceconversation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{agenttracefile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AgentTraceFileUpdateOne is the builder for updating a single AgentTraceFile entity.
type AgentTraceFileUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AgentTraceFileMutation
}

// SetPath sets the "path" field.
func (_u *AgentTraceFileUpdateOne) SetPath(v string) *AgentTraceFileUpdateOne {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *AgentTraceFileUpdateOne) SetNillablePath(v *string) *AgentTraceFileUpdateOne {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// SetTraceID sets the "trace" edge to the AgentTrace entity by ID.
func (_u *AgentTraceFileUpdateOne) SetTraceID(id string) *AgentTraceFileUpdateOne {
	_u.mutation.SetTraceID(id)
	return _u
}

// SetTrace sets the "trace" edge to the AgentTrace entity.
func (_u *AgentTraceFileUpdateOne) SetTrace(v *AgentTrace) *AgentTraceFileUpdateOne {
	return _u.SetTraceID(v.ID)
}

// AddConversationIDs adds the "conversations" edge to the AgentTraceConversation entity by IDs.
func (_u *AgentTraceFileUpdateOne) AddConversationIDs(ids ...int) *AgentTraceFileUpdateOne {
	_u.mutation.AddConversationIDs(ids...)
	return _u
}

// AddConversations adds the "conversations" edges to the AgentTraceConversation entity.
func (_u *AgentTraceFileUpdateOne) AddConversations(v ...*AgentTraceConversation) *AgentTraceFileUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddConversationIDs(ids...)
}

// Mutation returns the AgentTraceFileMutation object of the builder.
func (_u *AgentTraceFileUpdateOne) Mutation() *AgentTraceFileMutation {
	return _u.mutation
}

// ClearTrace clears the "trace" edge to the AgentTrace entity.
func (_u *AgentTraceFileUpdateOne) ClearTrace() *AgentTraceFileUpdateOne {
	_u.mutation.ClearTrace()
	return _u
}

// ClearConversations clears all "conversations" edges to the AgentTraceConversation entity.
func (_u *AgentTraceFileUpdateOne) ClearConversations() *AgentTraceFileUpdateOne {
	_u.mutation.ClearConversations()
	return _u
}

// RemoveConversationIDs removes the "conversations" edge to AgentTraceConversation entities by IDs.
func (_u *AgentTraceFileUpdateOne) RemoveConversationIDs(ids ...int) *AgentTraceFileUpdateOne {
	_u.mutation.RemoveConversationIDs(ids...)
	return _u
}

// RemoveConversations removes "conversations" edges to AgentTraceConversation entities.
func (_u *AgentTraceFileUpdateOne) RemoveConversations(v ...*AgentTraceConversation) *AgentTraceFileUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveConversationIDs(ids...)
}

// Where appends a list predicates to the AgentTraceFileUpdate builder.
func (_u *AgentTraceFileUpdateOne) Where(ps ...predicate.AgentTraceFile) *AgentTraceFileUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AgentTraceFileUpdateOne) Select(field string, fields ...string) *AgentTraceFileUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AgentTraceFile entity.
func (_u *AgentTraceFileUpdateOne) Save(ctx context.Context) (*AgentTraceFile, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AgentTraceFileUpdateOne) SaveX(ctx context.Context) *AgentTraceFile {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AgentTraceFileUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AgentTraceFileUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AgentTraceFileUpdateOne) check() error {
	if v, ok := _u.mutation.Path(); ok {
		if err := agenttracefile.PathValidator(v); err != nil {
			return &ValidationError{Name: "path", err: fmt.Errorf(`ent: validator failed for field "AgentTraceFile.path": %w`, err)}
		}
	}
	if _u.mutation.TraceCleared() && len(_u.mutation.TraceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AgentTraceFile.trace"`)
	}
	return nil
}

func (_u *AgentTraceFileUpdateOne) sqlSave(ctx context.Context) (_node *AgentTraceFile, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(agenttracefile.Table, agenttracefile.Columns, sqlgraph.NewFieldSpec(agenttracefile.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AgentTraceFile.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, agenttracefile.FieldID)
		for _, f := range fields {
			if !agenttracefile.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != agenttracefile.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(agenttracefile.FieldPath, field.TypeString, value)
	}
	if _u.mutation.TraceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agenttracefile.TraceTable,
			Columns: []string{agenttracefile.TraceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agenttrace.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TraceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agenttracefile.TraceTable,
			Columns: []string{agenttracefile.TraceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agenttrace.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ConversationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agenttracefile.ConversationsTable,
			Columns: []string{agenttracefile.ConversationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agenttraceconversation.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedConversationsIDs(); len(nodes) > 0 && !_u.mutation.ConversationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agenttracefile.ConversationsTable,
			Columns: []string{agenttracefile.ConversationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agenttraceconversation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ConversationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agenttracefile.ConversationsTable,
			Columns: []string{agenttracefile.ConversationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agenttraceconversation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &AgentTraceFile{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{agenttracefile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
