// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/papercomputeco/tapes/pkg/storage/ent/agenttraceconversation"
	"github.com/papercomputeco/tapes/pkg/storage/ent/agenttracerange"
	"github.com/papercomputeco/tapes/pkg/storage/ent/predicate"
)

// AgentTraceRangeUpdate is the builder for updating AgentTraceRange entities.
type AgentTraceRangeUpdate struct {
	config
	hooks    []Hook
	mutation *AgentTraceRangeMutation
}

// Where appends a list predicates to the AgentTraceRangeUpdate builder.
func (_u *AgentTraceRangeUpdate) Where(ps ...predicate.AgentTraceRange) *AgentTraceRangeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetStartLine sets the "start_line" field.
func (_u *AgentTraceRangeUpdate) SetStartLine(v int) *AgentTraceRangeUpdate {
	_u.mutation.ResetStartLine()
	_u.mutation.SetStartLine(v)
	return _u
}

// SetNillableStartLine sets the "start_line" field if the given value is not nil.
func (_u *AgentTraceRangeUpdate) SetNillableStartLine(v *int) *AgentTraceRangeUpdate {
	if v != nil {
		_u.SetStartLine(*v)
	}
	return _u
}

// AddStartLine adds value to the "start_line" field.
func (_u *AgentTraceRangeUpdate) AddStartLine(v int) *AgentTraceRangeUpdate {
	_u.mutation.AddStartLine(v)
	return _u
}

// SetEndLine sets the "end_line" field.
func (_u *AgentTraceRangeUpdate) SetEndLine(v int) *AgentTraceRangeUpdate {
	_u.mutation.ResetEndLine()
	_u.mutation.SetEndLine(v)
	return _u
}

// SetNillableEndLine sets the "end_line" field if the given value is not nil.
func (_u *AgentTraceRangeUpdate) SetNillableEndLine(v *int) *AgentTraceRangeUpdate {
	if v != nil {
		_u.SetEndLine(*v)
	}
	return _u
}

// AddEndLine adds value to the "end_line" field.
func (_u *AgentTraceRangeUpdate) AddEndLine(v int) *AgentTraceRangeUpdate {
	_u.mutation.AddEndLine(v)
	return _u
}

// SetContentHash sets the "content_hash" field.
func (_u *AgentTraceRangeUpdate) SetContentHash(v string) *AgentTraceRangeUpdate {
	_u.mutation.SetContentHash(v)
	return _u
}

// SetNillableContentHash sets the "content_hash" field if the given value is not nil.
func (_u *AgentTraceRangeUpdate) SetNillableContentHash(v *string) *AgentTraceRangeUpdate {
	if v != nil {
		_u.SetContentHash(*v)
	}
	return _u
}

// ClearContentHash clears the value of the "content_hash" field.
func (_u *AgentTraceRangeUpdate) ClearContentHash() *AgentTraceRangeUpdate {
	_u.mutation.ClearContentHash()
	return _u
}

// SetContributorType sets the "contributor_type" field.
func (_u *AgentTraceRangeUpdate) SetContributorType(v string) *AgentTraceRangeUpdate {
	_u.mutation.SetContributorType(v)
	return _u
}

// SetNillableContributorType sets the "contributor_type" field if the given value is not nil.
func (_u *AgentTraceRangeUpdate) SetNillableContributorType(v *string) *AgentTraceRangeUpdate {
	if v != nil {
		_u.SetContributorType(*v)
	}
	return _u
}

// ClearContributorType clears the value of the "contributor_type" field.
func (_u *AgentTraceRangeUpdate) ClearContributorType() *AgentTraceRangeUpdate {
	_u.mutation.ClearContributorType()
	return _u
}

// SetContributorModelID sets the "contributor_model_id" field.
func (_u *AgentTraceRangeUpdate) SetContributorModelID(v string) *AgentTraceRangeUpdate {
	_u.mutation.SetContributorModelID(v)
	return _u
}

// SetNillableContributorModelID sets the "contributor_model_id" field if the given value is not nil.
func (_u *AgentTraceRangeUpdate) SetNillableContributorModelID(v *string) *AgentTraceRangeUpdate {
	if v != nil {
		_u.SetContributorModelID(*v)
	}
	return _u
}

// ClearContributorModelID clears the value of the "contributor_model_id" field.
func (_u *AgentTraceRangeUpdate) ClearContributorModelID() *AgentTraceRangeUpdate {
	_u.mutation.ClearContributorModelID()
	return _u
}

// SetConversationID sets the "conversation" edge to the AgentTraceConversation entity by ID.
func (_u *AgentTraceRangeUpdate) SetConversationID(id int) *AgentTraceRangeUpdate {
	_u.mutation.SetConversationID(id)
	return _u
}

// SetConversation sets the "conversation" edge to the AgentTraceConversation entity.
func (_u *AgentTraceRangeUpdate) SetConversation(v *AgentTraceConversation) *AgentTraceRangeUpdate {
	return _u.SetConversationID(v.ID)
}

// Mutation returns the AgentTraceRangeMutation object of the builder.
func (_u *AgentTraceRangeUpdate) Mutation() *AgentTraceRangeMutation {
	return _u.mutation
}

// ClearConversation clears the "conversation" edge to the AgentTraceConversation entity.
func (_u *AgentTraceRangeUpdate) ClearConversation() *AgentTraceRangeUpdate {
	_u.mutation.ClearConversation()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AgentTraceRangeUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AgentTraceRangeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AgentTraceRangeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AgentTraceRangeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AgentTraceRangeUpdate) check() error {
	if _u.mutation.ConversationCleared() && len(_u.mutation.ConversationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AgentTraceRange.conversation"`)
	}
	return nil
}

func (_u *AgentTraceRangeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(agenttracerange.Table, agenttracerange.Columns, sqlgraph.NewFieldSpec(agenttracerange.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.StartLine(); ok {
		_spec.SetField(agenttracerange.FieldStartLine, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStartLine(); ok {
		_spec.AddField(agenttracerange.FieldStartLine, field.TypeInt, value)
	}
	if value, ok := _u.mutation.EndLine(); ok {
		_spec.SetField(agenttracerange.FieldEndLine, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedEndLine(); ok {
		_spec.AddField(agenttracerange.FieldEndLine, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ContentHash(); ok {
		_spec.SetField(agenttracerange.FieldContentHash, field.TypeString, value)
	}
	if _u.mutation.ContentHashCleared() {
		_spec.ClearField(agenttracerange.FieldContentHash, field.TypeString)
	}
	if value, ok := _u.mutation.ContributorType(); ok {
		_spec.SetField(agenttracerange.FieldContributorType, field.TypeString, value)
	}
	if _u.mutation.ContributorTypeCleared() {
		_spec.ClearField(agenttracerange.FieldContributorType, field.TypeString)
	}
	if value, ok := _u.mutation.ContributorModelID(); ok {
		_spec.SetField(agenttracerange.FieldContributorModelID, field.TypeString, value)
	}
	if _u.mutation.ContributorModelIDCleared() {
		_spec.ClearField(agenttracerange.FieldContributorModelID, field.TypeString)
	}
	if _u.mutation.ConversationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agenttracerange.ConversationTable,
			Columns: []string{agenttracerange.ConversationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agenttraceconversation.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ConversationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agenttracerange.ConversationTable,
			Columns: []string{agenttracerange.ConversationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agenttraceconversation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{agenttracerange.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AgentTraceRangeUpdateOne is the builder for updating a single AgentTraceRange entity.
type AgentTraceRangeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AgentTraceRangeMutation
}

// SetStartLine sets the "start_line" field.
func (_u *AgentTraceRangeUpdateOne) SetStartLine(v int) *AgentTraceRangeUpdateOne {
	_u.mutation.ResetStartLine()
	_u.mutation.SetStartLine(v)
	return _u
}

// SetNillableStartLine sets the "start_line" field if the given value is not nil.
func (_u *AgentTraceRangeUpdateOne) SetNillableStartLine(v *int) *AgentTraceRangeUpdateOne {
	if v != nil {
		_u.SetStartLine(*v)
	}
	return _u
}

// AddStartLine adds value to the "start_line" field.
func (_u *AgentTraceRangeUpdateOne) AddStartLine(v int) *AgentTraceRangeUpdateOne {
	_u.mutation.AddStartLine(v)
	return _u
}

// SetEndLine sets the "end_line" field.
func (_u *AgentTraceRangeUpdateOne) SetEndLine(v int) *AgentTraceRangeUpdateOne {
	_u.mutation.ResetEndLine()
	_u.mutation.SetEndLine(v)
	return _u
}

// SetNillableEndLine sets the "end_line" field if the given value is not nil.
func (_u *AgentTraceRangeUpdateOne) SetNillableEndLine(v *int) *AgentTraceRangeUpdateOne {
	if v != nil {
		_u.SetEndLine(*v)
	}
	return _u
}

// AddEndLine adds value to the "end_line" field.
func (_u *AgentTraceRangeUpdateOne) AddEndLine(v int) *AgentTraceRangeUpdateOne {
	_u.mutation.AddEndLine(v)
	return _u
}

// SetContentHash sets the "content_hash" field.
func (_u *AgentTraceRangeUpdateOne) SetContentHash(v string) *AgentTraceRangeUpdateOne {
	_u.mutation.SetContentHash(v)
	return _u
}

// SetNillableContentHash sets the "content_hash" field if the given value is not nil.
func (_u *AgentTraceRangeUpdateOne) SetNillableContentHash(v *string) *AgentTraceRangeUpdateOne {
	if v != nil {
		_u.SetContentHash(*v)
	}
	return _u
}

// ClearContentHash clears the value of the "content_hash" field.
func (_u *AgentTraceRangeUpdateOne) ClearContentHash() *AgentTraceRangeUpdateOne {
	_u.mutation.ClearContentHash()
	return _u
}

// SetContributorType sets the "contributor_type" field.
func (_u *AgentTraceRangeUpdateOne) SetContributorType(v string) *AgentTraceRangeUpdateOne {
	_u.mutation.SetContributorType(v)
	return _u
}

// SetNillableContributorType sets the "contributor_type" field if the given value is not nil.
func (_u *AgentTraceRangeUpdateOne) SetNillableContributorType(v *string) *AgentTraceRangeUpdateOne {
	if v != nil {
		_u.SetContributorType(*v)
	}
	return _u
}

// ClearContributorType clears the value of the "contributor_type" field.
func (_u *AgentTraceRangeUpdateOne) ClearContributorType() *AgentTraceRangeUpdateOne {
	_u.mutation.ClearContributorType()
	return _u
}

// SetContributorModelID sets the "contributor_model_id" field.
func (_u *AgentTraceRangeUpdateOne) SetContributorModelID(v string) *AgentTraceRangeUpdateOne {
	_u.mutation.SetContributorModelID(v)
	return _u
}

// SetNillableContributorModelID sets the "contributor_model_id" field if the given value is not nil.
func (_u *AgentTraceRangeUpdateOne) SetNillableContributorModelID(v *string) *AgentTraceRangeUpdateOne {
	if v != nil {
		_u.SetContributorModelID(*v)
	}
	return _u
}

// ClearContributorModelID clears the value of the "contributor_model_id" field.
func (_u *AgentTraceRangeUpdateOne) ClearContributorModelID() *AgentTraceRangeUpdateOne {
	_u.mutation.ClearContributorModelID()
	return _u
}

// SetConversationID sets the "conversation" edge to the AgentTraceConversation entity by ID.
func (_u *AgentTraceRangeUpdateOne) SetConversationID(id int) *AgentTraceRangeUpdateOne {
	_u.mutation.SetConversationID(id)
	return _u
}

// SetConversation sets the "conversation" edge to the AgentTraceConversation entity.
func (_u *AgentTraceRangeUpdateOne) SetConversation(v *AgentTraceConversation) *AgentTraceRangeUpdateOne {
	return _u.SetConversationID(v.ID)
}

// Mutation returns the AgentTraceRangeMutation object of the builder.
func (_u *AgentTraceRangeUpdateOne) Mutation() *AgentTraceRangeMutation {
	return _u.mutation
}

// ClearConversation clears the "conversation" edge to the AgentTraceConversation entity.
func (_u *AgentTraceRangeUpdateOne) ClearConversation() *AgentTraceRangeUpdateOne {
	_u.mutation.ClearConversation()
	return _u
}

// Where appends a list predicates to the AgentTraceRangeUpdate builder.
func (_u *AgentTraceRangeUpdateOne) Where(ps ...predicate.AgentTraceRange) *AgentTraceRangeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AgentTraceRangeUpdateOne) Select(field string, fields ...string) *AgentTraceRangeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AgentTraceRange entity.
func (_u *AgentTraceRangeUpdateOne) Save(ctx context.Context) (*AgentTraceRange, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AgentTraceRangeUpdateOne) SaveX(ctx context.Context) *AgentTraceRange {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AgentTraceRangeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AgentTraceRangeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AgentTraceRangeUpdateOne) check() error {
	if _u.mutation.ConversationCleared() && len(_u.mutation.ConversationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AgentTraceRange.conversation"`)
	}
	return nil
}

func (_u *AgentTraceRangeUpdateOne) sqlSave(ctx context.Context) (_node *AgentTraceRange, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(agenttracerange.Table, agenttracerange.Columns, sqlgraph.NewFieldSpec(agenttracerange.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AgentTraceRange.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, agenttracerange.FieldID)
		for _, f := range fields {
			if !agenttracerange.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != agenttracerange.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.StartLine(); ok {
		_spec.SetField(agenttracerange.FieldStartLine, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStartLine(); ok {
		_spec.AddField(agenttracerange.FieldStartLine, field.TypeInt, value)
	}
	if value, ok := _u.mutation.EndLine(); ok {
		_spec.SetField(agenttracerange.FieldEndLine, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedEndLine(); ok {
		_spec.AddField(agenttracerange.FieldEndLine, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ContentHash(); ok {
		_spec.SetField(agenttracerange.FieldContentHash, field.TypeString, value)
	}
	if _u.mutation.ContentHashCleared() {
		_spec.ClearField(agenttracerange.FieldContentHash, field.TypeString)
	}
	if value, ok := _u.mutation.ContributorType(); ok {
		_spec.SetField(agenttracerange.FieldContributorType, field.TypeString, value)
	}
	if _u.mutation.ContributorTypeCleared() {
		_spec.ClearField(agenttracerange.FieldContributorType, field.TypeString)
	}
	if value, ok := _u.mutation.ContributorModelID(); ok {
		_spec.SetField(agenttracerange.FieldContributorModelID, field.TypeString, value)
	}
	if _u.mutation.ContributorModelIDCleared() {
		_spec.ClearField(agenttracerange.FieldContributorModelID, field.TypeString)
	}
	if _u.mutation.ConversationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agenttracerange.ConversationTable,
			Columns: []string{agenttracerange.ConversationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agenttraceconversation.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ConversationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agenttracerange.ConversationTable,
			Columns: []string{agenttracerange.ConversationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agenttraceconversation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &AgentTraceRange{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{agenttracerange.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
