// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/papercomputeco/tapes/pkg/storage/ent/agenttraceconversation"
	"github.com/papercomputeco/tapes/pkg/storage/ent/agenttracefile"
	"github.com/papercomputeco/tapes/pkg/storage/ent/agenttracerange"
	"github.com/papercomputeco/tapes/pkg/storage/ent/predicate"
)

// AgentTraceConversationUpdate is the builder for updating AgentTraceConversation entities.
type AgentTraceConversationUpdate struct {
	config
	hooks    []Hook
	mutation *AgentTraceConversationMutation
}

// Where appends a list predicates to the AgentTraceConversationUpdate builder.
func (_u *AgentTraceConversationUpdate) Where(ps ...predicate.AgentTraceConversation) *AgentTraceConversationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetURL sets the "url" field.
func (_u *AgentTraceConversationUpdate) SetURL(v string) *AgentTraceConversationUpdate {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *AgentTraceConversationUpdate) SetNillableURL(v *string) *AgentTraceConversationUpdate {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// ClearURL clears the value of the "url" field.
func (_u *AgentTraceConversationUpdate) ClearURL() *AgentTraceConversationUpdate {
	_u.mutation.ClearURL()
	return _u
}

// SetContributorType sets the "contributor_type" field.
func (_u *AgentTraceConversationUpdate) SetContributorType(v string) *AgentTraceConversationUpdate {
	_u.mutation.SetContributorType(v)
	return _u
}

// SetNillableContributorType sets the "contributor_type" field if the given value is not nil.
func (_u *AgentTraceConversationUpdate) SetNillableContributorType(v *string) *AgentTraceConversationUpdate {
	if v != nil {
		_u.SetContributorType(*v)
	}
	return _u
}

// ClearContributorType clears the value of the "contributor_type" field.
func (_u *AgentTraceConversationUpdate) ClearContributorType() *AgentTraceConversationUpdate {
	_u.mutation.ClearContributorType()
	return _u
}

// SetContributorModelID sets the "contributor_model_id" field.
func (_u *AgentTraceConversationUpdate) SetContributorModelID(v string) *AgentTraceConversationUpdate {
	_u.mutation.SetContributorModelID(v)
	return _u
}

// SetNillableContributorModelID sets the "contributor_model_id" field if the given value is not nil.
func (_u *AgentTraceConversationUpdate) SetNillableContributorModelID(v *string) *AgentTraceConversationUpdate {
	if v != nil {
		_u.SetContributorModelID(*v)
	}
	return _u
}

// ClearContributorModelID clears the value of the "contributor_model_id" field.
func (_u *AgentTraceConversationUpdate) ClearContributorModelID() *AgentTraceConversationUpdate {
	_u.mutation.ClearContributorModelID()
	return _u
}

// SetRelated sets the "related" field.
func (_u *AgentTraceConversationUpdate) SetRelated(v []map[string]interface{}) *AgentTraceConversationUpdate {
	_u.mutation.SetRelated(v)
	return _u
}

// AppendRelated appends value to the "related" field.
func (_u *AgentTraceConversationUpdate) AppendRelated(v []map[string]interface{}) *AgentTraceConversationUpdate {
	_u.mutation.AppendRelated(v)
	return _u
}

// ClearRelated clears the value of the "related" field.
func (_u *AgentTraceConversationUpdate) ClearRelated() *AgentTraceConversationUpdate {
	_u.mutation.ClearRelated()
	return _u
}

// SetFileID sets the "file" edge to the AgentTraceFile entity by ID.
func (_u *AgentTraceConversationUpdate) SetFileID(id int) *AgentTraceConversationUpdate {
	_u.mutation.SetFileID(id)
	return _u
}

// SetFile sets the "file" edge to the AgentTraceFile entity.
func (_u *AgentTraceConversationUpdate) SetFile(v *AgentTraceFile) *AgentTraceConversationUpdate {
	return _u.SetFileID(v.ID)
}

// AddRangeIDs adds the "ranges" edge to the AgentTraceRange entity by IDs.
func (_u *AgentTraceConversationUpdate) AddRangeIDs(ids ...int) *AgentTraceConversationUpdate {
	_u.mutation.AddRangeIDs(ids...)
	return _u
}

// AddRanges adds the "ranges" edges to the AgentTraceRange entity.
func (_u *AgentTraceConversationUpdate) AddRanges(v ...*AgentTraceRange) *AgentTraceConversationUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRangeIDs(ids...)
}

// Mutation returns the AgentTraceConversationMutation object of the builder.
func (_u *AgentTraceConversationUpdate) Mutation() *AgentTraceConversationMutation {
	return _u.mutation
}

// ClearFile clears the "file" edge to the AgentTraceFile entity.
func (_u *AgentTraceConversationUpdate) ClearFile() *AgentTraceConversationUpdate {
	_u.mutation.ClearFile()
	return _u
}

// ClearRanges clears all "ranges" edges to the AgentTraceRange entity.
func (_u *AgentTraceConversationUpdate) ClearRanges() *AgentTraceConversationUpdate {
	_u.mutation.ClearRanges()
	return _u
}

// RemoveRangeIDs removes the "ranges" edge to AgentTraceRange entities by IDs.
func (_u *AgentTraceConversationUpdate) RemoveRangeIDs(ids ...int) *AgentTraceConversationUpdate {
	_u.mutation.RemoveRangeIDs(ids...)
	return _u
}

// RemoveRanges removes "ranges" edges to AgentTraceRange entities.
func (_u *AgentTraceConversationUpdate) RemoveRanges(v ...*AgentTraceRange) *AgentTraceConversationUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRangeIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AgentTraceConversationUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AgentTraceConversationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AgentTraceConversationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AgentTraceConversationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AgentTraceConversationUpdate) check() error {
	if _u.mutation.FileCleared() && len(_u.mutation.FileIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AgentTraceConversation.file"`)
	}
	return nil
}

func (_u *AgentTraceConversationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(agenttraceconversation.Table, agenttraceconversation.Columns, sqlgraph.NewFieldSpec(agenttraceconversation.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(agenttraceconversation.FieldURL, field.TypeString, value)
	}
	if _u.mutation.URLCleared() {
		_spec.ClearField(agenttraceconversation.FieldURL, field.TypeString)
	}
	if value, ok := _u.mutation.ContributorType(); ok {
		_spec.SetField(agenttraceconversation.FieldContributorType, field.TypeString, value)
	}
	if _u.mutation.ContributorTypeCleared() {
		_spec.ClearField(agenttraceconversation.FieldContributorType, field.TypeString)
	}
	if value, ok := _u.mutation.ContributorModelID(); ok {
		_spec.SetField(agenttraceconversation.FieldContributorModelID, field.TypeString, value)
	}
	if _u.mutation.ContributorModelIDCleared() {
		_spec.ClearField(agenttraceconversation.FieldContributorModelID, field.TypeString)
	}
	if value, ok := _u.mutation.Related(); ok {
		_spec.SetField(agenttraceconversation.FieldRelated, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedRelated(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, agenttraceconversation.FieldRelated, value)
		})
	}
	if _u.mutation.RelatedCleared() {
		_spec.ClearField(agenttraceconversation.FieldRelated, field.TypeJSON)
	}
	if _u.mutation.FileCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agenttraceconversation.FileTable,
			Columns: []string{agenttraceconversation.FileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agenttracefile.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FileIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agenttraceconversation.FileTable,
			Columns: []string{agenttraceconversation.FileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agenttracefile.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RangesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agenttraceconversation.RangesTable,
			Columns: []string{agenttraceconversation.RangesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agenttracerange.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRangesIDs(); len(nodes) > 0 && !_u.mutation.RangesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agenttraceconversation.RangesTable,
			Columns: []string{agenttraceconversation.RangesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agenttracerange.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RangesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agenttraceconversation.RangesTable,
			Columns: []string{agenttraceconversation.RangesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agenttracerange.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{agenttraceconversation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AgentTraceConversationUpdateOne is the builder for updating a single AgentTraceConversation entity.
type AgentTraceConversationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AgentTraceConversationMutation
}

// SetURL sets the "url" field.
func (_u *AgentTraceConversationUpdateOne) SetURL(v string) *AgentTraceConversationUpdateOne {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *AgentTraceConversationUpdateOne) SetNillableURL(v *string) *AgentTraceConversationUpdateOne {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// ClearURL clears the value of the "url" field.
func (_u *AgentTraceConversationUpdateOne) ClearURL() *AgentTraceConversationUpdateOne {
	_u.mutation.ClearURL()
	return _u
}

// SetContributorType sets the "contributor_type" field.
func (_u *AgentTraceConversationUpdateOne) SetContributorType(v string) *AgentTraceConversationUpdateOne {
	_u.mutation.SetContributorType(v)
	return _u
}

// SetNillableContributorType sets the "contributor_type" field if the given value is not nil.
func (_u *AgentTraceConversationUpdateOne) SetNillableContributorType(v *string) *AgentTraceConversationUpdateOne {
	if v != nil {
		_u.SetContributorType(*v)
	}
	return _u
}

// ClearContributorType clears the value of the "contributor_type" field.
func (_u *AgentTraceConversationUpdateOne) ClearContributorType() *AgentTraceConversationUpdateOne {
	_u.mutation.ClearContributorType()
	return _u
}

// SetContributorModelID sets the "contributor_model_id" field.
func (_u *AgentTraceConversationUpdateOne) SetContributorModelID(v string) *AgentTraceConversationUpdateOne {
	_u.mutation.SetContributorModelID(v)
	return _u
}

// SetNillableContributorModelID sets the "contributor_model_id" field if the given value is not nil.
func (_u *AgentTraceConversationUpdateOne) SetNillableContributorModelID(v *string) *AgentTraceConversationUpdateOne {
	if v != nil {
		_u.SetContributorModelID(*v)
	}
	return _u
}

// ClearContributorModelID clears the value of the "contributor_model_id" field.
func (_u *AgentTraceConversationUpdateOne) ClearContributorModelID() *AgentTraceConversationUpdateOne {
	_u.mutation.ClearContributorModelID()
	return _u
}

// SetRelated sets the "related" field.
func (_u *AgentTraceConversationUpdateOne) SetRelated(v []map[string]interface{}) *AgentTraceConversationUpdateOne {
	_u.mutation.SetRelated(v)
	return _u
}

// AppendRelated appends value to the "related" field.
func (_u *AgentTraceConversationUpdateOne) AppendRelated(v []map[string]interface{}) *AgentTraceConversationUpdateOne {
	_u.mutation.AppendRelated(v)
	return _u
}

// ClearRelated clears the value of the "related" field.
func (_u *AgentTraceConversationUpdateOne) ClearRelated() *AgentTraceConversationUpdateOne {
	_u.mutation.ClearRelated()
	return _u
}

// SetFileID sets the "file" edge to the AgentTraceFile entity by ID.
func (_u *AgentTraceConversationUpdateOne) SetFileID(id int) *AgentTraceConversationUpdateOne {
	_u.mutation.SetFileID(id)
	return _u
}

// SetFile sets the "file" edge to the AgentTraceFile entity.
func (_u *AgentTraceConversationUpdateOne) SetFile(v *AgentTraceFile) *AgentTraceConversationUpdateOne {
	return _u.SetFileID(v.ID)
}

// AddRangeIDs adds the "ranges" edge to the AgentTraceRange entity by IDs.
func (_u *AgentTraceConversationUpdateOne) AddRangeIDs(ids ...int) *AgentTraceConversationUpdateOne {
	_u.mutation.AddRangeIDs(ids...)
	return _u
}

// AddRanges adds the "ranges" edges to the AgentTraceRange entity.
func (_u *AgentTraceConversationUpdateOne) AddRanges(v ...*AgentTraceRange) *AgentTraceConversationUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRangeIDs(ids...)
}

// Mutation returns the AgentTraceConversationMutation object of the builder.
func (_u *AgentTraceConversationUpdateOne) Mutation() *AgentTraceConversationMutation {
	return _u.mutation
}

// ClearFile clears the "file" edge to the AgentTraceFile entity.
func (_u *AgentTraceConversationUpdateOne) ClearFile() *AgentTraceConversationUpdateOne {
	_u.mutation.ClearFile()
	return _u
}

// ClearRanges clears all "ranges" edges to the AgentTraceRange entity.
func (_u *AgentTraceConversationUpdateOne) ClearRanges() *AgentTraceConversationUpdateOne {
	_u.mutation.ClearRanges()
	return _u
}

// RemoveRangeIDs removes the "ranges" edge to AgentTraceRange entities by IDs.
func (_u *AgentTraceConversationUpdateOne) RemoveRangeIDs(ids ...int) *AgentTraceConversationUpdateOne {
	_u.mutation.RemoveRangeIDs(ids...)
	return _u
}

// RemoveRanges removes "ranges" edges to AgentTraceRange entities.
func (_u *AgentTraceConversationUpdateOne) RemoveRanges(v ...*AgentTraceRange) *AgentTraceConversationUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRangeIDs(ids...)
}

// Where appends a list predicates to the AgentTraceConversationUpdate builder.
func (_u *AgentTraceConversationUpdateOne) Where(ps ...predicate.AgentTraceConversation) *AgentTraceConversationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AgentTraceConversationUpdateOne) Select(field string, fields ...string) *AgentTraceConversationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AgentTraceConversation entity.
func (_u *AgentTraceConversationUpdateOne) Save(ctx context.Context) (*AgentTraceConversation, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AgentTraceConversationUpdateOne) SaveX(ctx context.Context) *AgentTraceConversation {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AgentTraceConversationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AgentTraceConversationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AgentTraceConversationUpdateOne) check() error {
	if _u.mutation.FileCleared() && len(_u.mutation.FileIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AgentTraceConversation.file"`)
	}
	return nil
}

func (_u *AgentTraceConversationUpdateOne) sqlSave(ctx context.Context) (_node *AgentTraceConversation, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(agenttraceconversation.Table, agenttraceconversation.Columns, sqlgraph.NewFieldSpec(agenttraceconversation.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AgentTraceConversation.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, agenttraceconversation.FieldID)
		for _, f := range fields {
			if !agenttraceconversation.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != agenttraceconversation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(agenttraceconversation.FieldURL, field.TypeString, value)
	}
	if _u.mutation.URLCleared() {
		_spec.ClearField(agenttraceconversation.FieldURL, field.TypeString)
	}
	if value, ok := _u.mutation.ContributorType(); ok {
		_spec.SetField(agenttraceconversation.FieldContributorType, field.TypeString, value)
	}
	if _u.mutation.ContributorTypeCleared() {
		_spec.ClearField(agenttraceconversation.FieldContributorType, field.TypeString)
	}
	if value, ok := _u.mutation.ContributorModelID(); ok {
		_spec.SetField(agenttraceconversation.FieldContributorModelID, field.TypeString, value)
	}
	if _u.mutation.ContributorModelIDCleared() {
		_spec.ClearField(agenttraceconversation.FieldContributorModelID, field.TypeString)
	}
	if value, ok := _u.mutation.Related(); ok {
		_spec.SetField(agenttraceconversation.FieldRelated, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedRelated(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, agenttraceconversation.FieldRelated, value)
		})
	}
	if _u.mutation.RelatedCleared() {
		_spec.ClearField(agenttraceconversation.FieldRelated, field.TypeJSON)
	}
	if _u.mutation.FileCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agenttraceconversation.FileTable,
			Columns: []string{agenttraceconversation.FileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agenttracefile.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FileIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agenttraceconversation.FileTable,
			Columns: []string{agenttraceconversation.FileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agenttracefile.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RangesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agenttraceconversation.RangesTable,
			Columns: []string{agenttraceconversation.RangesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agenttracerange.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRangesIDs(); len(nodes) > 0 && !_u.mutation.RangesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agenttraceconversation.RangesTable,
			Columns: []string{agenttraceconversation.RangesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agenttracerange.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RangesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agenttraceconversation.RangesTable,
			Columns: []string{agenttraceconversation.RangesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agenttracerange.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &AgentTraceConversation{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{agenttraceconversation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
