// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/papercomputeco/tapes/pkg/storage/ent/agenttraceconversation"
	"github.com/papercomputeco/tapes/pkg/storage/ent/agenttracefile"
)

// AgentTraceConversation is the model entity for the AgentTraceConversation schema.
type AgentTraceConversation struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// URL holds the value of the "url" field.
	URL string `json:"url,omitempty"`
	// ContributorType holds the value of the "contributor_type" field.
	ContributorType string `json:"contributor_type,omitempty"`
	// ContributorModelID holds the value of the "contributor_model_id" field.
	ContributorModelID string `json:"contributor_model_id,omitempty"`
	// Related holds the value of the "related" field.
	Related []map[string]interface{} `json:"related,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AgentTraceConversationQuery when eager-loading is set.
	Edges                          AgentTraceConversationEdges `json:"edges"`
	agent_trace_file_conversations *int
	selectValues                   sql.SelectValues
}

// AgentTraceConversationEdges holds the relations/edges for other nodes in the graph.
type AgentTraceConversationEdges struct {
	// File holds the value of the file edge.
	File *AgentTraceFile `json:"file,omitempty"`
	// Ranges holds the value of the ranges edge.
	Ranges []*AgentTraceRange `json:"ranges,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// FileOrErr returns the File value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AgentTraceConversationEdges) FileOrErr() (*AgentTraceFile, error) {
	if e.File != nil {
		return e.File, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: agenttracefile.Label}
	}
	return nil, &NotLoadedError{edge: "file"}
}

// RangesOrErr returns the Ranges value or an error if the edge
// was not loaded in eager-loading.
func (e AgentTraceConversationEdges) RangesOrErr() ([]*AgentTraceRange, error) {
	if e.loadedTypes[1] {
		return e.Ranges, nil
	}
	return nil, &NotLoadedError{edge: "ranges"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AgentTraceConversation) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case agenttraceconversation.FieldRelated:
			values[i] = new([]byte)
		case agenttraceconversation.FieldID:
			values[i] = new(sql.NullInt64)
		case agenttraceconversation.FieldURL, agenttraceconversation.FieldContributorType, agenttraceconversation.FieldContributorModelID:
			values[i] = new(sql.NullString)
		case agenttraceconversation.ForeignKeys[0]: // agent_trace_file_conversations
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AgentTraceConversation fields.
func (_m *AgentTraceConversation) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case agenttraceconversation.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case agenttraceconversation.FieldURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field url", values[i])
			} else if value.Valid {
				_m.URL = value.String
			}
		case agenttraceconversation.FieldContributorType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field contributor_type", values[i])
			} else if value.Valid {
				_m.ContributorType = value.String
			}
		case agenttraceconversation.FieldContributorModelID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field contributor_model_id", values[i])
			} else if value.Valid {
				_m.ContributorModelID = value.String
			}
		case agenttraceconversation.FieldRelated:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field related", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Related); err != nil {
					return fmt.Errorf("unmarshal field related: %w", err)
				}
			}
		case agenttraceconversation.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field agent_trace_file_conversations", value)
			} else if value.Valid {
				_m.agent_trace_file_conversations = new(int)
				*_m.agent_trace_file_conversations = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AgentTraceConversation.
// This includes values selected through modifiers, order, etc.
func (_m *AgentTraceConversation) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryFile queries the "file" edge of the AgentTraceConversation entity.
func (_m *AgentTraceConversation) QueryFile() *AgentTraceFileQuery {
	return NewAgentTraceConversationClient(_m.config).QueryFile(_m)
}

// QueryRanges queries the "ranges" edge of the AgentTraceConversation entity.
func (_m *AgentTraceConversation) QueryRanges() *AgentTraceRangeQuery {
	return NewAgentTraceConversationClient(_m.config).QueryRanges(_m)
}

// Update returns a builder for updating this AgentTraceConversation.
// Note that you need to call AgentTraceConversation.Unwrap() before calling this method if this AgentTraceConversation
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AgentTraceConversation) Update() *AgentTraceConversationUpdateOne {
	return NewAgentTraceConversationClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AgentTraceConversation entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AgentTraceConversation) Unwrap() *AgentTraceConversation {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AgentTraceConversation is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AgentTraceConversation) String() string {
	var builder strings.Builder
	builder.WriteString("AgentTraceConversation(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("url=")
	builder.WriteString(_m.URL)
	builder.WriteString(", ")
	builder.WriteString("contributor_type=")
	builder.WriteString(_m.ContributorType)
	builder.WriteString(", ")
	builder.WriteString("contributor_model_id=")
	builder.WriteString(_m.ContributorModelID)
	builder.WriteString(", ")
	builder.WriteString("related=")
	builder.WriteString(fmt.Sprintf("%v", _m.Related))
	builder.WriteByte(')')
	return builder.String()
}

// AgentTraceConversations is a parsable slice of AgentTraceConversation.
type AgentTraceConversations []*AgentTraceConversation
