// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/papercomputeco/tapes/pkg/storage/ent/agenttrace"
	"github.com/papercomputeco/tapes/pkg/storage/ent/agenttracefile"
	"github.com/papercomputeco/tapes/pkg/storage/ent/predicate"
)

// AgentTraceUpdate is the builder for updating AgentTrace entities.
type AgentTraceUpdate struct {
	config
	hooks    []Hook
	mutation *AgentTraceMutation
}

// Where appends a list predicates to the AgentTraceUpdate builder.
func (_u *AgentTraceUpdate) Where(ps ...predicate.AgentTrace) *AgentTraceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetVersion sets the "version" field.
func (_u *AgentTraceUpdate) SetVersion(v string) *AgentTraceUpdate {
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *AgentTraceUpdate) SetNillableVersion(v *string) *AgentTraceUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// SetTimestamp sets the "timestamp" field.
func (_u *AgentTraceUpdate) SetTimestamp(v string) *AgentTraceUpdate {
	_u.mutation.SetTimestamp(v)
	return _u
}

// SetNillableTimestamp sets the "timestamp" field if the given value is not nil.
func (_u *AgentTraceUpdate) SetNillableTimestamp(v *string) *AgentTraceUpdate {
	if v != nil {
		_u.SetTimestamp(*v)
	}
	return _u
}

// SetVcsType sets the "vcs_type" field.
func (_u *AgentTraceUpdate) SetVcsType(v string) *AgentTraceUpdate {
	_u.mutation.SetVcsType(v)
	return _u
}

// SetNillableVcsType sets the "vcs_type" field if the given value is not nil.
func (_u *AgentTraceUpdate) SetNillableVcsType(v *string) *AgentTraceUpdate {
	if v != nil {
		_u.SetVcsType(*v)
	}
	return _u
}

// ClearVcsType clears the value of the "vcs_type" field.
func (_u *AgentTraceUpdate) ClearVcsType() *AgentTraceUpdate {
	_u.mutation.ClearVcsType()
	return _u
}

// SetVcsRevision sets the "vcs_revision" field.
func (_u *AgentTraceUpdate) SetVcsRevision(v string) *AgentTraceUpdate {
	_u.mutation.SetVcsRevision(v)
	return _u
}

// SetNillableVcsRevision sets the "vcs_revision" field if the given value is not nil.
func (_u *AgentTraceUpdate) SetNillableVcsRevision(v *string) *AgentTraceUpdate {
	if v != nil {
		_u.SetVcsRevision(*v)
	}
	return _u
}

// ClearVcsRevision clears the value of the "vcs_revision" field.
func (_u *AgentTraceUpdate) ClearVcsRevision() *AgentTraceUpdate {
	_u.mutation.ClearVcsRevision()
	return _u
}

// SetToolName sets the "tool_name" field.
func (_u *AgentTraceUpdate) SetToolName(v string) *AgentTraceUpdate {
	_u.mutation.SetToolName(v)
	return _u
}

// SetNillableToolName sets the "tool_name" field if the given value is not nil.
func (_u *AgentTraceUpdate) SetNillableToolName(v *string) *AgentTraceUpdate {
	if v != nil {
		_u.SetToolName(*v)
	}
	return _u
}

// ClearToolName clears the value of the "tool_name" field.
func (_u *AgentTraceUpdate) ClearToolName() *AgentTraceUpdate {
	_u.mutation.ClearToolName()
	return _u
}

// SetToolVersion sets the "tool_version" field.
func (_u *AgentTraceUpdate) SetToolVersion(v string) *AgentTraceUpdate {
	_u.mutation.SetToolVersion(v)
	return _u
}

// SetNillableToolVersion sets the "tool_version" field if the given value is not nil.
func (_u *AgentTraceUpdate) SetNillableToolVersion(v *string) *AgentTraceUpdate {
	if v != nil {
		_u.SetToolVersion(*v)
	}
	return _u
}

// ClearToolVersion clears the value of the "tool_version" field.
func (_u *AgentTraceUpdate) ClearToolVersion() *AgentTraceUpdate {
	_u.mutation.ClearToolVersion()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *AgentTraceUpdate) SetMetadata(v map[string]interface{}) *AgentTraceUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *AgentTraceUpdate) ClearMetadata() *AgentTraceUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// AddFileIDs adds the "files" edge to the AgentTraceFile entity by IDs.
func (_u *AgentTraceUpdate) AddFileIDs(ids ...int) *AgentTraceUpdate {
	_u.mutation.AddFileIDs(ids...)
	return _u
}

// AddFiles adds the "files" edges to the AgentTraceFile entity.
func (_u *AgentTraceUpdate) AddFiles(v ...*AgentTraceFile) *AgentTraceUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddFileIDs(ids...)
}

// Mutation returns the AgentTraceMutation object of the builder.
func (_u *AgentTraceUpdate) Mutation() *AgentTraceMutation {
	return _u.mutation
}

// ClearFiles clears all "files" edges to the AgentTraceFile entity.
func (_u *AgentTraceUpdate) ClearFiles() *AgentTraceUpdate {
	_u.mutation.ClearFiles()
	return _u
}

// RemoveFileIDs removes the "files" edge to AgentTraceFile entities by IDs.
func (_u *AgentTraceUpdate) RemoveFileIDs(ids ...int) *AgentTraceUpdate {
	_u.mutation.RemoveFileIDs(ids...)
	return _u
}

// RemoveFiles removes "files" edges to AgentTraceFile entities.
func (_u *AgentTraceUpdate) RemoveFiles(v ...*AgentTraceFile) *AgentTraceUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveFileIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AgentTraceUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AgentTraceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AgentTraceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AgentTraceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AgentTraceUpdate) check() error {
	if v, ok := _u.mutation.Version(); ok {
		if err := agenttrace.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "AgentTrace.version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Timestamp(); ok {
		if err := agenttrace.TimestampValidator(v); err != nil {
			return &ValidationError{Name: "timestamp", err: fmt.Errorf(`ent: validator failed for field "AgentTrace.timestamp": %w`, err)}
		}
	}
	return nil
}

func (_u *AgentTraceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(agenttrace.Table, agenttrace.Columns, sqlgraph.NewFieldSpec(agenttrace.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(agenttrace.FieldVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Timestamp(); ok {
		_spec.SetField(agenttrace.FieldTimestamp, field.TypeString, value)
	}
	if value, ok := _u.mutation.VcsType(); ok {
		_spec.SetField(agenttrace.FieldVcsType, field.TypeString, value)
	}
	if _u.mutation.VcsTypeCleared() {
		_spec.ClearField(agenttrace.FieldVcsType, field.TypeString)
	}
	if value, ok := _u.mutation.VcsRevision(); ok {
		_spec.SetField(agenttrace.FieldVcsRevision, field.TypeString, value)
	}
	if _u.mutation.VcsRevisionCleared() {
		_spec.ClearField(agenttrace.FieldVcsRevision, field.TypeString)
	}
	if value, ok := _u.mutation.ToolName(); ok {
		_spec.SetField(agenttrace.FieldToolName, field.TypeString, value)
	}
	if _u.mutation.ToolNameCleared() {
		_spec.ClearField(agenttrace.FieldToolName, field.TypeString)
	}
	if value, ok := _u.mutation.ToolVersion(); ok {
		_spec.SetField(agenttrace.FieldToolVersion, field.TypeString, value)
	}
	if _u.mutation.ToolVersionCleared() {
		_spec.ClearField(agenttrace.FieldToolVersion, field.TypeString)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(agenttrace.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(agenttrace.FieldMetadata, field.TypeJSON)
	}
	if _u.mutation.FilesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agenttrace.FilesTable,
			Columns: []string{agenttrace.FilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agenttracefile.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedFilesIDs(); len(nodes) > 0 && !_u.mutation.FilesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agenttrace.FilesTable,
			Columns: []string{agenttrace.FilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agenttracefile.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FilesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agenttrace.FilesTable,
			Columns: []string{agenttrace.FilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agenttracefile.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{agenttrace.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AgentTraceUpdateOne is the builder for updating a single AgentTrace entity.
type AgentTraceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AgentTraceMutation
}

// SetVersion sets the "version" field.
func (_u *AgentTraceUpdateOne) SetVersion(v string) *AgentTraceUpdateOne {
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *AgentTraceUpdateOne) SetNillableVersion(v *string) *AgentTraceUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// SetTimestamp sets the "timestamp" field.
func (_u *AgentTraceUpdateOne) SetTimestamp(v string) *AgentTraceUpdateOne {
	_u.mutation.SetTimestamp(v)
	return _u
}

// SetNillableTimestamp sets the "timestamp" field if the given value is not nil.
func (_u *AgentTraceUpdateOne) SetNillableTimestamp(v *string) *AgentTraceUpdateOne {
	if v != nil {
		_u.SetTimestamp(*v)
	}
	return _u
}

// SetVcsType sets the "vcs_type" field.
func (_u *AgentTraceUpdateOne) SetVcsType(v string) *AgentTraceUpdateOne {
	_u.mutation.SetVcsType(v)
	return _u
}

// SetNillableVcsType sets the "vcs_type" field if the given value is not nil.
func (_u *AgentTraceUpdateOne) SetNillableVcsType(v *string) *AgentTraceUpdateOne {
	if v != nil {
		_u.SetVcsType(*v)
	}
	return _u
}

// ClearVcsType clears the value of the "vcs_type" field.
func (_u *AgentTraceUpdateOne) ClearVcsType() *AgentTraceUpdateOne {
	_u.mutation.ClearVcsType()
	return _u
}

// SetVcsRevision sets the "vcs_revision" field.
func (_u *AgentTraceUpdateOne) SetVcsRevision(v string) *AgentTraceUpdateOne {
	_u.mutation.SetVcsRevision(v)
	return _u
}

// SetNillableVcsRevision sets the "vcs_revision" field if the given value is not nil.
func (_u *AgentTraceUpdateOne) SetNillableVcsRevision(v *string) *AgentTraceUpdateOne {
	if v != nil {
		_u.SetVcsRevision(*v)
	}
	return _u
}

// ClearVcsRevision clears the value of the "vcs_revision" field.
func (_u *AgentTraceUpdateOne) ClearVcsRevision() *AgentTraceUpdateOne {
	_u.mutation.ClearVcsRevision()
	return _u
}

// SetToolName sets the "tool_name" field.
func (_u *AgentTraceUpdateOne) SetToolName(v string) *AgentTraceUpdateOne {
	_u.mutation.SetToolName(v)
	return _u
}

// SetNillableToolName sets the "tool_name" field if the given value is not nil.
func (_u *AgentTraceUpdateOne) SetNillableToolName(v *string) *AgentTraceUpdateOne {
	if v != nil {
		_u.SetToolName(*v)
	}
	return _u
}

// ClearToolName clears the value of the "tool_name" field.
func (_u *AgentTraceUpdateOne) ClearToolName() *AgentTraceUpdateOne {
	_u.mutation.ClearToolName()
	return _u
}

// SetToolVersion sets the "tool_version" field.
func (_u *AgentTraceUpdateOne) SetToolVersion(v string) *AgentTraceUpdateOne {
	_u.mutation.SetToolVersion(v)
	return _u
}

// SetNillableToolVersion sets the "tool_version" field if the given value is not nil.
func (_u *AgentTraceUpdateOne) SetNillableToolVersion(v *string) *AgentTraceUpdateOne {
	if v != nil {
		_u.SetToolVersion(*v)
	}
	return _u
}

// ClearToolVersion clears the value of the "tool_version" field.
func (_u *AgentTraceUpdateOne) ClearToolVersion() *AgentTraceUpdateOne {
	_u.mutation.ClearToolVersion()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *AgentTraceUpdateOne) SetMetadata(v map[string]interface{}) *AgentTraceUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *AgentTraceUpdateOne) ClearMetadata() *AgentTraceUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// AddFileIDs adds the "files" edge to the AgentTraceFile entity by IDs.
func (_u *AgentTraceUpdateOne) AddFileIDs(ids ...int) *AgentTraceUpdateOne {
	_u.mutation.AddFileIDs(ids...)
	return _u
}

// AddFiles adds the "files" edges to the AgentTraceFile entity.
func (_u *AgentTraceUpdateOne) AddFiles(v ...*AgentTraceFile) *AgentTraceUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddFileIDs(ids...)
}

// Mutation returns the AgentTraceMutation object of the builder.
func (_u *AgentTraceUpdateOne) Mutation() *AgentTraceMutation {
	return _u.mutation
}

// ClearFiles clears all "files" edges to the AgentTraceFile entity.
func (_u *AgentTraceUpdateOne) ClearFiles() *AgentTraceUpdateOne {
	_u.mutation.ClearFiles()
	return _u
}

// RemoveFileIDs removes the "files" edge to AgentTraceFile entities by IDs.
func (_u *AgentTraceUpdateOne) RemoveFileIDs(ids ...int) *AgentTraceUpdateOne {
	_u.mutation.RemoveFileIDs(ids...)
	return _u
}

// RemoveFiles removes "files" edges to AgentTraceFile entities.
func (_u *AgentTraceUpdateOne) RemoveFiles(v ...*AgentTraceFile) *AgentTraceUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveFileIDs(ids...)
}

// Where appends a list predicates to the AgentTraceUpdate builder.
func (_u *AgentTraceUpdateOne) Where(ps ...predicate.AgentTrace) *AgentTraceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AgentTraceUpdateOne) Select(field string, fields ...string) *AgentTraceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AgentTrace entity.
func (_u *AgentTraceUpdateOne) Save(ctx context.Context) (*AgentTrace, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AgentTraceUpdateOne) SaveX(ctx context.Context) *AgentTrace {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AgentTraceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AgentTraceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AgentTraceUpdateOne) check() error {
	if v, ok := _u.mutation.Version(); ok {
		if err := agenttrace.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "AgentTrace.version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Timestamp(); ok {
		if err := agenttrace.TimestampValidator(v); err != nil {
			return &ValidationError{Name: "timestamp", err: fmt.Errorf(`ent: validator failed for field "AgentTrace.timestamp": %w`, err)}
		}
	}
	return nil
}

func (_u *AgentTraceUpdateOne) sqlSave(ctx context.Context) (_node *AgentTrace, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(agenttrace.Table, agenttrace.Columns, sqlgraph.NewFieldSpec(agenttrace.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AgentTrace.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, agenttrace.FieldID)
		for _, f := range fields {
			if !agenttrace.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != agenttrace.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(agenttrace.FieldVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Timestamp(); ok {
		_spec.SetField(agenttrace.FieldTimestamp, field.TypeString, value)
	}
	if value, ok := _u.mutation.VcsType(); ok {
		_spec.SetField(agenttrace.FieldVcsType, field.TypeString, value)
	}
	if _u.mutation.VcsTypeCleared() {
		_spec.ClearField(agenttrace.FieldVcsType, field.TypeString)
	}
	if value, ok := _u.mutation.VcsRevision(); ok {
		_spec.SetField(agenttrace.FieldVcsRevision, field.TypeString, value)
	}
	if _u.mutation.VcsRevisionCleared() {
		_spec.ClearField(agenttrace.FieldVcsRevision, field.TypeString)
	}
	if value, ok := _u.mutation.ToolName(); ok {
		_spec.SetField(agenttrace.FieldToolName, field.TypeString, value)
	}
	if _u.mutation.ToolNameCleared() {
		_spec.ClearField(agenttrace.FieldToolName, field.TypeString)
	}
	if value, ok := _u.mutation.ToolVersion(); ok {
		_spec.SetField(agenttrace.FieldToolVersion, field.TypeString, value)
	}
	if _u.mutation.ToolVersionCleared() {
		_spec.ClearField(agenttrace.FieldToolVersion, field.TypeString)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(agenttrace.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(agenttrace.FieldMetadata, field.TypeJSON)
	}
	if _u.mutation.FilesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agenttrace.FilesTable,
			Columns: []string{agenttrace.FilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agenttracefile.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedFilesIDs(); len(nodes) > 0 && !_u.mutation.FilesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agenttrace.FilesTable,
			Columns: []string{agenttrace.FilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agenttracefile.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FilesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agenttrace.FilesTable,
			Columns: []string{agenttrace.FilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agenttracefile.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &AgentTrace{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{agenttrace.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
