// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/papercomputeco/tapes/pkg/storage/ent/agenttraceconversation"
	"github.com/papercomputeco/tapes/pkg/storage/ent/agenttracerange"
)

// AgentTraceRange is the model entity for the AgentTraceRange schema.
type AgentTraceRange struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// StartLine holds the value of the "start_line" field.
	StartLine int `json:"start_line,omitempty"`
	// EndLine holds the value of the "end_line" field.
	EndLine int `json:"end_line,omitempty"`
	// ContentHash holds the value of the "content_hash" field.
	ContentHash string `json:"content_hash,omitempty"`
	// ContributorType holds the value of the "contributor_type" field.
	ContributorType string `json:"contributor_type,omitempty"`
	// ContributorModelID holds the value of the "contributor_model_id" field.
	ContributorModelID string `json:"contributor_model_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AgentTraceRangeQuery when eager-loading is set.
	Edges                           AgentTraceRangeEdges `json:"edges"`
	agent_trace_conversation_ranges *int
	selectValues                    sql.SelectValues
}

// AgentTraceRangeEdges holds the relations/edges for other nodes in the graph.
type AgentTraceRangeEdges struct {
	// Conversation holds the value of the conversation edge.
	Conversation *AgentTraceConversation `json:"conversation,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ConversationOrErr returns the Conversation value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AgentTraceRangeEdges) ConversationOrErr() (*AgentTraceConversation, error) {
	if e.Conversation != nil {
		return e.Conversation, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: agenttraceconversation.Label}
	}
	return nil, &NotLoadedError{edge: "conversation"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AgentTraceRange) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case agenttracerange.FieldID, agenttracerange.FieldStartLine, agenttracerange.FieldEndLine:
			values[i] = new(sql.NullInt64)
		case agenttracerange.FieldContentHash, agenttracerange.FieldContributorType, agenttracerange.FieldContributorModelID:
			values[i] = new(sql.NullString)
		case agenttracerange.ForeignKeys[0]: // agent_trace_conversation_ranges
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AgentTraceRange fields.
func (_m *AgentTraceRange) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case agenttracerange.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case agenttracerange.FieldStartLine:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field start_line", values[i])
			} else if value.Valid {
				_m.StartLine = int(value.Int64)
			}
		case agenttracerange.FieldEndLine:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field end_line", values[i])
			} else if value.Valid {
				_m.EndLine = int(value.Int64)
			}
		case agenttracerange.FieldContentHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content_hash", values[i])
			} else if value.Valid {
				_m.ContentHash = value.String
			}
		case agenttracerange.FieldContributorType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field contributor_type", values[i])
			} else if value.Valid {
				_m.ContributorType = value.String
			}
		case agenttracerange.FieldContributorModelID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field contributor_model_id", values[i])
			} else if value.Valid {
				_m.ContributorModelID = value.String
			}
		case agenttracerange.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field agent_trace_conversation_ranges", value)
			} else if value.Valid {
				_m.agent_trace_conversation_ranges = new(int)
				*_m.agent_trace_conversation_ranges = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AgentTraceRange.
// This includes values selected through modifiers, order, etc.
func (_m *AgentTraceRange) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryConversation queries the "conversation" edge of the AgentTraceRange entity.
func (_m *AgentTraceRange) QueryConversation() *AgentTraceConversationQuery {
	return NewAgentTraceRangeClient(_m.config).QueryConversation(_m)
}

// Update returns a builder for updating this AgentTraceRange.
// Note that you need to call AgentTraceRange.Unwrap() before calling this method if this AgentTraceRange
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AgentTraceRange) Update() *AgentTraceRangeUpdateOne {
	return NewAgentTraceRangeClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AgentTraceRange entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AgentTraceRange) Unwrap() *AgentTraceRange {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AgentTraceRange is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AgentTraceRange) String() string {
	var builder strings.Builder
	builder.WriteString("AgentTraceRange(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("start_line=")
	builder.WriteString(fmt.Sprintf("%v", _m.StartLine))
	builder.WriteString(", ")
	builder.WriteString("end_line=")
	builder.WriteString(fmt.Sprintf("%v", _m.EndLine))
	builder.WriteString(", ")
	builder.WriteString("content_hash=")
	builder.WriteString(_m.ContentHash)
	builder.WriteString(", ")
	builder.WriteString("contributor_type=")
	builder.WriteString(_m.ContributorType)
	builder.WriteString(", ")
	builder.WriteString("contributor_model_id=")
	builder.WriteString(_m.ContributorModelID)
	builder.WriteByte(')')
	return builder.String()
}

// AgentTraceRanges is a parsable slice of AgentTraceRange.
type AgentTraceRanges []*AgentTraceRange
