// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/papercomputeco/tapes/pkg/storage/ent/node"
)

// Node is the model entity for the Node schema.
type Node struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// ParentHash holds the value of the "parent_hash" field.
	ParentHash *string `json:"parent_hash,omitempty"`
	// Bucket holds the value of the "bucket" field.
	Bucket map[string]interface{} `json:"bucket,omitempty"`
	// Type holds the value of the "type" field.
	Type string `json:"type,omitempty"`
	// Role holds the value of the "role" field.
	Role string `json:"role,omitempty"`
	// Content holds the value of the "content" field.
	Content []map[string]interface{} `json:"content,omitempty"`
	// Model holds the value of the "model" field.
	Model string `json:"model,omitempty"`
	// Provider holds the value of the "provider" field.
	Provider string `json:"provider,omitempty"`
	// AgentName holds the value of the "agent_name" field.
	AgentName string `json:"agent_name,omitempty"`
	// StopReason holds the value of the "stop_reason" field.
	StopReason string `json:"stop_reason,omitempty"`
	// PromptTokens holds the value of the "prompt_tokens" field.
	PromptTokens *int `json:"prompt_tokens,omitempty"`
	// CompletionTokens holds the value of the "completion_tokens" field.
	CompletionTokens *int `json:"completion_tokens,omitempty"`
	// TotalTokens holds the value of the "total_tokens" field.
	TotalTokens *int `json:"total_tokens,omitempty"`
	// TotalDurationNs holds the value of the "total_duration_ns" field.
	TotalDurationNs *int64 `json:"total_duration_ns,omitempty"`
	// PromptDurationNs holds the value of the "prompt_duration_ns" field.
	PromptDurationNs *int64 `json:"prompt_duration_ns,omitempty"`
	// Project holds the value of the "project" field.
	Project *string `json:"project,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the NodeQuery when eager-loading is set.
	Edges        NodeEdges `json:"edges"`
	selectValues sql.SelectValues
}

// NodeEdges holds the relations/edges for other nodes in the graph.
type NodeEdges struct {
	// Parent holds the value of the parent edge.
	Parent *Node `json:"parent,omitempty"`
	// Children holds the value of the children edge.
	Children []*Node `json:"children,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ParentOrErr returns the Parent value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e NodeEdges) ParentOrErr() (*Node, error) {
	if e.Parent != nil {
		return e.Parent, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: node.Label}
	}
	return nil, &NotLoadedError{edge: "parent"}
}

// ChildrenOrErr returns the Children value or an error if the edge
// was not loaded in eager-loading.
func (e NodeEdges) ChildrenOrErr() ([]*Node, error) {
	if e.loadedTypes[1] {
		return e.Children, nil
	}
	return nil, &NotLoadedError{edge: "children"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Node) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case node.FieldBucket, node.FieldContent:
			values[i] = new([]byte)
		case node.FieldPromptTokens, node.FieldCompletionTokens, node.FieldTotalTokens, node.FieldTotalDurationNs, node.FieldPromptDurationNs:
			values[i] = new(sql.NullInt64)
		case node.FieldID, node.FieldParentHash, node.FieldType, node.FieldRole, node.FieldModel, node.FieldProvider, node.FieldAgentName, node.FieldStopReason, node.FieldProject:
			values[i] = new(sql.NullString)
		case node.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Node fields.
func (_m *Node) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case node.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case node.FieldParentHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field parent_hash", values[i])
			} else if value.Valid {
				_m.ParentHash = new(string)
				*_m.ParentHash = value.String
			}
		case node.FieldBucket:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field bucket", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Bucket); err != nil {
					return fmt.Errorf("unmarshal field bucket: %w", err)
				}
			}
		case node.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = value.String
			}
		case node.FieldRole:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field role", values[i])
			} else if value.Valid {
				_m.Role = value.String
			}
		case node.FieldContent:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field content", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Content); err != nil {
					return fmt.Errorf("unmarshal field content: %w", err)
				}
			}
		case node.FieldModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model", values[i])
			} else if value.Valid {
				_m.Model = value.String
			}
		case node.FieldProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider", values[i])
			} else if value.Valid {
				_m.Provider = value.String
			}
		case node.FieldAgentName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field agent_name", values[i])
			} else if value.Valid {
				_m.AgentName = value.String
			}
		case node.FieldStopReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field stop_reason", values[i])
			} else if value.Valid {
				_m.StopReason = value.String
			}
		case node.FieldPromptTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field prompt_tokens", values[i])
			} else if value.Valid {
				_m.PromptTokens = new(int)
				*_m.PromptTokens = int(value.Int64)
			}
		case node.FieldCompletionTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field completion_tokens", values[i])
			} else if value.Valid {
				_m.CompletionTokens = new(int)
				*_m.CompletionTokens = int(value.Int64)
			}
		case node.FieldTotalTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field total_tokens", values[i])
			} else if value.Valid {
				_m.TotalTokens = new(int)
				*_m.TotalTokens = int(value.Int64)
			}
		case node.FieldTotalDurationNs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field total_duration_ns", values[i])
			} else if value.Valid {
				_m.TotalDurationNs = new(int64)
				*_m.TotalDurationNs = value.Int64
			}
		case node.FieldPromptDurationNs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field prompt_duration_ns", values[i])
			} else if value.Valid {
				_m.PromptDurationNs = new(int64)
				*_m.PromptDurationNs = value.Int64
			}
		case node.FieldProject:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field project", values[i])
			} else if value.Valid {
				_m.Project = new(string)
				*_m.Project = value.String
			}
		case node.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Node.
// This includes values selected through modifiers, order, etc.
func (_m *Node) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryParent queries the "parent" edge of the Node entity.
func (_m *Node) QueryParent() *NodeQuery {
	return NewNodeClient(_m.config).QueryParent(_m)
}

// QueryChildren queries the "children" edge of the Node entity.
func (_m *Node) QueryChildren() *NodeQuery {
	return NewNodeClient(_m.config).QueryChildren(_m)
}

// Update returns a builder for updating this Node.
// Note that you need to call Node.Unwrap() before calling this method if this Node
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Node) Update() *NodeUpdateOne {
	return NewNodeClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Node entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Node) Unwrap() *Node {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Node is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Node) String() string {
	var builder strings.Builder
	builder.WriteString("Node(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.ParentHash; v != nil {
		builder.WriteString("parent_hash=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("bucket=")
	builder.WriteString(fmt.Sprintf("%v", _m.Bucket))
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(_m.Type)
	builder.WriteString(", ")
	builder.WriteString("role=")
	builder.WriteString(_m.Role)
	builder.WriteString(", ")
	builder.WriteString("content=")
	builder.WriteString(fmt.Sprintf("%v", _m.Content))
	builder.WriteString(", ")
	builder.WriteString("model=")
	builder.WriteString(_m.Model)
	builder.WriteString(", ")
	builder.WriteString("provider=")
	builder.WriteString(_m.Provider)
	builder.WriteString(", ")
	builder.WriteString("agent_name=")
	builder.WriteString(_m.AgentName)
	builder.WriteString(", ")
	builder.WriteString("stop_reason=")
	builder.WriteString(_m.StopReason)
	builder.WriteString(", ")
	if v := _m.PromptTokens; v != nil {
		builder.WriteString("prompt_tokens=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.CompletionTokens; v != nil {
		builder.WriteString("completion_tokens=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.TotalTokens; v != nil {
		builder.WriteString("total_tokens=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.TotalDurationNs; v != nil {
		builder.WriteString("total_duration_ns=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.PromptDurationNs; v != nil {
		builder.WriteString("prompt_duration_ns=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Project; v != nil {
		builder.WriteString("project=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Nodes is a parsable slice of Node.
type Nodes []*Node
