// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"

	"github.com/papercomputeco/tapes/pkg/storage/ent/node"
)

// NodeCreate is the builder for creating a Node entity.
type NodeCreate struct {
	config
	mutation *NodeMutation
	hooks    []Hook
}

// SetParentHash sets the "parent_hash" field.
func (_c *NodeCreate) SetParentHash(v string) *NodeCreate {
	_c.mutation.SetParentHash(v)
	return _c
}

// SetNillableParentHash sets the "parent_hash" field if the given value is not nil.
func (_c *NodeCreate) SetNillableParentHash(v *string) *NodeCreate {
	if v != nil {
		_c.SetParentHash(*v)
	}
	return _c
}

// SetBucket sets the "bucket" field.
func (_c *NodeCreate) SetBucket(v map[string]interface{}) *NodeCreate {
	_c.mutation.SetBucket(v)
	return _c
}

// SetType sets the "type" field.
func (_c *NodeCreate) SetType(v string) *NodeCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_c *NodeCreate) SetNillableType(v *string) *NodeCreate {
	if v != nil {
		_c.SetType(*v)
	}
	return _c
}

// SetRole sets the "role" field.
func (_c *NodeCreate) SetRole(v string) *NodeCreate {
	_c.mutation.SetRole(v)
	return _c
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_c *NodeCreate) SetNillableRole(v *string) *NodeCreate {
	if v != nil {
		_c.SetRole(*v)
	}
	return _c
}

// SetContent sets the "content" field.
func (_c *NodeCreate) SetContent(v []map[string]interface{}) *NodeCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetModel sets the "model" field.
func (_c *NodeCreate) SetModel(v string) *NodeCreate {
	_c.mutation.SetModel(v)
	return _c
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_c *NodeCreate) SetNillableModel(v *string) *NodeCreate {
	if v != nil {
		_c.SetModel(*v)
	}
	return _c
}

// SetProvider sets the "provider" field.
func (_c *NodeCreate) SetProvider(v string) *NodeCreate {
	_c.mutation.SetProvider(v)
	return _c
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_c *NodeCreate) SetNillableProvider(v *string) *NodeCreate {
	if v != nil {
		_c.SetProvider(*v)
	}
	return _c
}

// SetStopReason sets the "stop_reason" field.
func (_c *NodeCreate) SetStopReason(v string) *NodeCreate {
	_c.mutation.SetStopReason(v)
	return _c
}

// SetNillableStopReason sets the "stop_reason" field if the given value is not nil.
func (_c *NodeCreate) SetNillableStopReason(v *string) *NodeCreate {
	if v != nil {
		_c.SetStopReason(*v)
	}
	return _c
}

// SetPromptTokens sets the "prompt_tokens" field.
func (_c *NodeCreate) SetPromptTokens(v int) *NodeCreate {
	_c.mutation.SetPromptTokens(v)
	return _c
}

// SetNillablePromptTokens sets the "prompt_tokens" field if the given value is not nil.
func (_c *NodeCreate) SetNillablePromptTokens(v *int) *NodeCreate {
	if v != nil {
		_c.SetPromptTokens(*v)
	}
	return _c
}

// SetCompletionTokens sets the "completion_tokens" field.
func (_c *NodeCreate) SetCompletionTokens(v int) *NodeCreate {
	_c.mutation.SetCompletionTokens(v)
	return _c
}

// SetNillableCompletionTokens sets the "completion_tokens" field if the given value is not nil.
func (_c *NodeCreate) SetNillableCompletionTokens(v *int) *NodeCreate {
	if v != nil {
		_c.SetCompletionTokens(*v)
	}
	return _c
}

// SetTotalTokens sets the "total_tokens" field.
func (_c *NodeCreate) SetTotalTokens(v int) *NodeCreate {
	_c.mutation.SetTotalTokens(v)
	return _c
}

// SetNillableTotalTokens sets the "total_tokens" field if the given value is not nil.
func (_c *NodeCreate) SetNillableTotalTokens(v *int) *NodeCreate {
	if v != nil {
		_c.SetTotalTokens(*v)
	}
	return _c
}

// SetTotalDurationNs sets the "total_duration_ns" field.
func (_c *NodeCreate) SetTotalDurationNs(v int64) *NodeCreate {
	_c.mutation.SetTotalDurationNs(v)
	return _c
}

// SetNillableTotalDurationNs sets the "total_duration_ns" field if the given value is not nil.
func (_c *NodeCreate) SetNillableTotalDurationNs(v *int64) *NodeCreate {
	if v != nil {
		_c.SetTotalDurationNs(*v)
	}
	return _c
}

// SetPromptDurationNs sets the "prompt_duration_ns" field.
func (_c *NodeCreate) SetPromptDurationNs(v int64) *NodeCreate {
	_c.mutation.SetPromptDurationNs(v)
	return _c
}

// SetNillablePromptDurationNs sets the "prompt_duration_ns" field if the given value is not nil.
func (_c *NodeCreate) SetNillablePromptDurationNs(v *int64) *NodeCreate {
	if v != nil {
		_c.SetPromptDurationNs(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *NodeCreate) SetCreatedAt(v time.Time) *NodeCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *NodeCreate) SetNillableCreatedAt(v *time.Time) *NodeCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *NodeCreate) SetID(v string) *NodeCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetParentID sets the "parent" edge to the Node entity by ID.
func (_c *NodeCreate) SetParentID(id string) *NodeCreate {
	_c.mutation.SetParentID(id)
	return _c
}

// SetNillableParentID sets the "parent" edge to the Node entity by ID if the given value is not nil.
func (_c *NodeCreate) SetNillableParentID(id *string) *NodeCreate {
	if id != nil {
		_c = _c.SetParentID(*id)
	}
	return _c
}

// SetParent sets the "parent" edge to the Node entity.
func (_c *NodeCreate) SetParent(v *Node) *NodeCreate {
	return _c.SetParentID(v.ID)
}

// AddChildIDs adds the "children" edge to the Node entity by IDs.
func (_c *NodeCreate) AddChildIDs(ids ...string) *NodeCreate {
	_c.mutation.AddChildIDs(ids...)
	return _c
}

// AddChildren adds the "children" edges to the Node entity.
func (_c *NodeCreate) AddChildren(v ...*Node) *NodeCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddChildIDs(ids...)
}

// Mutation returns the NodeMutation object of the builder.
func (_c *NodeCreate) Mutation() *NodeMutation {
	return _c.mutation
}

// Save creates the Node in the database.
func (_c *NodeCreate) Save(ctx context.Context) (*Node, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *NodeCreate) SaveX(ctx context.Context) *Node {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NodeCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NodeCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *NodeCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := node.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *NodeCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Node.created_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := node.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Node.id": %w`, err)}
		}
	}
	return nil
}

func (_c *NodeCreate) sqlSave(ctx context.Context) (*Node, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Node.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *NodeCreate) createSpec() (*Node, *sqlgraph.CreateSpec) {
	var (
		_node = &Node{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(node.Table, sqlgraph.NewFieldSpec(node.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Bucket(); ok {
		_spec.SetField(node.FieldBucket, field.TypeJSON, value)
		_node.Bucket = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(node.FieldType, field.TypeString, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.Role(); ok {
		_spec.SetField(node.FieldRole, field.TypeString, value)
		_node.Role = value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(node.FieldContent, field.TypeJSON, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.Model(); ok {
		_spec.SetField(node.FieldModel, field.TypeString, value)
		_node.Model = value
	}
	if value, ok := _c.mutation.Provider(); ok {
		_spec.SetField(node.FieldProvider, field.TypeString, value)
		_node.Provider = value
	}
	if value, ok := _c.mutation.StopReason(); ok {
		_spec.SetField(node.FieldStopReason, field.TypeString, value)
		_node.StopReason = value
	}
	if value, ok := _c.mutation.PromptTokens(); ok {
		_spec.SetField(node.FieldPromptTokens, field.TypeInt, value)
		_node.PromptTokens = &value
	}
	if value, ok := _c.mutation.CompletionTokens(); ok {
		_spec.SetField(node.FieldCompletionTokens, field.TypeInt, value)
		_node.CompletionTokens = &value
	}
	if value, ok := _c.mutation.TotalTokens(); ok {
		_spec.SetField(node.FieldTotalTokens, field.TypeInt, value)
		_node.TotalTokens = &value
	}
	if value, ok := _c.mutation.TotalDurationNs(); ok {
		_spec.SetField(node.FieldTotalDurationNs, field.TypeInt64, value)
		_node.TotalDurationNs = &value
	}
	if value, ok := _c.mutation.PromptDurationNs(); ok {
		_spec.SetField(node.FieldPromptDurationNs, field.TypeInt64, value)
		_node.PromptDurationNs = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(node.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   node.ParentTable,
			Columns: []string{node.ParentColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ParentHash = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   node.ChildrenTable,
			Columns: []string{node.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// NodeCreateBulk is the builder for creating many Node entities in bulk.
type NodeCreateBulk struct {
	config
	err      error
	builders []*NodeCreate
}

// Save creates the Node entities in the database.
func (_c *NodeCreateBulk) Save(ctx context.Context) ([]*Node, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Node, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*NodeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *NodeCreateBulk) SaveX(ctx context.Context) []*Node {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NodeCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NodeCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
