// Code generated by ent, DO NOT EDIT.

package agenttraceconversation

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the agenttraceconversation type in the database.
	Label = "agent_trace_conversation"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldURL holds the string denoting the url field in the database.
	FieldURL = "url"
	// FieldContributorType holds the string denoting the contributor_type field in the database.
	FieldContributorType = "contributor_type"
	// FieldContributorModelID holds the string denoting the contributor_model_id field in the database.
	FieldContributorModelID = "contributor_model_id"
	// FieldRelated holds the string denoting the related field in the database.
	FieldRelated = "related"
	// EdgeFile holds the string denoting the file edge name in mutations.
	EdgeFile = "file"
	// EdgeRanges holds the string denoting the ranges edge name in mutations.
	EdgeRanges = "ranges"
	// Table holds the table name of the agenttraceconversation in the database.
	Table = "agent_trace_conversations"
	// FileTable is the table that holds the file relation/edge.
	FileTable = "agent_trace_conversations"
	// FileInverseTable is the table name for the AgentTraceFile entity.
	// It exists in this package in order to avoid circular dependency with the "agenttracefile" package.
	FileInverseTable = "agent_trace_files"
	// FileColumn is the table column denoting the file relation/edge.
	FileColumn = "agent_trace_file_conversations"
	// RangesTable is the table that holds the ranges relation/edge.
	RangesTable = "agent_trace_ranges"
	// RangesInverseTable is the table name for the AgentTraceRange entity.
	// It exists in this package in order to avoid circular dependency with the "agenttracerange" package.
	RangesInverseTable = "agent_trace_ranges"
	// RangesColumn is the table column denoting the ranges relation/edge.
	RangesColumn = "agent_trace_conversation_ranges"
)

// Columns holds all SQL columns for agenttraceconversation fields.
var Columns = []string{
	FieldID,
	FieldURL,
	FieldContributorType,
	FieldContributorModelID,
	FieldRelated,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "agent_trace_conversations"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"agent_trace_file_conversations",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the AgentTraceConversation queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByURL orders the results by the url field.
func ByURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldURL, opts...).ToFunc()
}

// ByContributorType orders the results by the contributor_type field.
func ByContributorType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContributorType, opts...).ToFunc()
}

// ByContributorModelID orders the results by the contributor_model_id field.
func ByContributorModelID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContributorModelID, opts...).ToFunc()
}

// ByFileField orders the results by file field.
func ByFileField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newFileStep(), sql.OrderByField(field, opts...))
	}
}

// ByRangesCount orders the results by ranges count.
func ByRangesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newRangesStep(), opts...)
	}
}

// ByRanges orders the results by ranges terms.
func ByRanges(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRangesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newFileStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(FileInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, FileTable, FileColumn),
	)
}
func newRangesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RangesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, RangesTable, RangesColumn),
	)
}
