// Code generated by ent, DO NOT EDIT.

package agenttraceconversation

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/papercomputeco/tapes/pkg/storage/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.AgentTraceConversation {
	return predicate.AgentTraceConversation(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.AgentTraceConversation {
	return predicate.AgentTraceConversation(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.AgentTraceConversation {
	return predicate.AgentTraceConversation(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.AgentTraceConversation {
	return predicate.AgentTraceConversation(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.AgentTraceConversation {
	return predicate.AgentTraceConversation(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.AgentTraceConversation {
	return predicate.AgentTraceConversation(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.AgentTraceConversation {
	return predicate.AgentTraceConversation(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.AgentTraceConversation {
	return predicate.AgentTraceConversation(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.AgentTraceConversation {
	return predicate.AgentTraceConversation(sql.FieldLTE(FieldID, id))
}

// URL applies equality check predicate on the "url" field. It's identical to URLEQ.
func URL(v string) predicate.AgentTraceConversation {
	return predicate.AgentTraceConversation(sql.FieldEQ(FieldURL, v))
}

// ContributorType applies equality check predicate on the "contributor_type" field. It's identical to ContributorTypeEQ.
func ContributorType(v string) predicate.AgentTraceConversation {
	return predicate.AgentTraceConversation(sql.FieldEQ(FieldContributorType, v))
}

// ContributorModelID applies equality check predicate on the "contributor_model_id" field. It's identical to ContributorModelIDEQ.
func ContributorModelID(v string) predicate.AgentTraceConversation {
	return predicate.AgentTraceConversation(sql.FieldEQ(FieldContributorModelID, v))
}

// URLEQ applies the EQ predicate on the "url" field.
func URLEQ(v string) predicate.AgentTraceConversation {
	return predicate.AgentTraceConversation(sql.FieldEQ(FieldURL, v))
}

// URLNEQ applies the NEQ predicate on the "url" field.
func URLNEQ(v string) predicate.AgentTraceConversation {
	return predicate.AgentTraceConversation(sql.FieldNEQ(FieldURL, v))
}

// URLIn applies the In predicate on the "url" field.
func URLIn(vs ...string) predicate.AgentTraceConversation {
	return predicate.AgentTraceConversation(sql.FieldIn(FieldURL, vs...))
}

// URLNotIn applies the NotIn predicate on the "url" field.
func URLNotIn(vs ...string) predicate.AgentTraceConversation {
	return predicate.AgentTraceConversation(sql.FieldNotIn(FieldURL, vs...))
}

// URLGT applies the GT predicate on the "url" field.
func URLGT(v string) predicate.AgentTraceConversation {
	return predicate.AgentTraceConversation(sql.FieldGT(FieldURL, v))
}

// URLGTE applies the GTE predicate on the "url" field.
func URLGTE(v string) predicate.AgentTraceConversation {
	return predicate.AgentTraceConversation(sql.FieldGTE(FieldURL, v))
}

// URLLT applies the LT predicate on the "url" field.
func URLLT(v string) predicate.AgentTraceConversation {
	return predicate.AgentTraceConversation(sql.FieldLT(FieldURL, v))
}

// URLLTE applies the LTE predicate on the "url" field.
func URLLTE(v string) predicate.AgentTraceConversation {
	return predicate.AgentTraceConversation(sql.FieldLTE(FieldURL, v))
}

// URLContains applies the Contains predicate on the "url" field.
func URLContains(v string) predicate.AgentTraceConversation {
	return predicate.AgentTraceConversation(sql.FieldContains(FieldURL, v))
}

// URLHasPrefix applies the HasPrefix predicate on the "url" field.
func URLHasPrefix(v string) predicate.AgentTraceConversation {
	return predicate.AgentTraceConversation(sql.FieldHasPrefix(FieldURL, v))
}

// URLHasSuffix applies the HasSuffix predicate on the "url" field.
func URLHasSuffix(v string) predicate.AgentTraceConversation {
	return predicate.AgentTraceConversation(sql.FieldHasSuffix(FieldURL, v))
}

// URLIsNil applies the IsNil predicate on the "url" field.
func URLIsNil() predicate.AgentTraceConversation {
	return predicate.AgentTraceConversation(sql.FieldIsNull(FieldURL))
}

// URLNotNil applies the NotNil predicate on the "url" field.
func URLNotNil() predicate.AgentTraceConversation {
	return predicate.AgentTraceConversation(sql.FieldNotNull(FieldURL))
}

// URLEqualFold applies the EqualFold predicate on the "url" field.
func URLEqualFold(v string) predicate.AgentTraceConversation {
	return predicate.AgentTraceConversation(sql.FieldEqualFold(FieldURL, v))
}

// URLContainsFold applies the ContainsFold predicate on the "url" field.
func URLContainsFold(v string) predicate.AgentTraceConversation {
	return predicate.AgentTraceConversation(sql.FieldContainsFold(FieldURL, v))
}

// ContributorTypeEQ applies the EQ predicate on the "contributor_type" field.
func ContributorTypeEQ(v string) predicate.AgentTraceConversation {
	return predicate.AgentTraceConversation(sql.FieldEQ(FieldContributorType, v))
}

// ContributorTypeNEQ applies the NEQ predicate on the "contributor_type" field.
func ContributorTypeNEQ(v string) predicate.AgentTraceConversation {
	return predicate.AgentTraceConversation(sql.FieldNEQ(FieldContributorType, v))
}

// ContributorTypeIn applies the In predicate on the "contributor_type" field.
func ContributorTypeIn(vs ...string) predicate.AgentTraceConversation {
	return predicate.AgentTraceConversation(sql.FieldIn(FieldContributorType, vs...))
}

// ContributorTypeNotIn applies the NotIn predicate on the "contributor_type" field.
func ContributorTypeNotIn(vs ...string) predicate.AgentTraceConversation {
	return predicate.AgentTraceConversation(sql.FieldNotIn(FieldContributorType, vs...))
}

// ContributorTypeGT applies the GT predicate on the "contributor_type" field.
func ContributorTypeGT(v string) predicate.AgentTraceConversation {
	return predicate.AgentTraceConversation(sql.FieldGT(FieldContributorType, v))
}

// ContributorTypeGTE applies the GTE predicate on the "contributor_type" field.
func ContributorTypeGTE(v string) predicate.AgentTraceConversation {
	return predicate.AgentTraceConversation(sql.FieldGTE(FieldContributorType, v))
}

// ContributorTypeLT applies the LT predicate on the "contributor_type" field.
func ContributorTypeLT(v string) predicate.AgentTraceConversation {
	return predicate.AgentTraceConversation(sql.FieldLT(FieldContributorType, v))
}

// ContributorTypeLTE applies the LTE predicate on the "contributor_type" field.
func ContributorTypeLTE(v string) predicate.AgentTraceConversation {
	return predicate.AgentTraceConversation(sql.FieldLTE(FieldContributorType, v))
}

// ContributorTypeContains applies the Contains predicate on the "contributor_type" field.
func ContributorTypeContains(v string) predicate.AgentTraceConversation {
	return predicate.AgentTraceConversation(sql.FieldContains(FieldContributorType, v))
}

// ContributorTypeHasPrefix applies the HasPrefix predicate on the "contributor_type" field.
func ContributorTypeHasPrefix(v string) predicate.AgentTraceConversation {
	return predicate.AgentTraceConversation(sql.FieldHasPrefix(FieldContributorType, v))
}

// ContributorTypeHasSuffix applies the HasSuffix predicate on the "contributor_type" field.
func ContributorTypeHasSuffix(v string) predicate.AgentTraceConversation {
	return predicate.AgentTraceConversation(sql.FieldHasSuffix(FieldContributorType, v))
}

// ContributorTypeIsNil applies the IsNil predicate on the "contributor_type" field.
func ContributorTypeIsNil() predicate.AgentTraceConversation {
	return predicate.AgentTraceConversation(sql.FieldIsNull(FieldContributorType))
}

// ContributorTypeNotNil applies the NotNil predicate on the "contributor_type" field.
func ContributorTypeNotNil() predicate.AgentTraceConversation {
	return predicate.AgentTraceConversation(sql.FieldNotNull(FieldContributorType))
}

// ContributorTypeEqualFold applies the EqualFold predicate on the "contributor_type" field.
func ContributorTypeEqualFold(v string) predicate.AgentTraceConversation {
	return predicate.AgentTraceConversation(sql.FieldEqualFold(FieldContributorType, v))
}

// ContributorTypeContainsFold applies the ContainsFold predicate on the "contributor_type" field.
func ContributorTypeContainsFold(v string) predicate.AgentTraceConversation {
	return predicate.AgentTraceConversation(sql.FieldContainsFold(FieldContributorType, v))
}

// ContributorModelIDEQ applies the EQ predicate on the "contributor_model_id" field.
func ContributorModelIDEQ(v string) predicate.AgentTraceConversation {
	return predicate.AgentTraceConversation(sql.FieldEQ(FieldContributorModelID, v))
}

// ContributorModelIDNEQ applies the NEQ predicate on the "contributor_model_id" field.
func ContributorModelIDNEQ(v string) predicate.AgentTraceConversation {
	return predicate.AgentTraceConversation(sql.FieldNEQ(FieldContributorModelID, v))
}

// ContributorModelIDIn applies the In predicate on the "contributor_model_id" field.
func ContributorModelIDIn(vs ...string) predicate.AgentTraceConversation {
	return predicate.AgentTraceConversation(sql.FieldIn(FieldContributorModelID, vs...))
}

// ContributorModelIDNotIn applies the NotIn predicate on the "contributor_model_id" field.
func ContributorModelIDNotIn(vs ...string) predicate.AgentTraceConversation {
	return predicate.AgentTraceConversation(sql.FieldNotIn(FieldContributorModelID, vs...))
}

// ContributorModelIDGT applies the GT predicate on the "contributor_model_id" field.
func ContributorModelIDGT(v string) predicate.AgentTraceConversation {
	return predicate.AgentTraceConversation(sql.FieldGT(FieldContributorModelID, v))
}

// ContributorModelIDGTE applies the GTE predicate on the "contributor_model_id" field.
func ContributorModelIDGTE(v string) predicate.AgentTraceConversation {
	return predicate.AgentTraceConversation(sql.FieldGTE(FieldContributorModelID, v))
}

// ContributorModelIDLT applies the LT predicate on the "contributor_model_id" field.
func ContributorModelIDLT(v string) predicate.AgentTraceConversation {
	return predicate.AgentTraceConversation(sql.FieldLT(FieldContributorModelID, v))
}

// ContributorModelIDLTE applies the LTE predicate on the "contributor_model_id" field.
func ContributorModelIDLTE(v string) predicate.AgentTraceConversation {
	return predicate.AgentTraceConversation(sql.FieldLTE(FieldContributorModelID, v))
}

// ContributorModelIDContains applies the Contains predicate on the "contributor_model_id" field.
func ContributorModelIDContains(v string) predicate.AgentTraceConversation {
	return predicate.AgentTraceConversation(sql.FieldContains(FieldContributorModelID, v))
}

// ContributorModelIDHasPrefix applies the HasPrefix predicate on the "contributor_model_id" field.
func ContributorModelIDHasPrefix(v string) predicate.AgentTraceConversation {
	return predicate.AgentTraceConversation(sql.FieldHasPrefix(FieldContributorModelID, v))
}

// ContributorModelIDHasSuffix applies the HasSuffix predicate on the "contributor_model_id" field.
func ContributorModelIDHasSuffix(v string) predicate.AgentTraceConversation {
	return predicate.AgentTraceConversation(sql.FieldHasSuffix(FieldContributorModelID, v))
}

// ContributorModelIDIsNil applies the IsNil predicate on the "contributor_model_id" field.
func ContributorModelIDIsNil() predicate.AgentTraceConversation {
	return predicate.AgentTraceConversation(sql.FieldIsNull(FieldContributorModelID))
}

// ContributorModelIDNotNil applies the NotNil predicate on the "contributor_model_id" field.
func ContributorModelIDNotNil() predicate.AgentTraceConversation {
	return predicate.AgentTraceConversation(sql.FieldNotNull(FieldContributorModelID))
}

// ContributorModelIDEqualFold applies the EqualFold predicate on the "contributor_model_id" field.
func ContributorModelIDEqualFold(v string) predicate.AgentTraceConversation {
	return predicate.AgentTraceConversation(sql.FieldEqualFold(FieldContributorModelID, v))
}

// ContributorModelIDContainsFold applies the ContainsFold predicate on the "contributor_model_id" field.
func ContributorModelIDContainsFold(v string) predicate.AgentTraceConversation {
	return predicate.AgentTraceConversation(sql.FieldContainsFold(FieldContributorModelID, v))
}

// RelatedIsNil applies the IsNil predicate on the "related" field.
func RelatedIsNil() predicate.AgentTraceConversation {
	return predicate.AgentTraceConversation(sql.FieldIsNull(FieldRelated))
}

// RelatedNotNil applies the NotNil predicate on the "related" field.
func RelatedNotNil() predicate.AgentTraceConversation {
	return predicate.AgentTraceConversation(sql.FieldNotNull(FieldRelated))
}

// HasFile applies the HasEdge predicate on the "file" edge.
func HasFile() predicate.AgentTraceConversation {
	return predicate.AgentTraceConversation(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, FileTable, FileColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasFileWith applies the HasEdge predicate on the "file" edge with a given conditions (other predicates).
func HasFileWith(preds ...predicate.AgentTraceFile) predicate.AgentTraceConversation {
	return predicate.AgentTraceConversation(func(s *sql.Selector) {
		step := newFileStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRanges applies the HasEdge predicate on the "ranges" edge.
func HasRanges() predicate.AgentTraceConversation {
	return predicate.AgentTraceConversation(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, RangesTable, RangesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRangesWith applies the HasEdge predicate on the "ranges" edge with a given conditions (other predicates).
func HasRangesWith(preds ...predicate.AgentTraceRange) predicate.AgentTraceConversation {
	return predicate.AgentTraceConversation(func(s *sql.Selector) {
		step := newRangesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AgentTraceConversation) predicate.AgentTraceConversation {
	return predicate.AgentTraceConversation(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AgentTraceConversation) predicate.AgentTraceConversation {
	return predicate.AgentTraceConversation(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AgentTraceConversation) predicate.AgentTraceConversation {
	return predicate.AgentTraceConversation(sql.NotPredicates(p))
}
