-- name: AncestryChains :many
SELECT
    COALESCE(walk.start_hash::text, '') AS start_hash,
    COALESCE(walk.hash::text, '') AS hash,
    COALESCE(walk.parent_hash::text, '') AS parent_hash,
    COALESCE(walk.bucket::jsonb, '{}'::jsonb) AS bucket,
    COALESCE(walk.type::text, '') AS type,
    COALESCE(walk.role::text, '') AS role,
    COALESCE(walk.content::jsonb, '[]'::jsonb) AS content,
    COALESCE(walk.model::text, '') AS model,
    COALESCE(walk.provider::text, '') AS provider,
    COALESCE(walk.agent_name::text, '') AS agent_name,
    COALESCE(walk.stop_reason::text, '') AS stop_reason,
    COALESCE(walk.prompt_tokens::integer, 0) AS prompt_tokens,
    COALESCE(walk.completion_tokens::integer, 0) AS completion_tokens,
    COALESCE(walk.total_tokens::integer, 0) AS total_tokens,
    COALESCE(walk.cache_creation_input_tokens::integer, 0) AS cache_creation_input_tokens,
    COALESCE(walk.cache_read_input_tokens::integer, 0) AS cache_read_input_tokens,
    COALESCE(walk.total_duration_ns::bigint, 0) AS total_duration_ns,
    COALESCE(walk.prompt_duration_ns::bigint, 0) AS prompt_duration_ns,
    COALESCE(walk.project::text, '') AS project,
    walk.created_at::timestamptz AS created_at,
    walk.depth::integer AS depth,
    walk.has_usage::boolean AS has_usage
FROM ancestry_chains_rows(sqlc.arg(hashes)::text[], sqlc.arg(max_depth)::integer) AS walk(
    start_hash,
    hash,
    parent_hash,
    bucket,
    type,
    role,
    content,
    model,
    provider,
    agent_name,
    stop_reason,
    prompt_tokens,
    completion_tokens,
    total_tokens,
    cache_creation_input_tokens,
    cache_read_input_tokens,
    total_duration_ns,
    prompt_duration_ns,
    project,
    created_at,
    depth,
    has_usage
)
ORDER BY walk.start_hash, walk.depth;
