// Command gen-openapi converts the swaggo-generated Swagger 2.0 document
// (docs/swagger.json) into a clean OpenAPI 3.0.3 document written to
// api/openapi.yaml.
//
// This is the versioned contract other services (notably the paper CLI, which
// generates a Rust client with progenitor) consume. progenitor + openapiv3 are
// OpenAPI 3.0.x-only and require an operationId on every operation, so this tool:
//
//   - converts 2.0 -> 3.0.3 in-process via kin-openapi (no Node toolchain),
//   - forces the version string to 3.0.3,
//   - synthesizes a deterministic operationId for any operation still missing
//     one (belt-and-suspenders: the handlers carry @ID annotations, but a future
//     un-annotated handler must not be able to break downstream codegen),
//   - strips swag's package prefixes from component schema names (and rewrites
//     every $ref) so the generated Rust types read as SessionItem rather than
//     ApiSessionItem, with a collision guard that keeps the qualified name when
//     two packages would otherwise collapse onto the same bare name.
//
// Run via `make openapi` (which runs `make swag` first). Do not edit the output
// by hand.
package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/getkin/kin-openapi/openapi2"
	"github.com/getkin/kin-openapi/openapi2conv"
	"github.com/getkin/kin-openapi/openapi3"
	"sigs.k8s.io/yaml"
)

const (
	swaggerInputPath  = "docs/swagger.json"
	openapiOutputPath = "api/openapi.yaml"
	openapiVersion    = "3.0.3"
	schemaRefPrefix   = "#/components/schemas/"
)

func main() {
	if err := run(); err != nil {
		fmt.Fprintf(os.Stderr, "gen-openapi: %v\n", err)
		os.Exit(1)
	}
}

func run() error {
	raw, err := os.ReadFile(swaggerInputPath)
	if err != nil {
		return fmt.Errorf("read %s (did you run `make swag`?): %w", swaggerInputPath, err)
	}

	var doc2 openapi2.T
	if err := json.Unmarshal(raw, &doc2); err != nil {
		return fmt.Errorf("parse swagger 2.0: %w", err)
	}

	doc3, err := openapi2conv.ToV3(&doc2)
	if err != nil {
		return fmt.Errorf("convert to openapi 3: %w", err)
	}
	doc3.OpenAPI = openapiVersion

	// OpenAPI 3.0.3 requires a non-empty info.version. swag emits it from
	// the @version annotation; default it defensively so a missing
	// annotation degrades to a placeholder instead of failing validation.
	if doc3.Info != nil && strings.TrimSpace(doc3.Info.Version) == "" {
		doc3.Info.Version = "0.0.0"
	}

	synthesizeOperationIDs(doc3)

	// Round-trip through the spec-valid JSON encoding, then do the schema
	// rename on a generic tree so we only ever touch $ref strings and the
	// component keys — no deep kin-openapi traversal to keep in sync.
	jsonBytes, err := doc3.MarshalJSON()
	if err != nil {
		return fmt.Errorf("marshal openapi 3 to json: %w", err)
	}

	var tree map[string]any
	if err := json.Unmarshal(jsonBytes, &tree); err != nil {
		return fmt.Errorf("reparse openapi 3 json: %w", err)
	}

	if err := stripSchemaPrefixes(tree); err != nil {
		return fmt.Errorf("strip schema prefixes: %w", err)
	}

	// sigs.k8s.io/yaml marshals value -> JSON -> YAML with sorted keys, so the
	// output is deterministic and integral numbers stay integers.
	out, err := yaml.Marshal(tree)
	if err != nil {
		return fmt.Errorf("marshal yaml: %w", err)
	}

	// Re-parse and validate the FINAL document against the OpenAPI 3.0.3
	// schema, so a conversion or $ref-rewrite bug (e.g. a ref left pointing
	// at a schema key the rename missed) fails here, at generation time,
	// rather than downstream when a client generator chokes on it.
	loader := openapi3.NewLoader()
	finalDoc, err := loader.LoadFromData(out)
	if err != nil {
		return fmt.Errorf("reload generated spec for validation: %w", err)
	}
	if err := finalDoc.Validate(loader.Context); err != nil {
		return fmt.Errorf("generated spec failed OpenAPI %s validation: %w", openapiVersion, err)
	}

	header := "# Code generated by cmd/gen-openapi from " + swaggerInputPath + ". DO NOT EDIT.\n"
	body := append([]byte(header), out...)

	if err := os.MkdirAll(filepath.Dir(openapiOutputPath), 0o755); err != nil {
		return fmt.Errorf("mkdir: %w", err)
	}
	if err := os.WriteFile(openapiOutputPath, body, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", openapiOutputPath, err)
	}

	fmt.Printf("gen-openapi: wrote %s (openapi %s, %d paths, %d schemas)\n",
		openapiOutputPath, doc3.OpenAPI, doc3.Paths.Len(), len(doc3.Components.Schemas))
	return nil
}

var nonIdentRe = regexp.MustCompile(`[^a-zA-Z0-9]+`)

// synthesizeOperationIDs fills in a deterministic operationId for any operation
// that lacks one, so progenitor (which hard-panics on a missing operationId)
// can always consume the output even if a handler forgets its @ID annotation.
func synthesizeOperationIDs(doc *openapi3.T) {
	if doc.Paths == nil {
		return
	}
	paths := doc.Paths.Map()
	// Iterate in sorted path order for stable synthesized names.
	keys := make([]string, 0, len(paths))
	for k := range paths {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	// Seed with every explicit operationId so a synthesized fallback can
	// collide with neither an existing id nor an earlier synthesized one.
	seen := make(map[string]bool)
	for _, item := range paths {
		for _, op := range item.Operations() {
			if op.OperationID != "" {
				seen[op.OperationID] = true
			}
		}
	}

	for _, path := range keys {
		item := paths[path]
		ops := item.Operations()
		// Deterministic method order so a collision suffix is assigned the
		// same way on every run.
		methods := make([]string, 0, len(ops))
		for method := range ops {
			methods = append(methods, method)
		}
		sort.Strings(methods)
		for _, method := range methods {
			op := ops[method]
			if op.OperationID != "" {
				continue
			}
			op.OperationID = uniqueOperationID(synthesizeID(method, path), seen)
			seen[op.OperationID] = true
		}
	}
}

// uniqueOperationID returns base if unused, else base with the smallest
// numeric suffix that is free. Paths differing only in separator style
// (e.g. `{session-id}` vs `{session_id}`) sanitize to the same base, so
// without this the spec could carry two ops sharing one operationId — an
// OpenAPI violation that makes progenitor panic.
func uniqueOperationID(base string, seen map[string]bool) string {
	if !seen[base] {
		return base
	}
	for i := 2; ; i++ {
		candidate := fmt.Sprintf("%s%d", base, i)
		if !seen[candidate] {
			return candidate
		}
	}
}

// synthesizeID builds an operationId like "getV1SessionsId" from a method and
// path. Deterministic and collision-resistant enough for a fallback.
func synthesizeID(method, path string) string {
	parts := nonIdentRe.Split(path, -1)
	var b strings.Builder
	b.WriteString(strings.ToLower(method))
	for _, p := range parts {
		if p == "" {
			continue
		}
		b.WriteString(strings.ToUpper(p[:1]))
		b.WriteString(p[1:])
	}
	return b.String()
}

// reservedBareNames are type/trait names that must NOT become a component schema
// key: a downstream Rust client (progenitor) emits a `pub struct <name>` per
// schema, and if that name shadows a prelude type the generated code stops
// compiling (e.g. `Result` shadows `std::result::Result`). Schemas whose bare
// name lands here keep their package-qualified key, which progenitor sanitizes
// into a safe, unique CamelCase identifier.
var reservedBareNames = map[string]bool{
	"Result": true, "Option": true, "String": true, "Vec": true, "Box": true,
	"Self": true, "Ok": true, "Err": true, "Some": true, "None": true,
	"Iterator": true, "Future": true,
}

// stripSchemaPrefixes renames component schema keys from swag's package-qualified
// form (api.SessionItem, github_com_..._pkg_llm.ErrorResponse) to their bare type
// name (SessionItem, ErrorResponse) and rewrites every $ref accordingly. A
// qualified name is left untouched when its bare form would either collide with
// another schema's bare form or shadow a reserved Rust prelude name.
func stripSchemaPrefixes(tree map[string]any) error {
	components, ok := tree["components"].(map[string]any)
	if !ok {
		return nil // nothing to rename
	}
	schemas, ok := components["schemas"].(map[string]any)
	if !ok {
		return nil
	}

	// Count bare-name targets to detect collisions.
	bareCount := map[string]int{}
	for name := range schemas {
		bareCount[bareName(name)]++
	}

	rename := map[string]string{}
	for name := range schemas {
		bare := bareName(name)
		if bare != name && bareCount[bare] == 1 && !reservedBareNames[bare] {
			rename[name] = bare
		}
	}
	if len(rename) == 0 {
		return nil
	}

	// Rewrite the schemas map keys.
	renamed := make(map[string]any, len(schemas))
	for name, schema := range schemas {
		if newName, ok := rename[name]; ok {
			renamed[newName] = schema
		} else {
			renamed[name] = schema
		}
	}
	components["schemas"] = renamed

	// Rewrite every $ref pointing at a renamed schema, everywhere in the tree.
	refRewrites := make(map[string]string, len(rename))
	for old, newName := range rename {
		refRewrites[schemaRefPrefix+old] = schemaRefPrefix + newName
	}
	rewriteRefs(tree, refRewrites)
	return nil
}

// bareName returns the substring after the final '.' in a swag schema name.
func bareName(name string) string {
	if i := strings.LastIndex(name, "."); i >= 0 {
		return name[i+1:]
	}
	return name
}

// rewriteRefs walks an arbitrary JSON tree and replaces any string value under a
// "$ref" key according to the rewrites map.
func rewriteRefs(node any, rewrites map[string]string) {
	switch n := node.(type) {
	case map[string]any:
		for k, v := range n {
			if k == "$ref" {
				if s, ok := v.(string); ok {
					if repl, ok := rewrites[s]; ok {
						n[k] = repl
					}
				}
				continue
			}
			rewriteRefs(v, rewrites)
		}
	case []any:
		for _, v := range n {
			rewriteRefs(v, rewrites)
		}
	}
}
