// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/ping": {
            "get": {
                "description": "Returns a simple JSON string confirming that the API server is reachable.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "pong",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/mcp": {
            "get": {
                "description": "Opens the streamable MCP endpoint for server-sent events. Stateless clients can use this to receive streamed MCP messages.",
                "produces": [
                    "text/event-stream"
                ],
                "tags": [
                    "mcp"
                ],
                "summary": "Open an MCP event stream",
                "responses": {
                    "200": {
                        "description": "Server-sent event stream",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "Sends a JSON-RPC 2.0 request to the stateless Model Context Protocol endpoint mounted at /v1/mcp.\n\nTypical calls include initialize, tools/list, and tools/call. When search is configured, the server exposes a search tool over this transport.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mcp"
                ],
                "summary": "Invoke the streamable MCP endpoint",
                "parameters": [
                    {
                        "description": "JSON-RPC 2.0 request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.swaggerMCPRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.swaggerMCPResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid JSON-RPC request",
                        "schema": {
                            "$ref": "#/definitions/api.swaggerMCPResponse"
                        }
                    },
                    "500": {
                        "description": "Server-side MCP error",
                        "schema": {
                            "$ref": "#/definitions/api.swaggerMCPResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Requests termination of a streamable MCP session when a client is using session-oriented transport semantics.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mcp"
                ],
                "summary": "Close an MCP session",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.swaggerMCPResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.swaggerMCPResponse"
                        }
                    }
                }
            }
        },
        "/v1/search": {
            "get": {
                "description": "Embeds the query text, searches the configured vector store, and returns matching sessions with their full conversation branch.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "search"
                ],
                "summary": "Semantic search over stored sessions",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search query",
                        "name": "query",
                        "in": "query",
                        "required": true
                    },
                    {
                        "minimum": 1,
                        "type": "integer",
                        "default": 5,
                        "description": "Maximum number of results to return",
                        "name": "top_k",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_papercomputeco_tapes_api_search.Output"
                        }
                    },
                    "400": {
                        "description": "Missing or invalid query parameters",
                        "schema": {
                            "$ref": "#/definitions/github_com_papercomputeco_tapes_pkg_llm.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Search execution failed",
                        "schema": {
                            "$ref": "#/definitions/github_com_papercomputeco_tapes_pkg_llm.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Search is not configured",
                        "schema": {
                            "$ref": "#/definitions/github_com_papercomputeco_tapes_pkg_llm.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/sessions": {
            "get": {
                "description": "Returns one row per harness session from the sessions table, newest first (last_seen_at desc), cursor-paginated. This is the product session view; the Merkle leaf-chain view lives at /v1/stems.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sessions"
                ],
                "summary": "List sessions",
                "parameters": [
                    {
                        "minimum": 1,
                        "type": "integer",
                        "description": "Maximum number of sessions to return (default 50, max 200)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Opaque pagination cursor returned by a previous response",
                        "name": "cursor",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter to the single session with this harness id (exact match; requires harness_session_id, incompatible with cursor; limit is ignored when the filter is active)",
                        "name": "harness_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter to the single session with this harness session id (exact match; requires harness_id, incompatible with cursor; limit is ignored when the filter is active)",
                        "name": "harness_session_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.SessionListResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid query parameters, a lone harness filter param, or cursor combined with the harness filter",
                        "schema": {
                            "$ref": "#/definitions/github_com_papercomputeco_tapes_pkg_llm.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to list sessions",
                        "schema": {
                            "$ref": "#/definitions/github_com_papercomputeco_tapes_pkg_llm.ErrorResponse"
                        }
                    },
                    "501": {
                        "description": "Sessions not supported by this backend",
                        "schema": {
                            "$ref": "#/definitions/github_com_papercomputeco_tapes_pkg_llm.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/sessions/{id}": {
            "get": {
                "description": "Returns a single session, the selected stem of turns, and a summary of every stem (root-to-leaf path) in the session. ?stem=longest (default) returns the longest stem; ?stem=all returns every node ordered by created_at. ?root=\u003chash\u003e restricts turns to the subtree rooted at that node.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sessions"
                ],
                "summary": "Get a session",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session id (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "longest",
                            "all"
                        ],
                        "type": "string",
                        "description": "Which turns to return: longest (default) or all",
                        "name": "stem",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Restrict turns to the subtree rooted at this node hash",
                        "name": "root",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.SessionDetailResponse"
                        }
                    },
                    "400": {
                        "description": "Missing id or unknown root",
                        "schema": {
                            "$ref": "#/definitions/github_com_papercomputeco_tapes_pkg_llm.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Session not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_papercomputeco_tapes_pkg_llm.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to load session",
                        "schema": {
                            "$ref": "#/definitions/github_com_papercomputeco_tapes_pkg_llm.ErrorResponse"
                        }
                    },
                    "501": {
                        "description": "Sessions not supported by this backend",
                        "schema": {
                            "$ref": "#/definitions/github_com_papercomputeco_tapes_pkg_llm.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/stats": {
            "get": {
                "description": "Returns counts plus folded cost / token / duration / tool-call / completed-count totals across every node matching the supplied filters. Numeric aggregates come from a single storage-driver SQL aggregate; cost is folded in the handler from the per-model token rollup using the configured pricing table. total_duration_ns is wall-clock MAX-MIN over the matched window (see PCC-514). completed_count uses leaf-status-only classification (assistant leaf with a terminal stop_reason) — see StatsResponse and PCC-515 for the durable chain-aware fix.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sessions"
                ],
                "summary": "Get aggregate session stats",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by project name",
                        "name": "project",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by agent name",
                        "name": "agent_name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by model name",
                        "name": "model",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by provider name",
                        "name": "provider",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "format": "date-time",
                        "description": "Only include records at or after this RFC3339 timestamp",
                        "name": "since",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "format": "date-time",
                        "description": "Only include records before or at this RFC3339 timestamp",
                        "name": "until",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.StatsResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid query parameters",
                        "schema": {
                            "$ref": "#/definitions/github_com_papercomputeco_tapes_pkg_llm.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to compute stats",
                        "schema": {
                            "$ref": "#/definitions/github_com_papercomputeco_tapes_pkg_llm.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/stems": {
            "get": {
                "description": "Returns paginated per-stem summaries including derived labels, status, token counts, cost, duration, and truncation metadata.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stems"
                ],
                "summary": "List stems (Merkle leaf chains) with aggregates",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by project name",
                        "name": "project",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by agent name",
                        "name": "agent_name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by model name",
                        "name": "model",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by provider name",
                        "name": "provider",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "format": "date-time",
                        "description": "Only include stems updated at or after this RFC3339 timestamp",
                        "name": "since",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "format": "date-time",
                        "description": "Only include stems updated before or at this RFC3339 timestamp",
                        "name": "until",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Opaque pagination cursor returned by a previous response",
                        "name": "cursor",
                        "in": "query"
                    },
                    {
                        "minimum": 1,
                        "type": "integer",
                        "description": "Maximum number of stems to return",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.StemListResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid query parameters",
                        "schema": {
                            "$ref": "#/definitions/github_com_papercomputeco_tapes_pkg_llm.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to list or summarize stems",
                        "schema": {
                            "$ref": "#/definitions/github_com_papercomputeco_tapes_pkg_llm.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/stems/{hash}": {
            "get": {
                "description": "Returns the ancestry chain of a single Merkle leaf in chronological order (root first). When depth is provided, only the last N turns are returned while the full chain depth is still reported.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stems"
                ],
                "summary": "Get a stem (Merkle leaf chain)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Stem head (leaf) hash",
                        "name": "hash",
                        "in": "path",
                        "required": true
                    },
                    {
                        "minimum": 1,
                        "type": "integer",
                        "description": "Maximum number of most-recent turns to include",
                        "name": "depth",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.StemResponse"
                        }
                    },
                    "400": {
                        "description": "Missing or invalid hash/depth",
                        "schema": {
                            "$ref": "#/definitions/github_com_papercomputeco_tapes_pkg_llm.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Stem not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_papercomputeco_tapes_pkg_llm.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to load stem",
                        "schema": {
                            "$ref": "#/definitions/github_com_papercomputeco_tapes_pkg_llm.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/stems/{hash}/graph": {
            "get": {
                "description": "Returns a graph-shaped projection of the Merkle DAG around a node hash (the same ancestry returned by GET /v1/stems/{hash}). scope=root loads the requested node's resolvable root and all descendants, scope=branch loads the ancestry plus descendants of the requested node, and scope=ancestry loads only the parent chain.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stems"
                ],
                "summary": "Get a stem graph",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Node (stem head) hash",
                        "name": "hash",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "root",
                            "branch",
                            "ancestry"
                        ],
                        "type": "string",
                        "description": "Graph scope: root, branch, or ancestry",
                        "name": "scope",
                        "in": "query"
                    },
                    {
                        "maximum": 5000,
                        "minimum": 1,
                        "type": "integer",
                        "description": "Maximum number of graph nodes to include",
                        "name": "max_nodes",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.GraphResponse"
                        }
                    },
                    "400": {
                        "description": "Missing hash or invalid query parameters",
                        "schema": {
                            "$ref": "#/definitions/github_com_papercomputeco_tapes_pkg_llm.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Stem not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_papercomputeco_tapes_pkg_llm.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to load stem graph",
                        "schema": {
                            "$ref": "#/definitions/github_com_papercomputeco_tapes_pkg_llm.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.GraphLink": {
            "type": "object",
            "properties": {
                "source": {
                    "type": "string"
                },
                "target": {
                    "type": "string"
                }
            }
        },
        "api.GraphNode": {
            "type": "object",
            "properties": {
                "agent_name": {
                    "type": "string"
                },
                "children_count": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "depth": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "is_branch_point": {
                    "type": "boolean"
                },
                "is_leaf": {
                    "type": "boolean"
                },
                "is_root": {
                    "type": "boolean"
                },
                "model": {
                    "type": "string"
                },
                "parent_hash": {
                    "type": "string"
                },
                "parent_id": {
                    "type": "string"
                },
                "preview": {
                    "type": "string"
                },
                "project": {
                    "type": "string"
                },
                "provider": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "selected": {
                    "type": "boolean"
                },
                "stop_reason": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "usage": {
                    "$ref": "#/definitions/github_com_papercomputeco_tapes_pkg_llm.Usage"
                }
            }
        },
        "api.GraphResponse": {
            "type": "object",
            "properties": {
                "branch_points": {
                    "description": "BranchPoints names included nodes with more than one child in storage.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "cycle_detected": {
                    "description": "CycleDetected is true when storage guarded the ancestry walk out of a cycle.",
                    "type": "boolean"
                },
                "hash": {
                    "description": "Hash is the session/node hash requested by the caller.",
                    "type": "string"
                },
                "leaves": {
                    "description": "Leaves names included nodes that have no children in storage.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "links": {
                    "description": "Links contains parent -\u003e child edges between included nodes.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.GraphLink"
                    }
                },
                "missing_parent": {
                    "description": "MissingParent names the unresolved parent hash when the ancestry is incomplete.",
                    "type": "string"
                },
                "node_limit": {
                    "description": "NodeLimit is the maximum number of nodes the server will include.",
                    "type": "integer"
                },
                "nodes": {
                    "description": "Nodes is the flat node list consumed by graph visualizers.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.GraphNode"
                    }
                },
                "root_hash": {
                    "description": "RootHash is the top-most resolvable node included in the response.",
                    "type": "string"
                },
                "scope": {
                    "description": "Scope describes which portion of the graph was loaded: root, branch, or ancestry.",
                    "type": "string"
                },
                "truncated": {
                    "description": "Truncated is true when the graph hit NodeLimit or the ancestry chain is incomplete.",
                    "type": "boolean"
                }
            }
        },
        "api.SessionDetailResponse": {
            "type": "object",
            "properties": {
                "session": {
                    "$ref": "#/definitions/api.SessionItem"
                },
                "stems": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.StemSummary"
                    }
                },
                "turns": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.Turn"
                    }
                }
            }
        },
        "api.SessionItem": {
            "type": "object",
            "properties": {
                "cwd": {
                    "type": "string"
                },
                "derived_status": {
                    "type": "string"
                },
                "ended_at": {
                    "type": "string"
                },
                "harness_id": {
                    "type": "string"
                },
                "harness_metadata": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "harness_session_id": {
                    "type": "string"
                },
                "harness_version": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "last_seen_at": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "parent_session_id": {
                    "type": "string"
                },
                "preview": {
                    "type": "string"
                },
                "started_at": {
                    "type": "string"
                },
                "total_cost_usd": {
                    "type": "number"
                },
                "total_input_tokens": {
                    "type": "integer"
                },
                "total_output_tokens": {
                    "type": "integer"
                },
                "turn_count": {
                    "type": "integer"
                }
            }
        },
        "api.SessionListResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.SessionItem"
                    }
                },
                "next_cursor": {
                    "type": "string"
                }
            }
        },
        "api.StatsResponse": {
            "type": "object",
            "properties": {
                "completed_count": {
                    "type": "integer"
                },
                "input_tokens": {
                    "type": "integer"
                },
                "output_tokens": {
                    "type": "integer"
                },
                "root_count": {
                    "type": "integer"
                },
                "session_count": {
                    "type": "integer"
                },
                "stem_count": {
                    "type": "integer"
                },
                "tool_calls": {
                    "type": "integer"
                },
                "total_cost": {
                    "type": "number"
                },
                "total_duration_ns": {
                    "type": "integer"
                },
                "turn_count": {
                    "type": "integer"
                }
            }
        },
        "api.StemListResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_papercomputeco_tapes_pkg_sessions.SessionSummary"
                    }
                },
                "next_cursor": {
                    "type": "string"
                }
            }
        },
        "api.StemResponse": {
            "type": "object",
            "properties": {
                "depth": {
                    "description": "Depth is the total number of turns in the full ancestry of Hash.\nWhen the client passes ?depth=N, the Turns array may contain fewer\nthan Depth items.",
                    "type": "integer"
                },
                "harness_id": {
                    "description": "HarnessID and HarnessSessionID identify the upstream agent session when\nsession tracking metadata is available. For Claude Code, HarnessID is\n\"claude\" and HarnessSessionID is Claude's session id.",
                    "type": "string"
                },
                "harness_session_id": {
                    "type": "string"
                },
                "hash": {
                    "description": "Hash is the head of the returned chain (== the requested hash).",
                    "type": "string"
                },
                "missing_parent": {
                    "type": "string"
                },
                "truncated": {
                    "description": "Truncated is true when the ancestry walk stopped at a parent_hash\nthat could not be resolved in the current store. MissingParent\nnames that hash. This is an expected edge case on stores that\ntrim older data, merge foreign content, or offload history to\nanother source — not an error.",
                    "type": "boolean"
                },
                "turns": {
                    "description": "Turns contains the chain in chronological order (root-first).\nWhen ?depth=N is supplied, only the last N turns (head + N-1 ancestors)\nare returned, still in chronological order.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.Turn"
                    }
                }
            }
        },
        "api.StemSummary": {
            "type": "object",
            "properties": {
                "length": {
                    "type": "integer"
                },
                "model": {
                    "type": "string"
                },
                "preview": {
                    "type": "string"
                },
                "root_hash": {
                    "type": "string"
                }
            }
        },
        "api.Turn": {
            "type": "object",
            "properties": {
                "agent_name": {
                    "type": "string"
                },
                "content": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_papercomputeco_tapes_pkg_llm.ContentBlock"
                    }
                },
                "created_at": {
                    "type": "string"
                },
                "hash": {
                    "type": "string"
                },
                "model": {
                    "type": "string"
                },
                "parent_hash": {
                    "type": "string"
                },
                "provider": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "stop_reason": {
                    "type": "string"
                },
                "usage": {
                    "$ref": "#/definitions/github_com_papercomputeco_tapes_pkg_llm.Usage"
                }
            }
        },
        "api.swaggerMCPError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": -32600
                },
                "message": {
                    "type": "string",
                    "example": "invalid request"
                }
            }
        },
        "api.swaggerMCPRequest": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "1"
                },
                "jsonrpc": {
                    "type": "string",
                    "example": "2.0"
                },
                "method": {
                    "type": "string",
                    "example": "tools/call"
                },
                "params": {
                    "type": "object",
                    "additionalProperties": {}
                }
            }
        },
        "api.swaggerMCPResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/api.swaggerMCPError"
                },
                "id": {
                    "type": "string",
                    "example": "1"
                },
                "jsonrpc": {
                    "type": "string",
                    "example": "2.0"
                },
                "result": {
                    "type": "object",
                    "additionalProperties": {}
                }
            }
        },
        "github_com_papercomputeco_tapes_api_search.Output": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "query": {
                    "type": "string"
                },
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_papercomputeco_tapes_api_search.Result"
                    }
                }
            }
        },
        "github_com_papercomputeco_tapes_api_search.Result": {
            "type": "object",
            "properties": {
                "branch": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_papercomputeco_tapes_api_search.Turn"
                    }
                },
                "hash": {
                    "type": "string"
                },
                "preview": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "score": {
                    "type": "number"
                },
                "turns": {
                    "type": "integer"
                }
            }
        },
        "github_com_papercomputeco_tapes_api_search.Turn": {
            "type": "object",
            "properties": {
                "hash": {
                    "type": "string"
                },
                "matched": {
                    "type": "boolean"
                },
                "role": {
                    "type": "string"
                },
                "text": {
                    "type": "string"
                }
            }
        },
        "github_com_papercomputeco_tapes_pkg_llm.ContentBlock": {
            "type": "object",
            "properties": {
                "content": {
                    "description": "Content (type=\"web_search_tool_result\" and other server-tool results) -\nthe raw result payload Anthropic returns inline on the block, captured\nverbatim as JSON so the variable result-object shapes survive without\nimposing a schema. ToolResultID links it to the paired server_tool_use.",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "image_base64": {
                    "description": "Base64-encoded image data",
                    "type": "string"
                },
                "image_url": {
                    "description": "Image content (type=\"image\")",
                    "type": "string"
                },
                "is_error": {
                    "type": "boolean"
                },
                "media_type": {
                    "description": "MIME type (e.g., \"image/png\")",
                    "type": "string"
                },
                "text": {
                    "description": "Text content (type=\"text\")",
                    "type": "string"
                },
                "thinking": {
                    "description": "Thinking (type=\"thinking\") - Anthropic extended-thinking blocks.\nAnthropic emits thinking as content_block_delta frames with type\n\"thinking_delta\" followed by a \"signature_delta\" that authenticates the\nblock. Consumers treat Thinking as opaque text; the signature is persisted\nso downstream tooling can verify integrity.",
                    "type": "string"
                },
                "thinking_signature": {
                    "type": "string"
                },
                "tool_input": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "tool_name": {
                    "type": "string"
                },
                "tool_output": {
                    "type": "string"
                },
                "tool_result_id": {
                    "description": "Tool result (type=\"tool_result\") - result from tool execution",
                    "type": "string"
                },
                "tool_use_id": {
                    "description": "Tool use (type=\"tool_use\") - assistant requesting tool execution",
                    "type": "string"
                },
                "type": {
                    "description": "\"text\", \"image\", \"tool_use\", \"tool_result\", \"thinking\"",
                    "type": "string"
                }
            }
        },
        "github_com_papercomputeco_tapes_pkg_llm.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "github_com_papercomputeco_tapes_pkg_llm.Usage": {
            "type": "object",
            "properties": {
                "cache_creation_input_tokens": {
                    "description": "Cache token counts (Anthropic prompt caching)",
                    "type": "integer"
                },
                "cache_read_input_tokens": {
                    "type": "integer"
                },
                "completion_tokens": {
                    "type": "integer"
                },
                "prompt_duration_ns": {
                    "description": "PromptDurationNs is provider-reported prompt-evaluation time, in\nnanoseconds. Populated by providers that surface it (currently Ollama\nonly); left at zero otherwise.",
                    "type": "integer"
                },
                "prompt_tokens": {
                    "description": "Token counts",
                    "type": "integer"
                },
                "total_duration_ns": {
                    "description": "TotalDurationNs is the proxy-measured wall-clock time, in nanoseconds,\nfrom when the proxy received the client request to when the upstream\nresponse was fully assembled. Set uniformly by the proxy across providers\n— Anthropic and OpenAI don't surface a duration field on the wire, and\nOllama's server-internal ` + "`" + `total_duration` + "`" + ` is intentionally overwritten so\naggregate stats compare apples to apples.",
                    "type": "integer"
                },
                "total_tokens": {
                    "type": "integer"
                }
            }
        },
        "github_com_papercomputeco_tapes_pkg_sessions.SessionSummary": {
            "type": "object",
            "properties": {
                "agent_name": {
                    "type": "string"
                },
                "duration_ns": {
                    "$ref": "#/definitions/time.Duration"
                },
                "end_time": {
                    "type": "string"
                },
                "harness_id": {
                    "type": "string"
                },
                "harness_session_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "input_cost": {
                    "type": "number"
                },
                "input_tokens": {
                    "type": "integer"
                },
                "label": {
                    "type": "string"
                },
                "message_count": {
                    "type": "integer"
                },
                "missing_parent": {
                    "type": "string"
                },
                "model": {
                    "type": "string"
                },
                "output_cost": {
                    "type": "number"
                },
                "output_tokens": {
                    "type": "integer"
                },
                "project": {
                    "type": "string"
                },
                "session_count": {
                    "type": "integer"
                },
                "start_time": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "tool_calls": {
                    "type": "integer"
                },
                "total_cost": {
                    "type": "number"
                },
                "truncated": {
                    "description": "Truncated is true when this summary was built from a partial chain\nbecause an ancestor's parent_hash could not be resolved in the\ncurrent store. MissingParent names the hash that would have\ncontinued the walk if the referenced node existed. Both fields are\ninformational — they signal that higher ancestors may live outside\nthis store (trimmed history, foreign chain, offloaded data) rather\nthan an error.",
                    "type": "boolean"
                }
            }
        },
        "time.Duration": {
            "type": "integer",
            "format": "int64",
            "enum": [
                -9223372036854775808,
                9223372036854775807,
                1,
                1000,
                1000000,
                1000000000,
                60000000000,
                3600000000000
            ],
            "x-enum-varnames": [
                "minDuration",
                "maxDuration",
                "Nanosecond",
                "Microsecond",
                "Millisecond",
                "Second",
                "Minute",
                "Hour"
            ]
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Tapes API",
	Description:      "HTTP API for inspecting, querying, and searching stored Tapes sessions.\n\nThe REST surface exposes health checks, session listing and retrieval, derived session summaries, aggregate stats, semantic search, and a streamable MCP endpoint.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
