name: Release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: depot-ubuntu-24.04
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@d96678350ffd6a456235832eb11e1c491589b7bb # v3.21.8

      - name: Cache Nix store
        uses: DeterminateSystems/magic-nix-cache-action@908b263ff629f4cc17666315b7fd3ec127c6244d # v14

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Login to ECR Public
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: Push tapes image
        run: |
          nix develop --command dagger call \
            build-push-tapes-images \
              --registry=${{ vars.REGISTRY }} \
              --tags="${{ github.event.release.tag_name }}" \
              --tags="latest" \
              --version="${{ github.event.release.tag_name }}" \
              --commit="${{ github.sha }}" \
        env:
          DAGGER_CLOUD_TOKEN: ${{ secrets.DAGGER_CLOUD_TOKEN }}

      - name: Build upload release artifacts
        run: |
          nix develop --command dagger call \
            release-latest \
              --version="${{ github.event.release.tag_name }}" \
              --commit="${{ github.sha }}" \
              --post-hog-public-key="${{ secrets.POSTHOG_API_KEY }}" \
              --endpoint=env://BUCKET_ENDPOINT \
              --bucket=env://BUCKET_NAME \
              --access-key-id=env://BUCKET_ACCESS_KEY_ID \
              --secret-access-key=env://BUCKET_SECRET_ACCESS_KEY \
            export \
              --path=./build
        env:
          BUCKET_ENDPOINT: ${{ secrets.BUCKET_ENDPOINT }}
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
          BUCKET_ACCESS_KEY_ID: ${{ secrets.BUCKET_ACCESS_KEY_ID }}
          BUCKET_SECRET_ACCESS_KEY: ${{ secrets.BUCKET_SECRET_ACCESS_KEY }}
          DAGGER_CLOUD_TOKEN: ${{ secrets.DAGGER_CLOUD_TOKEN }}

      - name: Upload artifacts to release
        run: |
          mkdir -p dist
          for file in $(find build -type f); do
            rel_path="${file#build/}"
            os=$(dirname "$rel_path" | cut -d'/' -f1)
            arch=$(dirname "$rel_path" | cut -d'/' -f2)
            filename=$(basename "$file")

            if [[ "$filename" == *.sha256 ]]; then
              base="${filename%.sha256}"
              new_name="${base}-${os}-${arch}.sha256"
            else
              new_name="${filename}-${os}-${arch}"
            fi

            cp "$file" "dist/$new_name"
          done

          gh release upload "${{ github.event.release.tag_name }}" dist/*
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
