// Code generated by ent, DO NOT EDIT.

package agenttracefile

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/papercomputeco/tapes/pkg/storage/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.AgentTraceFile {
	return predicate.AgentTraceFile(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.AgentTraceFile {
	return predicate.AgentTraceFile(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.AgentTraceFile {
	return predicate.AgentTraceFile(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.AgentTraceFile {
	return predicate.AgentTraceFile(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.AgentTraceFile {
	return predicate.AgentTraceFile(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.AgentTraceFile {
	return predicate.AgentTraceFile(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.AgentTraceFile {
	return predicate.AgentTraceFile(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.AgentTraceFile {
	return predicate.AgentTraceFile(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.AgentTraceFile {
	return predicate.AgentTraceFile(sql.FieldLTE(FieldID, id))
}

// Path applies equality check predicate on the "path" field. It's identical to PathEQ.
func Path(v string) predicate.AgentTraceFile {
	return predicate.AgentTraceFile(sql.FieldEQ(FieldPath, v))
}

// PathEQ applies the EQ predicate on the "path" field.
func PathEQ(v string) predicate.AgentTraceFile {
	return predicate.AgentTraceFile(sql.FieldEQ(FieldPath, v))
}

// PathNEQ applies the NEQ predicate on the "path" field.
func PathNEQ(v string) predicate.AgentTraceFile {
	return predicate.AgentTraceFile(sql.FieldNEQ(FieldPath, v))
}

// PathIn applies the In predicate on the "path" field.
func PathIn(vs ...string) predicate.AgentTraceFile {
	return predicate.AgentTraceFile(sql.FieldIn(FieldPath, vs...))
}

// PathNotIn applies the NotIn predicate on the "path" field.
func PathNotIn(vs ...string) predicate.AgentTraceFile {
	return predicate.AgentTraceFile(sql.FieldNotIn(FieldPath, vs...))
}

// PathGT applies the GT predicate on the "path" field.
func PathGT(v string) predicate.AgentTraceFile {
	return predicate.AgentTraceFile(sql.FieldGT(FieldPath, v))
}

// PathGTE applies the GTE predicate on the "path" field.
func PathGTE(v string) predicate.AgentTraceFile {
	return predicate.AgentTraceFile(sql.FieldGTE(FieldPath, v))
}

// PathLT applies the LT predicate on the "path" field.
func PathLT(v string) predicate.AgentTraceFile {
	return predicate.AgentTraceFile(sql.FieldLT(FieldPath, v))
}

// PathLTE applies the LTE predicate on the "path" field.
func PathLTE(v string) predicate.AgentTraceFile {
	return predicate.AgentTraceFile(sql.FieldLTE(FieldPath, v))
}

// PathContains applies the Contains predicate on the "path" field.
func PathContains(v string) predicate.AgentTraceFile {
	return predicate.AgentTraceFile(sql.FieldContains(FieldPath, v))
}

// PathHasPrefix applies the HasPrefix predicate on the "path" field.
func PathHasPrefix(v string) predicate.AgentTraceFile {
	return predicate.AgentTraceFile(sql.FieldHasPrefix(FieldPath, v))
}

// PathHasSuffix applies the HasSuffix predicate on the "path" field.
func PathHasSuffix(v string) predicate.AgentTraceFile {
	return predicate.AgentTraceFile(sql.FieldHasSuffix(FieldPath, v))
}

// PathEqualFold applies the EqualFold predicate on the "path" field.
func PathEqualFold(v string) predicate.AgentTraceFile {
	return predicate.AgentTraceFile(sql.FieldEqualFold(FieldPath, v))
}

// PathContainsFold applies the ContainsFold predicate on the "path" field.
func PathContainsFold(v string) predicate.AgentTraceFile {
	return predicate.AgentTraceFile(sql.FieldContainsFold(FieldPath, v))
}

// HasTrace applies the HasEdge predicate on the "trace" edge.
func HasTrace() predicate.AgentTraceFile {
	return predicate.AgentTraceFile(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TraceTable, TraceColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTraceWith applies the HasEdge predicate on the "trace" edge with a given conditions (other predicates).
func HasTraceWith(preds ...predicate.AgentTrace) predicate.AgentTraceFile {
	return predicate.AgentTraceFile(func(s *sql.Selector) {
		step := newTraceStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasConversations applies the HasEdge predicate on the "conversations" edge.
func HasConversations() predicate.AgentTraceFile {
	return predicate.AgentTraceFile(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ConversationsTable, ConversationsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasConversationsWith applies the HasEdge predicate on the "conversations" edge with a given conditions (other predicates).
func HasConversationsWith(preds ...predicate.AgentTraceConversation) predicate.AgentTraceFile {
	return predicate.AgentTraceFile(func(s *sql.Selector) {
		step := newConversationsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AgentTraceFile) predicate.AgentTraceFile {
	return predicate.AgentTraceFile(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AgentTraceFile) predicate.AgentTraceFile {
	return predicate.AgentTraceFile(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AgentTraceFile) predicate.AgentTraceFile {
	return predicate.AgentTraceFile(sql.NotPredicates(p))
}
